import test from 'node:test';import assert from 'node:assert/strict'
import { DialogueDatabase } from '../src/dialogue/dialogueDatabase.js';import { defineDialogue } from '../src/dialogue/dialogueModels.js';import { DialogueRepository } from '../src/dialogue/dialogueRepository.js';import { DialogueChoiceResolver,DialogueTextResolver } from '../src/dialogue/dialogueResolvers.js';import { DialogueCostService,DialogueEffectExecutor,DialogueSelectionService,DialogueSessionService } from '../src/dialogue/dialogueServices.js';import { DIALOGUE_CHOICE_STATE,DIALOGUE_EFFECT,DIALOGUE_REPEAT } from '../src/dialogue/dialogueConstants.js';import { dialogueDefinitions,DIALOGUE_NPCS } from '../src/dialogue/dialogueDefinitions.js'
const character=()=>({name:'Arin',gold:20,stats:{perception:3},discoveredKnowledge:[]});const context=(extra={})=>({character:character(),worldDay:1,worldTime:{hour:6},worldState:{worldFlags:{}},regionState:{activeFlags:[]},npcState:{metPlayer:false,localFlags:{},localCounters:{}},randomSource:()=>.5,...extra})
const dialogue=(id='test',extra={})=>defineDialogue({id,npcId:'npc',priority:1,startNodeId:'start',nodeDefinitions:[{id:'start',text:'Hello {playerName}.',choices:[{id:'next',text:'Continue',nextNodeId:'end'}]},{id:'end',text:'Goodbye.',endsDialogue:true}],...extra})
const engine=(defs=[dialogue()])=>{const database=new DialogueDatabase(defs,['npc']);const repository=new DialogueRepository;const service=new DialogueSessionService({database,repository});return{database,repository,service}}
test('definitions validate NPC, start nodes and stable example data',()=>{assert.equal(new DialogueDatabase([dialogue()],['npc']).validate().valid,true);assert.equal(new DialogueDatabase([dialogue('bad',{npcId:null})],['npc']).validate().valid,false);assert.equal(new DialogueDatabase([dialogue('bad-start',{startNodeId:'missing'})],['npc']).validate().valid,false);assert.equal(new DialogueDatabase(dialogueDefinitions,Object.keys(DIALOGUE_NPCS)).validate().valid,true)})
test('selection uses priority and a stable id tie-break',()=>{const low=dialogue('z',{priority:1}),a=dialogue('a',{priority:5}),b=dialogue('b',{priority:5});const db=new DialogueDatabase([low,b,a],['npc']),repo=new DialogueRepository,selection=new DialogueSelectionService(db,repo);assert.equal(selection.preview('npc',context()).selected.id,'a')})
test('disabled and unavailable definitions are rejected',()=>{const blocked=dialogue('blocked',{priority:20,availabilityRequirements:[{type:'gold',minimum:99}]}),disabled=dialogue('disabled',{priority:30,enabled:false}),fallback=dialogue('fallback');const db=new DialogueDatabase([blocked,disabled,fallback],['npc']),selection=new DialogueSelectionService(db,new DialogueRepository);assert.equal(selection.preview('npc',context()).selected.id,'fallback')})
test('session starts once, resolves node tokens and marks NPC met',()=>{const e=engine(),c=context();const started=e.service.startNpc('npc',c);assert.equal(started.code,'DIALOGUE_NODE_ENTERED');assert.equal(started.view.text,'Hello Arin.');assert.equal(c.npcState.metPlayer,true);assert.equal(e.service.startNpc('npc',c).code,'DIALOGUE_SESSION_ALREADY_ACTIVE')})
test('missing text tokens are safe warnings',()=>{const r=new DialogueTextResolver().resolve('Hello {missing}.',context());assert.equal(r.text,'Hello [missing].');assert.deepEqual(r.warnings,['missing'])})
test('choice resolver distinguishes Hidden, Locked, Available and Exhausted',()=>{const resolver=new DialogueChoiceResolver,state={usedChoiceIds:['once'],choiceUseCounters:{},localFlags:{}},session={sessionUsedChoiceIds:[]},base={...context(),dialogueState:state,session};assert.equal(resolver.resolve({id:'hidden',enabled:true,visibilityRequirements:[{type:'dialogue_flag',flag:'secret'}],availabilityRequirements:[],costs:[],repeatPolicy:DIALOGUE_REPEAT.ALWAYS},base).state,DIALOGUE_CHOICE_STATE.HIDDEN);assert.equal(resolver.resolve({id:'locked',enabled:true,visibilityRequirements:[],availabilityRequirements:[{type:'gold',minimum:99}],costs:[],repeatPolicy:DIALOGUE_REPEAT.ALWAYS},base).state,DIALOGUE_CHOICE_STATE.LOCKED);assert.equal(resolver.resolve({id:'open',enabled:true,visibilityRequirements:[],availabilityRequirements:[],costs:[],repeatPolicy:DIALOGUE_REPEAT.ALWAYS},base).state,DIALOGUE_CHOICE_STATE.AVAILABLE);assert.equal(resolver.resolve({id:'once',enabled:true,visibilityRequirements:[],availabilityRequirements:[],costs:[],repeatPolicy:DIALOGUE_REPEAT.ONCE_EVER},base).state,DIALOGUE_CHOICE_STATE.EXHAUSTED)})
test('Gold cost previews, applies and rolls back atomically',()=>{const service=new DialogueCostService,c=context(),costs=[{type:'Gold',quantity:5}];assert.equal(service.preview(costs,c).ok,true);assert.equal(c.character.gold,20);const applied=service.apply(costs,c);assert.equal(c.character.gold,15);service.rollback(applied.snapshot,c);assert.equal(c.character.gold,20);assert.equal(service.preview([{type:'Gold',quantity:99}],c).ok,false)})
test('required effect failure rolls back prior effects and marker',()=>{const executor=new DialogueEffectExecutor,c={...context(),dialogueState:{localFlags:{},exhaustedTopicIds:[],appliedEffectIds:[]}};const result=executor.apply([{id:'gold',effectType:DIALOGUE_EFFECT.GRANT_GOLD,quantity:10},{id:'bad',effectType:'Missing',required:true}],c,'choice');assert.equal(result.code,'DIALOGUE_EFFECT_ROLLED_BACK');assert.equal(c.character.gold,20);assert.deepEqual(c.dialogueState.appliedEffectIds,[])})
test('effects are idempotent and sessions save current node and history',()=>{const d=dialogue('flow',{nodeDefinitions:[{id:'start',text:'Start',choices:[{id:'pay',text:'Pay',costs:[{type:'Gold',quantity:5}],effects:[{id:'flag',effectType:DIALOGUE_EFFECT.SET_WORLD_FLAG,flag:'paid'}],nextNodeId:'middle'}]},{id:'middle',text:'Middle',choices:[{id:'leave',text:'Leave',endsDialogue:true}]}]}),e=engine([d]),c=context();e.service.start('flow',c);assert.equal(e.service.choose('pay',c).view.nodeId,'middle');assert.equal(c.character.gold,15);assert.equal(c.worldState.worldFlags.paid,true);const saved=e.repository.serialize();assert.equal(saved.activeSession.currentNodeId,'middle');e.service.choose('leave',c);assert.equal(e.repository.runtime.history.length,1);assert.equal(e.repository.runtime.activeSession,null)})
test('controlled checks are stored and not rerolled',()=>{let rolls=0;const d=dialogue('check',{nodeDefinitions:[{id:'start',text:'Start',choices:[{id:'try',text:'Try',check:{stat:'perception',difficulty:8},nextNodeId:'end',failureNodeId:'end'}]},{id:'end',text:'Done',choices:[{id:'leave',text:'Leave',endsDialogue:true}]}]}),e=engine([d]),c=context({randomSource:()=>{rolls++;return .5}});e.service.start('check',c);e.service.choose('try',c);assert.equal(rolls,1);const state=e.repository.state(d);assert.ok(state.storedCheckResults['dialogue-1:try']);assert.equal(e.service.checkResolver.resolve({stat:'perception',difficulty:8},{...c,dialogueState:state},'dialogue-1:try').success,true);assert.equal(rolls,1)})
