import test from 'node:test'
import assert from 'node:assert/strict'
import { ENCOUNTER_COOLDOWN_TYPE, ENCOUNTER_REPEAT_POLICY, ENCOUNTER_SELECTION_RESULT, ENCOUNTER_TIME_WINDOW } from '../src/encounters/encounterConstants.js'
import { defineEncounter, defineEncounterTable, defineEncounterTableEntry } from '../src/encounters/encounterModels.js'
import { EncounterDatabase } from '../src/encounters/encounterDatabase.js'
import { createEmptyEncounterRunState, EncounterStateRepository, normalizeEncounterRunState } from '../src/encounters/encounterRepository.js'
import { EncounterTableResolver, matchesTimeWindow } from '../src/encounters/encounterTableResolver.js'
import { createSeededRandom, EncounterSelectionService } from '../src/encounters/encounterSelectionService.js'
import { createNewRun } from '../src/game/gameState.js'
import { migrateSave } from '../src/game/saveService.js'

const encounter = (id, data = {}) => defineEncounter({ id, displayName: id, weight: 1, ...data })
const table = (id, ids, data = {}) => defineEncounterTable({ id, encounterEntries: ids.map((entry) => typeof entry === 'string' ? defineEncounterTableEntry({ encounterDefinitionId: entry }) : defineEncounterTableEntry(entry)), ...data })
const context = (data = {}) => ({ runId: 'run', regionId: 'meadows', biomeTags: ['forest'], locationId: 'road-1', locationTags: ['Road'], worldDay: 2, worldTime: { hour: 12, minute: 0 }, regionThreatLevel: 2, nightThreatPercent: 20, worldFlags: {}, regionFlags: {}, randomSource: () => .1, ...data })
const setup = (encounters, tables, state = createEmptyEncounterRunState()) => { const database = new EncounterDatabase({ encounters, tables }); const stateRepository = new EncounterStateRepository(state); return { database, stateRepository, resolver: new EncounterTableResolver(database), service: new EncounterSelectionService({ database, stateRepository, runSeed: 'seed' }) } }

test('definitions, tables and database queries are data-driven', () => { const e = encounter('wolf', { encounterType: 'Creature', tags: ['wolf'] }); const t = table('road', ['wolf'], { regionIds: ['meadows'] }); const { database } = setup([e], [t]); assert.equal(database.getEncounter('wolf'), e); assert.equal(database.getTable('road'), t); assert.equal(database.getEncountersByTag('wolf').length, 1); assert.equal(database.getTablesByRegion('meadows').length, 1) })
test('validation detects duplicates, missing entries, fallback cycles and negative weights', () => { const bad = encounter('same', { weight: -1 }); const a = table('a', [{ encounterDefinitionId: 'missing', weight: -2 }], { fallbackEncounterTableId: 'b' }); const b = table('b', [], { fallbackEncounterTableId: 'a', noEncounterWeight: 1 }); const database = new EncounterDatabase({ encounters: [bad, bad], tables: [a, b] }); const validation = database.validate(); for (const code of ['DUPLICATE_ENCOUNTER_ID', 'NEGATIVE_ENCOUNTER_WEIGHT', 'MISSING_ENCOUNTER_DEFINITION', 'NEGATIVE_ENTRY_WEIGHT', 'FALLBACK_CYCLE']) assert.ok(validation.errors.some((error) => error.code === code), code) })
test('validation detects missing fallback and empty active table', () => { const database = new EncounterDatabase({ encounters: [], tables: [table('empty', [], { allowNoEncounterResult: false, noEncounterWeight: 0, fallbackEncounterTableId: 'missing' })] }); const codes = database.validate().errors.map(({ code }) => code); assert.ok(codes.includes('MISSING_FALLBACK_TABLE')); assert.ok(codes.includes('EMPTY_ACTIVE_TABLE')) })
test('table resolver prioritizes exact location, then region, biome and global', () => { const e = encounter('e'); const tables = [table('global', ['e']), table('biome', ['e'], { biomeTags: ['forest'] }), table('region', ['e'], { regionIds: ['meadows'] }), table('location', ['e'], { locationTags: ['Road'] })]; const { resolver } = setup([e], tables); assert.equal(resolver.resolve(context()).matchingTables[0].table.id, 'location'); assert.equal(resolver.resolve(context({ locationTags: ['Wilderness'] })).matchingTables[0].table.id, 'region'); assert.equal(resolver.resolve(context({ regionId: 'other', locationTags: ['Wilderness'] })).matchingTables[0].table.id, 'biome'); assert.equal(resolver.resolve(context({ regionId: 'other', biomeTags: ['desert'], locationTags: ['Wilderness'] })).matchingTables[0].table.id, 'global') })
test('disabled tables and safe zones are filtered unless explicitly allowed', () => { const e = encounter('e'); const { resolver } = setup([e], [table('disabled', ['e'], { enabled: false }), table('unsafe', ['e']), table('safe', ['e'], { allowInSafeZone: true })]); const result = resolver.resolve(context({ currentSafeZoneStatus: true })); assert.deepEqual(result.matchingTables.map(({ table }) => table.id), ['safe']); assert.ok(result.rejectedTables.some(({ reasons }) => reasons.includes('TABLE_DISABLED'))); assert.ok(result.rejectedTables.some(({ reasons }) => reasons.includes('SAFE_ZONE_BLOCKED'))) })
test('day, night, dawn, dusk and custom time windows use central clock boundaries', () => { assert.equal(matchesTimeWindow(ENCOUNTER_TIME_WINDOW.DAY, context({ worldTime: { hour: 12 } })), true); assert.equal(matchesTimeWindow(ENCOUNTER_TIME_WINDOW.NIGHT, context({ worldTime: { hour: 22 } })), true); assert.equal(matchesTimeWindow(ENCOUNTER_TIME_WINDOW.DAWN, context({ worldTime: { hour: 6 } })), true); assert.equal(matchesTimeWindow(ENCOUNTER_TIME_WINDOW.DUSK, context({ worldTime: { hour: 19 } })), true); assert.equal(matchesTimeWindow({ type: ENCOUNTER_TIME_WINDOW.CUSTOM, start: 23 * 60, end: 2 * 60 }, context({ worldTime: { hour: 1 } })), true) })
test('candidate filtering covers region, biome, location, time, threats and world day', () => { const e = encounter('strict', { regionTags: ['meadows'], biomeTags: ['forest'], allowedLocationTags: ['Road'], dayOnly: true, minimumThreatLevel: 2, maximumThreatLevel: 3, minimumNightThreatPercent: 10, maximumNightThreatPercent: 30, minimumWorldDay: 2, maximumWorldDay: 3 }); const { service } = setup([e], [table('t', ['strict'])]); assert.equal(service.previewEncounterSelection(context()).eligibleEncounters.length, 1); for (const changed of [{ regionId: 'x' }, { biomeTags: ['hills'] }, { locationTags: ['Wilderness'] }, { worldTime: { hour: 22 } }, { regionThreatLevel: 4 }, { nightThreatPercent: 40 }, { worldDay: 4 }]) assert.equal(service.previewEncounterSelection(context(changed)).eligibleEncounters.length, 0) })
test('requirements and required or blocked flags filter candidates', () => { const e = encounter('flagged', { requirements: [{ type: 'world_day', minimum: 2 }] }); const t = table('t', [{ encounterDefinitionId: 'flagged', requiredWorldFlags: ['open'], blockedWorldFlags: ['closed'], requiredRegionFlags: ['calm'] }]); const { service } = setup([e], [t]); assert.equal(service.previewEncounterSelection(context({ worldFlags: { open: true }, regionFlags: { calm: true } })).eligibleEncounters.length, 1); assert.equal(service.previewEncounterSelection(context({ worldFlags: {}, regionFlags: { calm: true } })).eligibleEncounters.length, 0); assert.equal(service.previewEncounterSelection(context({ worldFlags: { open: true, closed: true }, regionFlags: { calm: true } })).eligibleEncounters.length, 0) })
test('limited, unique, disabled and zero-weight encounters are rejected', () => { const encounters = [encounter('limited', { repeatPolicy: ENCOUNTER_REPEAT_POLICY.LIMITED_PER_RUN, maximumOccurrencesPerRun: 1 }), encounter('unique', { uniquePerRun: true }), encounter('zero', { weight: 0 }), encounter('disabled', { enabled: false })]; const state = createEmptyEncounterRunState(); state.occurrenceCountersByEncounterId.limited = 1; state.uniqueEncounterIdsUsed.push('unique'); const { service } = setup(encounters, [table('t', encounters.map(({ id }) => id))], state); const preview = service.previewEncounterSelection(context()); assert.equal(preview.eligibleEncounters.length, 0); assert.ok(preview.rejectedEncounters.some(({ reasons }) => reasons.includes('OCCURRENCE_LIMIT_REACHED'))); assert.ok(preview.rejectedEncounters.some(({ reasons }) => reasons.includes('UNIQUE_ENCOUNTER_ALREADY_USED'))); assert.ok(preview.rejectedEncounters.some(({ reasons }) => reasons.includes('INVALID_ENCOUNTER_WEIGHT'))) })
test('cooldown supports WorldMinutes and EncounterCount', () => { const a = encounter('a'); const b = encounter('b'); const state = createEmptyEncounterRunState(); state.cooldowns.a = { type: ENCOUNTER_COOLDOWN_TYPE.WORLD_MINUTES, value: 60, startedWorldMinutes: 2 * 1440 + 12 * 60 }; state.cooldowns.b = { type: ENCOUNTER_COOLDOWN_TYPE.ENCOUNTER_COUNT, value: 2, startedEncounterCount: 0 }; state.triggeredEncounterCount = 1; const { service } = setup([a, b], [table('t', ['a', 'b'])], state); assert.equal(service.previewEncounterSelection(context()).eligibleEncounters.length, 0); assert.equal(service.previewEncounterSelection(context({ worldTime: { hour: 14 } })).eligibleEncounters.find(({ definition }) => definition.id === 'a').cooldownActive, false) })
test('immediate and recent repetition rules modify or reject candidates', () => { const blocked = encounter('blocked', { blockImmediateRepeat: true }); const weighted = encounter('weighted', { repeatedEncounterWeightMultiplier: .25 }); const state = createEmptyEncounterRunState(); state.lastEncounterId = 'blocked'; state.recentEncounterIds = ['weighted', 'blocked']; const { service } = setup([blocked, weighted], [table('t', ['blocked', 'weighted'])], state); const preview = service.previewEncounterSelection(context()); assert.ok(preview.rejectedEncounters.find(({ definition }) => definition.id === 'blocked').reasons.includes('IMMEDIATE_REPEAT_BLOCKED')); assert.equal(preview.eligibleEncounters.find(({ definition }) => definition.id === 'weighted').repetitionModifier, .25) })
test('No Encounter is a selected result and does not create an instance', () => { const { service, stateRepository } = setup([encounter('e')], [table('t', ['e'], { noEncounterWeight: 100 })]); const result = service.selectEncounter(context({ randomSource: () => .99 })); assert.equal(result.resultCode, ENCOUNTER_SELECTION_RESULT.NONE); assert.equal(result.noEncounterSelected, true); assert.equal(stateRepository.instances.getAll().length, 0) })
test('fallback is used only when primary table has no valid candidate and no valid No Encounter', () => { const disabled = encounter('disabled', { enabled: false }); const valid = encounter('valid'); const primary = table('primary', ['disabled'], { locationTags: ['Road'], fallbackEncounterTableId: 'fallback', allowNoEncounterResult: false }); const fallback = table('fallback', ['valid']); const { service } = setup([disabled, valid], [primary, fallback]); const preview = service.previewEncounterSelection(context()); assert.equal(preview.fallbackUsed, true); assert.equal(preview.selectedTableId, 'fallback') })
test('controlled RNG is deterministic and preview is side-effect free', () => { const encounters = [encounter('a'), encounter('b')]; const make = () => setup(encounters, [table('t', ['a', 'b'])]); const first = make(); const before = first.stateRepository.serialize(); const preview = first.service.previewEncounterSelection(context()); assert.equal(preview.success, true); assert.deepEqual(first.stateRepository.serialize(), before); const one = make().service.selectEncounter(context({ randomSource: createSeededRandom('same') })); const two = make().service.selectEncounter(context({ randomSource: createSeededRandom('same') })); assert.equal(one.selectedEncounterDefinitionId, two.selectedEncounterDefinitionId) })
test('selection creates a Selected instance but counters update only on trigger', () => { const { service, stateRepository } = setup([encounter('a')], [table('t', ['a'])]); const result = service.selectEncounter(context()); assert.equal(result.resultCode, ENCOUNTER_SELECTION_RESULT.SELECTED); assert.equal(result.encounterInstance.currentPhase, 'Selected'); assert.equal(stateRepository.state.occurrenceCountersByEncounterId.a, undefined); service.markEncounterTriggered(result.encounterInstanceId); assert.equal(stateRepository.state.occurrenceCountersByEncounterId.a, 1); service.markEncounterResolved(result.encounterInstanceId, 'Completed'); assert.equal(stateRepository.state.historyRecords.length, 1) })
test('forced encounter and forced table are consumed after selection', () => { const { service, stateRepository } = setup([encounter('a'), encounter('b')], [table('a-table', ['a']), table('b-table', ['b'])]); stateRepository.state.forcedNextEncounterTableId = 'b-table'; stateRepository.state.forcedNextEncounterId = 'b'; const result = service.selectEncounter(context()); assert.equal(result.selectedEncounterDefinitionId, 'b'); assert.equal(stateRepository.state.forcedNextEncounterId, null); assert.equal(stateRepository.state.forcedNextEncounterTableId, null) })
test('state normalization persists instances, history, counters, cooldowns and forced IDs', () => { const state = createEmptyEncounterRunState(); state.encounterInstances.push({ instanceId: 'i' }); state.historyRecords.push({ result: 'Completed' }); state.occurrenceCountersByEncounterId.a = 2; state.cooldowns.a = { type: 'EncounterCount', value: 2 }; state.forcedNextEncounterId = 'a'; const restored = normalizeEncounterRunState(JSON.parse(JSON.stringify(state))); assert.equal(restored.encounterInstances[0].instanceId, 'i'); assert.equal(restored.historyRecords.length, 1); assert.equal(restored.occurrenceCountersByEncounterId.a, 2); assert.equal(restored.cooldowns.a.value, 2); assert.equal(restored.forcedNextEncounterId, 'a') })
test('legacy save migration and New Run create safe empty encounter state', () => { const migrated = migrateSave({ saveVersion: 7 }); assert.equal(migrated.encounterState.encounterSequenceCounter, 0); const run = createNewRun(null, { seed: 'encounter-new-run', runId: 'run-encounter', now: () => 'now' }); assert.equal(run.encounterState.encounterInstances.length, 0); assert.equal(run.encounterState.travelState.encounterMeterValue, 0); assert.ok(run.encounterState.travelState.encounterMeterThreshold >= 11) })
