import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import { encounterDatabase } from '../src/encounters/encounterDatabase.js'
import { createEncounterInstance } from '../src/encounters/encounterModels.js'
import { createInitialEncounterRunState, EncounterStateRepository } from '../src/encounters/encounterRepository.js'
import { EncounterDetectionService } from '../src/encounters/encounterDetectionService.js'
import { EncounterPresentationCoordinator } from '../src/encounters/encounterPresentationCoordinator.js'
import { EncounterChoiceAvailabilityResolver } from '../src/encounters/encounterChoiceService.js'
import { createEncounterPresentationModel } from '../src/encounters/encounterPresentationService.js'
import { validateEncounterInteractions } from '../src/encounters/encounterInteractionValidator.js'
import { NotificationService } from '../src/ui/notificationService.js'
import { ENCOUNTER_PHASE } from '../src/encounters/encounterConstants.js'

const root = new URL('../', import.meta.url)
const source = (path) => fs.readFileSync(new URL(path, root), 'utf8')
const create = (encounterDefinitionId = 'bandit_ambush') => {
  const stateRepository = new EncounterStateRepository(createInitialEncounterRunState('ui', 'run'))
  const instance = createEncounterInstance({ instanceId: 'pending-ui', encounterDefinitionId, seed: 'ui-seed', generatedForRunId: 'run', regionId: 'meadows', currentPhase: ENCOUNTER_PHASE.PENDING_TRIGGER })
  stateRepository.instances.save(instance); Object.assign(stateRepository.state.travelState, { pendingEncounterInstanceId: instance.instanceId, movementBlockedByEncounter: true })
  const context = { characterState: { inventory: [], gold: 0, stats: { perception: 20, luck: 3 }, proficiencySkills: {} }, characterStats: { finalStats: { perception: 20, luck: 3 }, baseStats: { perception: 20, luck: 3 } }, randomSource: () => 0.5 }
  const detectionService = new EncounterDetectionService({ database: encounterDatabase, stateRepository, runSeed: 'ui' })
  const availabilityResolver = new EncounterChoiceAvailabilityResolver()
  const notifications = new NotificationService(); let executed = 0
  const choiceService = { preview: () => ({ ok: true }), execute: () => { executed += 1; return { ok: true, code: 'CHOICE_CHECK_SUCCESS' } } }
  const coordinator = new EncounterPresentationCoordinator({ database: encounterDatabase, stateRepository, detectionService, choiceService, resolutionService: {}, availabilityResolver, contextFactory: () => context, notificationService: notifications })
  return { coordinator, stateRepository, detectionService, context, notifications, executed: () => executed }
}

test('pending encounter opens one mandatory overlay model and preserves movement lock', () => { const system = create(); assert.equal(system.coordinator.openPending().ok, true); assert.equal(system.coordinator.presentation().instanceId, 'pending-ui'); assert.equal(system.stateRepository.state.travelState.movementBlockedByEncounter, true); assert.equal(system.coordinator.openPending().code, 'ENCOUNTER_RECOVERED') })
test('detection presentation hides identity until revealed and exposes only public information', () => { const system = create(); const result = system.coordinator.openPending(); const hidden = createEncounterPresentationModel(result.instance, encounterDatabase.getEncounter('bandit_ambush'), system.coordinator.availabilityResolver, system.context); assert.equal(hidden.displayName, 'Bandit Ambush'); assert.equal('definitionId' in hidden, false); assert.equal(JSON.stringify(hidden).includes('sourceTableId'), false); assert.equal(hidden.detectionPublicStat, 'Perception check'); assert.equal(JSON.stringify(hidden).includes('"roll"'), true); assert.equal(source('src/components/EncounterOverlay.vue').includes('detectionResult.roll'), false) })
test('ambush preparation and current choice set produce accessible choice models', () => { const system = create(); system.coordinator.openPending(); const model = system.coordinator.presentation(); assert.equal(model.isAmbush, true); assert.equal(model.preparationState, 'Alert'); assert.equal(model.currentChoiceSetId, 'bandit_detected'); assert.ok(model.choices.some(({ choice }) => choice.id === 'fight')); assert.ok(!model.choices.some(({ choice }) => choice.id === 'flee')) })
test('coordinator command guard prevents duplicate choice execution', () => { const system = create(); system.coordinator.openPending(); system.coordinator.executeChoice('fight'); assert.equal(system.executed(), 1); system.coordinator.requestId = 'busy'; assert.equal(system.coordinator.executeChoice('fight').code, 'ENCOUNTER_COMMAND_PENDING'); assert.equal(system.executed(), 1) })
test('recovery does not repeat saved detection, combat or reward generation', () => { const system = create(); system.coordinator.openPending(); const instance = system.coordinator.activeInstance; const sequence = instance.detectionSequenceCounter; let recovered = system.coordinator.recoverPendingEncounterState(); assert.equal(recovered.skippedDuplicateDetection, true); assert.equal(instance.detectionSequenceCounter, sequence); instance.pendingCombatId = 'combat-saved'; instance.currentPhase = ENCOUNTER_PHASE.COMBAT_PENDING; system.stateRepository.instances.save(instance); recovered = system.coordinator.recoverPendingEncounterState(); assert.equal(recovered.panel, 'combat'); assert.equal(recovered.skippedDuplicateCombat, true) })
test('pending loot recovery resumes the existing bundle', () => { const system = create('injured_traveler'); system.coordinator.openPending(); const instance = system.coordinator.activeInstance; instance.pendingLootRewardId = 'stable-loot-id'; instance.pendingResolution.generatedLootReward = { entries: [{ type: 'item', displayName: 'Bandage' }] }; instance.pendingResolution.rewardsGenerated = true; system.stateRepository.instances.save(instance); const recovered = system.coordinator.recoverPendingEncounterState(); assert.equal(recovered.panel, 'loot'); assert.equal(recovered.skippedDuplicateRewards, true); assert.equal(system.coordinator.debugView().loot.entries[0].displayName, 'Bandage') })
test('final overlay closes only after resolution and movement unlock', () => { const system = create(); system.coordinator.openPending(); assert.equal(system.coordinator.closeFinalized().code, 'ENCOUNTER_RESOLUTION_PENDING'); const instance = system.coordinator.activeInstance; instance.resolved = true; instance.currentPhase = ENCOUNTER_PHASE.COMPLETED; system.stateRepository.instances.save(instance); system.stateRepository.state.travelState.movementBlockedByEncounter = false; assert.equal(system.coordinator.closeFinalized().code, 'ENCOUNTER_OVERLAY_CLOSED'); assert.equal(system.coordinator.activeInstanceId, null) })
test('notifications map controlled encounter results to player-facing text', () => { const system = create(); const received = []; system.notifications.subscribe((notification) => received.push(notification)); system.coordinator.openPending(); system.coordinator.requestId = 'busy'; system.coordinator.executeChoice('fight'); assert.equal(received.at(-1).code, 'ENCOUNTER_COMMAND_PENDING'); assert.ok(received.at(-1).message.length > 0) })
test('EncounterOverlay contains confirmation, focus, keyboard and responsive behavior without business logic', () => { const ui = source('src/components/EncounterOverlay.vue'); assert.match(ui, /role="dialog"/); assert.match(ui, /role="alertdialog"/); assert.match(ui, /@keydown\.esc\.prevent/); assert.match(ui, /Confirm/); assert.match(ui, /Cancel/); assert.match(ui, /@media\(max-width:760px\)/); assert.doesNotMatch(ui, /Math\.random|rewardService|currentPhase\s*=/) })
test('interaction validator reports missing sets, choices and resolutions', () => { const missingSet = validateEncounterInteractions({ database: encounterDatabase, configs: { bandit_ambush: { detectionDefinitionId: 'automatic', detectedChoiceSetId: 'missing' } } }); assert.ok(missingSet.errors.some(({ code }) => code === 'MISSING_CHOICE_SET')); const missingChoice = validateEncounterInteractions({ database: encounterDatabase, choiceSets: { broken: { id: 'broken', choiceIds: ['missing'] } }, configs: {} }); assert.ok(missingChoice.errors.some(({ code }) => code === 'MISSING_CHOICE')) })
test('map integration uses the coordinator and blocks POI overlap without creating map markers', () => { const menu = source('src/views/MenuThree.vue'); assert.match(menu, /encounterCoordinator\.openPending/); assert.match(menu, /recoverPendingEncounterState/); assert.match(menu, /Resolve the active encounter first/); assert.doesNotMatch(source('src/encounters/encounterPresentationCoordinator.js'), /createPoi|mapMarker/) })
test('Bow and Crossbow encounter UI has no ammunition dependency or Arrow and Bolt rewards', () => { const weapons = source('src/items/itemDatabase.js'); const encounters = fs.readdirSync(new URL('src/encounters/', root)).filter((file) => file.endsWith('.js')).map((file) => source(`src/encounters/${file}`)).join('\n'); assert.match(weapons, /short_bow/); assert.match(weapons, /simple_crossbow/); assert.doesNotMatch(encounters, /arrow reward|bolt reward|requires ammunition/i) })
