import assert from 'node:assert/strict'
import test from 'node:test'
import { createCharacterState, cloneCharacterState, restoreCharacterState } from '../src/game/characterState.js'
import { PROFICIENCY_NAMES } from '../src/data/characterCreation.js'
import { InventoryManager } from '../src/inventory/inventoryManager.js'
import { createItemInstance } from '../src/items/itemInstance.js'
import { createItemUseContext } from '../src/items/itemUseContext.js'
import { ItemUseService, ITEM_USE_ACTION } from '../src/items/itemUseService.js'
import { WardwoodService, WARDWOOD_CONFIG } from '../src/world/wardwoodService.js'
import { consumeLightDuration, isLightActive, LIGHT_SOURCE_TYPE } from '../src/world/lightSourceSystem.js'
import { checkNightEncounter } from '../src/world/nightEncounterService.js'
import { waitUntilMorningProtected } from '../src/world/nightProtectionService.js'

const hero = () => createCharacterState({ id: 'use-hero', name: 'Hero', proficiencies: Object.fromEntries(PROFICIENCY_NAMES.map((name) => [name, ['Camping', 'Swordsmanship'].includes(name) ? 'Novice' : 'Untrained'])), startingWeapon: { id: 'test', combatSkills: [] } })
const setup = () => { const character = hero(); const inventory = new InventoryManager(character); const wardwood = new WardwoodService(character, inventory); const service = new ItemUseService({ character, inventoryManager: inventory, wardwoodService: wardwood }); return { character, inventory, wardwood, service } }
const context = (options = {}) => createItemUseContext({ time: { day: 1, hour: 22, minute: 0, moveCount: 0 }, position: { row: 1, column: 1 }, ...options })
const addWardwood = (state, quantity = 6, day = 1) => { state.wardwood.addBatch(quantity, day); return state.character.inventory.find(({ definitionId }) => definitionId === 'wardwood') }

test('ItemUseService finds ItemInstance and returns controlled errors', () => { const state = setup(); state.inventory.add(createItemInstance('club')); const club = state.character.inventory[0]; assert.equal(state.service.useItem('use-hero', 'missing', context()).code, 'ITEM_NOT_FOUND'); assert.equal(state.service.useItem('use-hero', club.instanceId, context()).code, 'ITEM_NOT_USABLE'); assert.equal(state.service.useItem('use-hero', club.instanceId, null).code, 'ITEM_NOT_USABLE') })
test('Torch use decreases stack, removes empty stack and blocks use during Combat', () => { const state = setup(); const torch = createItemInstance('torch', { quantity: 2 }); state.inventory.add(torch); assert.equal(state.service.useItem('use-hero', torch.instanceId, context({ isCombatActive: true })).code, 'CANNOT_USE_DURING_COMBAT'); assert.equal(state.service.useItem('use-hero', torch.instanceId, context()).ok, true); assert.equal(state.inventory.find(torch.instanceId).quantity, 1); state.character.activeLightSource = null; state.service.useItem('use-hero', torch.instanceId, context()); assert.equal(state.inventory.find(torch.instanceId), null) })
test('Campfire costs configured Wardwood, cannot be built in Safe Zone and blocks movement and Threat', () => { const state = setup(); const wood = addWardwood(state, 5); assert.equal(state.service.useItem('use-hero', wood.instanceId, context({ isSafeZone: true }), ITEM_USE_ACTION.BUILD_CAMPFIRE).code, 'SAFE_ZONE_NOT_REQUIRED'); assert.equal(state.service.useItem('use-hero', wood.instanceId, context(), ITEM_USE_ACTION.BUILD_CAMPFIRE).ok, true); assert.equal(state.character.wardwood, 5 - WARDWOOD_CONFIG.campfireCost); assert.equal(state.character.activeLightSource.isPortable, false); assert.equal(checkNightEncounter({ time: context().time, tile: { terrain: 'grassland' }, lightSource: state.character.activeLightSource, random: () => 0 }).reason, 'PROTECTED') })
test('Wait Until Morning works at Campfire and Safe Zone, but not without protection', () => { const camp = setup(); const wood = addWardwood(camp, 3); camp.service.useItem('use-hero', wood.instanceId, context(), ITEM_USE_ACTION.BUILD_CAMPFIRE); const waited = waitUntilMorningProtected({ character: camp.character, tile: { terrain: 'grassland' }, time: context().time, wardwoodService: camp.wardwood, random: () => 1 }); assert.equal(waited.ok, true); assert.equal(waited.time.hour, 6); assert.equal(waited.time.day, 2); assert.equal(camp.character.activeLightSource, null); const safe = setup(); assert.equal(waitUntilMorningProtected({ character: safe.character, tile: { terrain: 'city' }, time: context().time, wardwoodService: safe.wardwood, random: () => 1 }).ok, true); assert.equal(waitUntilMorningProtected({ character: safe.character, tile: { terrain: 'grassland' }, time: context().time, wardwoodService: safe.wardwood, random: () => 1 }).code, 'SAFE_NIGHT_PROTECTION_REQUIRED') })
test('Torch uses configured world minutes, expires and re-enables Night Threat', () => { const state = setup(); const wood = addWardwood(state, 1); state.service.useItem('use-hero', wood.instanceId, context(), ITEM_USE_ACTION.LIGHT_TORCH); assert.equal(state.character.activeLightSource.remainingDurationMinutes, 120); consumeLightDuration(state.character, 30); assert.equal(state.character.activeLightSource.remainingDurationMinutes, 90); const expired = consumeLightDuration(state.character, 90); assert.equal(expired.expired, true); assert.equal(state.character.activeLightSource, null); assert.equal(checkNightEncounter({ time: context().time, tile: { terrain: 'grassland' }, lightSource: null, random: () => 0 }).triggered, true) })
test('Lantern accepts proportional Wardwood fuel, caps at maximum, toggles and remains in Inventory', () => { const state = setup(); addWardwood(state, 8); const lantern = createItemInstance('lantern'); state.inventory.add(lantern); assert.equal(state.service.useItem('use-hero', lantern.instanceId, context(), ITEM_USE_ACTION.REFUEL_LANTERN).ok, true); assert.equal(state.character.lanternState.remainingFuelMinutes, 480); assert.equal(state.service.useItem('use-hero', lantern.instanceId, context(), ITEM_USE_ACTION.LIGHT_LANTERN).ok, true); consumeLightDuration(state.character, 96); assert.equal(state.character.lanternState.remainingFuelMinutes, 384); state.service.useItem('use-hero', lantern.instanceId, context(), ITEM_USE_ACTION.EXTINGUISH_LANTERN); consumeLightDuration(state.character, 96); assert.equal(state.character.lanternState.remainingFuelMinutes, 384); assert.ok(state.inventory.find(lantern.instanceId)) })
test('Torch and Lantern cannot be active together and Holy Lantern toggles without fuel', () => { const state = setup(); const wood = addWardwood(state, 6); const lantern = createItemInstance('lantern'); const holy = createItemInstance('holy_lantern'); state.inventory.add(lantern); state.inventory.add(holy); state.service.useItem('use-hero', lantern.instanceId, context(), ITEM_USE_ACTION.REFUEL_LANTERN); state.service.useItem('use-hero', wood.instanceId, context(), ITEM_USE_ACTION.LIGHT_TORCH); assert.equal(state.service.useItem('use-hero', lantern.instanceId, context(), ITEM_USE_ACTION.LIGHT_LANTERN).code, 'LIGHT_SOURCE_ALREADY_ACTIVE'); state.character.activeLightSource = null; assert.equal(state.service.useItem('use-hero', holy.instanceId, context(), ITEM_USE_ACTION.TOGGLE_HOLY_LANTERN).ok, true); assert.equal(isLightActive(state.character.activeLightSource), true) })
test('Wardwood batches expire, become one Dead Wardwood stack and FIFO consumes oldest', () => { const state = setup(); state.wardwood.addBatch(2, 1, { id: 'old' }); state.wardwood.addBatch(3, 3, { id: 'new' }); const used = state.wardwood.consume(1, 3); assert.deepEqual(used.consumedBatchIds, ['old']); assert.equal(state.character.wardwoodBatches.find(({ id }) => id === 'old').quantity, 1); const expired = state.wardwood.expire(8); assert.equal(expired.expired, 1); assert.equal(state.character.deadWardwood, 1); assert.equal(state.character.inventory.filter(({ definitionId }) => definitionId === 'dead_wardwood').length, 1); assert.equal(state.wardwood.getSummary(8).quantity, 3) })
test('Campfire recovery uses controlled RNG', () => { const state = setup(); assert.equal(state.wardwood.recoverCampfire(() => 0).recovered, 1); assert.equal(state.wardwood.recoverCampfire(() => 1).recovered, 0) })
test('Save restores light, Lantern, Wardwood batches and legacy defaults', () => { const state = setup(); const wood = addWardwood(state, 3); state.service.useItem('use-hero', wood.instanceId, context(), ITEM_USE_ACTION.LIGHT_TORCH); const restored = restoreCharacterState(JSON.parse(JSON.stringify(cloneCharacterState(state.character))), hero()); assert.equal(restored.activeLightSource.type, LIGHT_SOURCE_TYPE.TORCH); assert.equal(restored.wardwoodBatches.length, 1); assert.equal(restored.lanternState.maximumFuelMinutes, 480); const legacy = restoreCharacterState({ ...hero(), wardwoodBatches: undefined, lanternState: undefined }, hero()); assert.deepEqual(legacy.wardwoodBatches, []); assert.equal(legacy.activeLightSource, null) })
