import assert from 'node:assert/strict'
import test from 'node:test'
import { createCharacterState } from '../src/game/characterState.js'
import { PROFICIENCY_NAMES } from '../src/data/characterCreation.js'
import { InventoryManager } from '../src/inventory/inventoryManager.js'
import { createItemInstance } from '../src/items/itemInstance.js'
import { getItemDefinition } from '../src/items/itemDatabase.js'
import { BookService } from '../src/books/bookService.js'
import { BOOK_CATEGORY, BOOK_KIND, BOOK_STATUS } from '../src/books/bookDefinitions.js'
import { queryLibrary } from '../src/books/bookCollectionService.js'
import { NotificationService } from '../src/ui/notificationService.js'
import { createItemTooltipModel } from '../src/items/itemTooltip.js'
import { RewardService } from '../src/rewards/rewardService.js'
import { defineReward, REWARD_TYPE } from '../src/rewards/rewardDefinitions.js'

const hero = () => createCharacterState({ id: 'knowledge-book-hero', name: 'Reader', proficiencies: Object.fromEntries(PROFICIENCY_NAMES.map((name) => [name, ['Archery', 'Animal Lore'].includes(name) ? 'Novice' : 'Untrained'])), startingWeapon: { id: 'test', combatSkills: [] } })

test('Knowledge remains independent from Attributes and Skills', () => { const character = hero(); const rewards = new RewardService({ character }); const beforeStats = { ...character.stats }; const beforeSkill = character.proficiencySkills.Archery.baseValue; assert.equal(rewards.apply(defineReward(REWARD_TYPE.GRANT_KNOWLEDGE, { knowledgeId: 'old_kingdom_history' })).ok, true); assert.deepEqual(character.stats, beforeStats); assert.equal(character.proficiencySkills.Archery.baseValue, beforeSkill); assert.deepEqual(character.discoveredKnowledge, ['old_kingdom_history']) })
test('BookDefinition and ScrollDefinition expose common data-driven fields and categories', () => { const book = getItemDefinition('history_of_the_old_kingdom').bookData; const scroll = getItemDefinition('archery_skill_scroll').bookData; for (const field of ['kind', 'requirements', 'effects', 'quality', 'manualTier', 'consumable', 'destroyOnUse', 'repeatable', 'category', 'protected']) assert.ok(field in book); assert.equal(book.category, BOOK_CATEGORY.HISTORY); assert.equal(scroll.kind, BOOK_KIND.SKILL_SCROLL); assert.equal(scroll.destroyOnUse, true) })
test("Hunter's Journal atomically grants Skills, Knowledge and its Recipe through RewardService", () => { const character = hero(); const inventory = new InventoryManager(character); const item = createItemInstance('hunters_journal'); inventory.add(item); const notifications = new NotificationService(); const service = new BookService({ character, inventoryManager: inventory, notificationService: notifications }); const result = service.useBook(item, getItemDefinition('hunters_journal'), { time: { day: 3 } }); assert.equal(result.ok, true); assert.equal(result.rewards.length, 4); assert.equal(character.proficiencySkills.Archery.baseValue, 11); assert.equal(character.proficiencySkills['Animal Lore'].baseValue, 11); assert.deepEqual(character.discoveredKnowledge, ['hunters_legacy']); assert.equal(character.recipeState.knownRecipeIds.includes('simple_soup'), true); assert.equal(character.inventory[0].state.known, true); assert.equal(notifications.history.length, 4) })
test('RewardService supports shared Gold, LP, Flag and Maximum Cap reward definitions', () => { const character = hero(); const service = new RewardService({ character }); const result = service.applyMany([defineReward(REWARD_TYPE.GRANT_GOLD, { amount: 12 }), defineReward(REWARD_TYPE.GRANT_LP, { amount: 5 }), defineReward(REWARD_TYPE.GRANT_FLAG, { flag: 'read_test', value: true }), defineReward(REWARD_TYPE.GRANT_MAXIMUM_CAP, { skill: 'Archery', amount: 5 })]); assert.equal(result.ok, true); assert.equal(character.gold, 12); assert.equal(character.learningPoints, 5); assert.equal(character.flags.read_test, true); assert.equal(character.proficiencySkills.Archery.maximumCap, 105) })
test('Library supports statuses, search, category/type filters and sorting', () => { const character = hero(); const inventory = new InventoryManager(character); for (const id of ['history_of_the_old_kingdom', 'basic_archery_manual']) inventory.add(createItemInstance(id, { instanceId: id })); const service = new BookService({ character, inventoryManager: inventory }); service.useBook(inventory.find('history_of_the_old_kingdom'), getItemDefinition('history_of_the_old_kingdom'), { time: { day: 1 } }); service.useBook(inventory.find('basic_archery_manual'), getItemDefinition('basic_archery_manual'), { time: { day: 1 } }); assert.equal(queryLibrary(character, { search: 'history' })[0].status, BOOK_STATUS.KNOWN); assert.equal(queryLibrary(character, { category: BOOK_CATEGORY.COMBAT })[0].status, BOOK_STATUS.CONSUMED); assert.equal(queryLibrary(character, { bookType: BOOK_KIND.KNOWLEDGE_BOOK }).length, 1) })
test('Protected Treatises cannot be manually destroyed while destroy-on-use remains supported', () => { const character = hero(); const inventory = new InventoryManager(character); const item = createItemInstance('archery_master_treatise'); inventory.add(item); assert.equal(inventory.destroy(item.instanceId).code, 'PROTECTED_ITEM'); assert.equal(character.inventory.length, 1) })
test('Book tooltip exposes category, type, requirements, rewards, tier and availability', () => { const character = hero(); const item = getItemDefinition('archery_master_treatise'); const model = createItemTooltipModel(item, character); assert.equal(model.category, BOOK_CATEGORY.COMBAT); assert.equal(model.bookType, 'Master Treatise'); assert.equal(model.protected, true); assert.equal(model.availability, BOOK_STATUS.UNKNOWN); assert.ok(model.requirements.length); assert.ok(model.effects.some((effect) => effect.includes('Maximum Archery'))) })
