import assert from 'node:assert/strict'
import test from 'node:test'
import fs from 'node:fs'
import { createCharacterState } from '../src/game/characterState.js'
import { PROFICIENCY_NAMES } from '../src/data/characterCreation.js'
import { InventoryManager } from '../src/inventory/inventoryManager.js'
import { createItemInstance } from '../src/items/itemInstance.js'
import { ITEM_DATABASE, ITEM_LIST, getItemDefinition } from '../src/items/itemDatabase.js'
import { WardwoodService } from '../src/world/wardwoodService.js'
import { MERCHANT_DEFINITIONS, MERCHANT_LIST, defineMerchant } from '../src/merchants/merchantDefinitions.js'
import { generateMerchantState, refreshMerchantStock } from '../src/merchants/merchantStock.js'
import { MerchantService, merchantAcceptsItem } from '../src/merchants/merchantService.js'
import { calculateTransactionPrice, calculateUnitPrice } from '../src/merchants/merchantPriceCalculator.js'
import { MERCHANT_RESULT, MERCHANT_TYPE, STOCK_MODE, STOCK_REFRESH_SOURCE } from '../src/merchants/merchantConstants.js'
import { ITEM_TYPE } from '../src/items/itemConstants.js'
import { createNewRun } from '../src/game/gameState.js'
import { migrateSave } from '../src/game/saveService.js'

const makeCharacter = () => createCharacterState({ id: 'merchant-hero', name: 'Trader', proficiencies: Object.fromEntries(PROFICIENCY_NAMES.map((name) => [name, ['Archery', 'Camping'].includes(name) ? 'Novice' : 'Untrained'])), startingWeapon: { id: 'test', combatSkills: [] } })
const setup = (merchantId = 'general_merchant') => { const character = makeCharacter(); character.gold = 1000; const inventory = new InventoryManager(character); const wardwood = new WardwoodService(character, inventory); const state = generateMerchantState('merchant-seed', 'run-merchant'); const service = new MerchantService({ character, inventoryManager: inventory, merchantState: state, wardwoodService: wardwood, runId: 'run-merchant', seed: 'merchant-seed', getWorldTime: () => ({ day: 3, hour: 12 }) }); return { character, inventory, wardwood, state, service, stock: state[merchantId] } }

test('MerchantDefinition loads five data-driven merchant types and immutable filters', () => { assert.equal(MERCHANT_LIST.length, 5); assert.deepEqual(new Set(MERCHANT_LIST.map(({ merchantType }) => merchantType)), new Set(Object.values(MERCHANT_TYPE))); assert.ok(Object.isFrozen(MERCHANT_DEFINITIONS.blacksmith.stockDefinition)); assert.equal(MERCHANT_DEFINITIONS.book_merchant.rejectedItemIds.includes('legendary_archery_tome'), true) })
test('Merchant Stock is deterministic for a Run and does not react to day, waiting or opening UI', () => { const first = generateMerchantState('same-seed', 'run-a'); const snapshot = JSON.stringify(first); const afterDay = first; const afterWaitUntilMorning = first; assert.equal(JSON.stringify(afterDay), snapshot); assert.equal(JSON.stringify(afterWaitUntilMorning), snapshot); assert.deepEqual(generateMerchantState('same-seed', 'run-a'), first) })
test('Developer refresh explicitly renews stock and records its source', () => { const state = generateMerchantState('seed', 'run'); const result = refreshMerchantStock(state, 'general_merchant', { seed: 'seed', runId: 'run', source: STOCK_REFRESH_SOURCE.DEVELOPER }); assert.equal(result.ok, true); assert.equal(result.stock.refreshState.count, 1); assert.equal(result.stock.optionalRefreshSource, STOCK_REFRESH_SOURCE.DEVELOPER); assert.equal(result.stock.refreshState.history.length, 2) })
test('buy transfers one Item and Gold between player, stock and merchant', () => { const { character, inventory, service, stock } = setup(); const entry = stock.stockEntries.find(({ itemDefinitionId }) => itemDefinitionId === 'torch'); const beforeQuantity = entry.quantity; const price = calculateUnitPrice(getItemDefinition('torch'), MERCHANT_DEFINITIONS.general_merchant, 'buy'); const reserve = stock.currentGoldReserve; const result = service.buy('general_merchant', 'torch', 1); assert.equal(result.ok, true); assert.equal(entry.quantity, beforeQuantity - 1); assert.equal(character.gold, 1000 - price); assert.equal(stock.currentGoldReserve, reserve + price); assert.equal(inventory.query({ search: 'torch' })[0].instance.quantity, 1) })
test('stack purchase respects selected quantity and available stock', () => { const { character, inventory, service, stock } = setup(); service.addStock('general_merchant', 'bandage', 4); const before = stock.stockEntries.find(({ itemDefinitionId }) => itemDefinitionId === 'bandage').quantity; assert.equal(service.buy('general_merchant', 'bandage', 3).ok, true); assert.equal(inventory.query({ search: 'bandage' })[0].instance.quantity, 3); assert.equal(stock.stockEntries.find(({ itemDefinitionId }) => itemDefinitionId === 'bandage').quantity, before - 3); const gold = character.gold; assert.equal(service.buy('general_merchant', 'bandage', 999).code, MERCHANT_RESULT.STOCK_LIMIT_REACHED); assert.equal(character.gold, gold) })
test('insufficient Gold blocks the full purchase without mutation', () => { const { character, service, stock } = setup(); character.gold = 0; const before = JSON.stringify(stock); assert.equal(service.buy('general_merchant', 'torch').code, MERCHANT_RESULT.INSUFFICIENT_PLAYER_GOLD); assert.equal(JSON.stringify(stock), before); assert.equal(character.inventory.length, 0) })
test('accepted sale changes both Gold balances and adds sold quantity to stock', () => { const { character, inventory, service, stock } = setup(); const meat = createItemInstance('raw_meat', { quantity: 3 }); inventory.add(meat); const playerGold = character.gold; const merchantGold = stock.currentGoldReserve; const result = service.sell('general_merchant', meat.instanceId, 2); assert.equal(result.ok, true); assert.equal(character.gold, playerGold + result.totalPrice); assert.equal(stock.currentGoldReserve, merchantGold - result.totalPrice); assert.equal(inventory.find(meat.instanceId).quantity, 1); assert.ok(stock.stockEntries.some(({ itemDefinitionId, quantity }) => itemDefinitionId === 'raw_meat' && quantity >= 2)) })
test('acceptance is data-driven and rejected tag takes precedence', () => { const merchant = defineMerchant({ id: 'test', displayName: 'Test', description: '', merchantType: MERCHANT_TYPE.GENERAL, locationId: 'x', acceptedItemTypes: [ITEM_TYPE.ACCESSORY], rejectedTags: ['Magic'], stockDefinition: { mode: STOCK_MODE.FIXED, fixed: [] } }); assert.equal(merchantAcceptsItem(merchant, getItemDefinition('plain_ring')).accepted, true); assert.equal(merchantAcceptsItem(merchant, getItemDefinition('warded_ring')).accepted, false); assert.equal(merchantAcceptsItem(MERCHANT_DEFINITIONS.innkeeper, getItemDefinition('rusty_sword')).accepted, false) })
test('Favorite, Protected and Quest Items are never sold', () => { const { inventory, service } = setup(); const favorite = createItemInstance('raw_meat', { favorite: true }); const protectedItem = createItemInstance('archery_master_treatise'); const quest = createItemInstance('sealed_contract'); inventory.add(favorite); inventory.add(protectedItem); inventory.add(quest); assert.equal(service.sell('general_merchant', favorite.instanceId).code, MERCHANT_RESULT.ITEM_FAVORITE); assert.equal(service.sell('book_merchant', protectedItem.instanceId).code, MERCHANT_RESULT.ITEM_PROTECTED); assert.equal(service.sell('general_merchant', quest.instanceId).code, MERCHANT_RESULT.QUEST_ITEM_CANNOT_BE_SOLD); assert.equal(characterInventoryCount(inventory), 3) })
const characterInventoryCount = (inventory) => inventory.character.inventory.length
test('merchant without sufficient reserve does not remove an Item', () => { const { character, inventory, service, state } = setup(); const cup = createItemInstance('silver_cup'); inventory.add(cup); state.general_merchant.currentGoldReserve = 0; const gold = character.gold; assert.equal(service.sell('general_merchant', cup.instanceId).code, MERCHANT_RESULT.INSUFFICIENT_MERCHANT_GOLD); assert.ok(inventory.find(cup.instanceId)); assert.equal(character.gold, gold) })
test('Buy Selected and Sell Selected are atomic', () => { const buy = setup(); buy.character.gold = 1; const stockBefore = JSON.stringify(buy.stock.stockEntries); const selection = buy.stock.stockEntries.slice(0, 2).map(({ itemDefinitionId }) => ({ itemDefinitionId, quantity: 1 })); assert.equal(buy.service.buySelected('general_merchant', selection).ok, false); assert.equal(JSON.stringify(buy.stock.stockEntries), stockBefore); const sell = setup(); const normal = createItemInstance('raw_meat'); const favorite = createItemInstance('wolf_hide', { favorite: true }); sell.inventory.add(normal); sell.inventory.add(favorite); assert.equal(sell.service.sellSelected('general_merchant', [{ instanceId: normal.instanceId, quantity: 1 }, { instanceId: favorite.instanceId, quantity: 1 }]).code, MERCHANT_RESULT.ITEM_FAVORITE); assert.ok(sell.inventory.find(normal.instanceId)); assert.ok(sell.inventory.find(favorite.instanceId)) })
test('Merchant stock ignores Smart Loot and sells currently unusable Manual', () => { const { character, service, state } = setup('book_merchant'); character.proficiencySkills.Archery.baseValue = 30; const manual = state.book_merchant.stockEntries.find(({ itemDefinitionId }) => itemDefinitionId === 'basic_archery_manual'); assert.ok(manual); assert.equal(service.buy('book_merchant', 'basic_archery_manual').ok, true); assert.ok(character.inventory.some(({ definitionId }) => definitionId === 'basic_archery_manual')) })
test('Wardwood stock is bounded and purchased Wardwood creates an expiration batch', () => { for (const id of ['general_merchant', 'hunter_merchant', 'innkeeper']) { for (let index = 0; index < 20; index += 1) { const state = generateMerchantState(`ward-${index}`, `run-${index}`); const quantity = state[id].stockEntries.find(({ itemDefinitionId }) => itemDefinitionId === 'wardwood')?.quantity ?? 0; assert.ok(quantity >= 0 && quantity <= (id === 'general_merchant' ? 3 : 2)) } } const context = setup(); context.service.addStock('general_merchant', 'wardwood', 2); assert.equal(context.service.buy('general_merchant', 'wardwood', 1).ok, true); assert.equal(context.character.wardwood, 1); assert.equal(context.character.wardwoodBatches[0].acquiredDay, 3) })
test('Bow and Crossbow buy normally and no ammunition definitions exist', () => { const context = setup('hunter_merchant'); assert.equal(context.service.buy('hunter_merchant', 'short_bow').ok, true); assert.equal(context.service.buy('hunter_merchant', 'simple_crossbow').ok, true); assert.ok(context.character.inventory.some(({ definitionId }) => definitionId === 'short_bow')); assert.ok(context.character.inventory.some(({ definitionId }) => definitionId === 'simple_crossbow')); assert.equal(ITEM_DATABASE.arrow, undefined); assert.equal(ITEM_DATABASE.bolt, undefined); assert.equal(ITEM_LIST.some(({ displayName }) => /arrow|bolt/i.test(displayName)), false); assert.equal('ammo' in getItemDefinition('simple_crossbow').weaponStats, false) })
test('Price Calculator applies multipliers, stack quantity, rounding and minimum', () => { const merchant = MERCHANT_DEFINITIONS.general_merchant; assert.deepEqual(calculateTransactionPrice({ value: 3 }, merchant, 'sell', 3), { unitPrice: 2, quantity: 3, totalPrice: 6 }); assert.equal(calculateUnitPrice({ value: 0.1 }, merchant, 'sell'), 1); assert.equal(calculateUnitPrice({ value: 0, unsellable: true }, merchant, 'sell'), 0) })
test('MerchantTransactionRecord contains debugging economy fields', () => { const { service } = setup(); const result = service.buy('general_merchant', 'torch'); const record = result.records[0]; assert.equal(record.merchantId, 'general_merchant'); assert.equal(record.transactionType, 'buy'); assert.equal(record.itemDefinitionId, 'torch'); assert.equal(record.worldDay, 3); assert.equal(record.worldTime, 12); assert.equal(record.totalPrice, record.unitPrice * record.quantity) })
test('New Run creates fresh Merchant State and migration supplies safe state to older saves', () => { const creation = { name: 'Merchant Hero', attributes: { strength: 2, defense: 2, vitality: 2, agility: 2, magicPower: 2, wisdom: 2, perception: 2, luck: 2 }, proficiencies: Object.fromEntries(PROFICIENCY_NAMES.map((name) => [name, ['Archery', 'Camping'].includes(name) ? 'Novice' : 'Untrained'])), startingWeapon: { id: 'test', combatSkills: [] }, startingSkills: [] }; const first = createNewRun(creation, { seed: 'merchant-run-1', runId: 'merchant-run-1', now: () => '2026-01-01' }); first.merchantState.general_merchant.transactions.push({ test: true }); const second = createNewRun(creation, { seed: 'merchant-run-2', runId: 'merchant-run-2', now: () => '2026-01-01' }); assert.equal(second.merchantState.general_merchant.transactions.length, 0); const legacy = { ...second }; delete legacy.merchantState; assert.ok(migrateSave(legacy).merchantState.general_merchant) })
test('controlled errors never throw for invalid commands', () => { const { service } = setup(); assert.doesNotThrow(() => service.buy('missing', 'torch')); assert.equal(service.buy('missing', 'torch').code, MERCHANT_RESULT.MERCHANT_NOT_FOUND); assert.equal(service.buy('general_merchant', 'missing').code, MERCHANT_RESULT.ITEM_NOT_IN_STOCK); assert.equal(service.buy('general_merchant', 'torch', 0).code, MERCHANT_RESULT.INVALID_QUANTITY) })
test('Merchant UI delegates prices and transactions to services', () => { const source = fs.readFileSync(new URL('../src/views/MenuThree.vue', import.meta.url), 'utf8'); for (const label of ['Merchant Stock', 'Player Inventory', 'Merchant Gold', 'Buy Selected', 'Sell Selected', 'Transaction', 'Refresh Merchant Stock']) assert.match(source, new RegExp(label)); assert.match(source, /Open \{\{ merchant\.merchantType \}\}/); assert.match(source, /calculateTransactionPrice/); assert.match(source, /merchantService\.buySelected/); assert.doesNotMatch(source, /Arrow|Bolt|Ammo|Quiver/) })
