import test from 'node:test'
import assert from 'node:assert/strict'
import { createCharacterState } from '../src/game/characterState.js'
import { PROFICIENCY_NAMES } from '../src/data/characterCreation.js'
import { calculateCharacterStats } from '../src/character/characterStatCalculator.js'
import { InventoryManager } from '../src/inventory/inventoryManager.js'
import { createItemInstance } from '../src/items/itemInstance.js'
import { WardwoodService } from '../src/world/wardwoodService.js'
import { PoiRepository } from '../src/poi/poiRepository.js'
import { PoiService } from '../src/poi/poiService.js'
import { poiDatabase } from '../src/poi/poiDatabase.js'
import { PoiDiscoveryService } from '../src/poi/poiDiscoveryService.js'
import { PoiActionService } from '../src/poi/poiActionService.js'
import { PoiActionAvailabilityResolver } from '../src/poi/poiActionAvailabilityResolver.js'
import { PoiCheckService } from '../src/poi/poiCheckService.js'
import { definePoiAction, definePoiCheck, definePoiDiscovery } from '../src/poi/poiModels.js'
import { POI_ACTION_STATUS, POI_ACTION_VISIBILITY, POI_CHECK_STRATEGY, POI_CHECK_TYPE, POI_COMPARISON, POI_DISCOVERY_MODE, POI_VALUE_SOURCE } from '../src/poi/poiConstants.js'

const hero = () => createCharacterState({ id: 'poi-hero', name: 'Explorer', attributes: { strength: 3, defense: 1, vitality: 1, agility: 1, magicPower: 1, wisdom: 3, perception: 3, luck: 3 }, proficiencies: Object.fromEntries(PROFICIENCY_NAMES.map((name) => [name, ['Camping', 'Scouting'].includes(name) ? 'Novice' : 'Untrained'])), startingWeapon: { id: 'test', combatSkills: [] } })
function setup(random = () => 0.5) { const character = hero(); const inventoryManager = new InventoryManager(character); const wardwoodService = new WardwoodService(character, inventoryManager); const repository = new PoiRepository(); const poiService = new PoiService({ database: poiDatabase, repository }); for (const [index, id] of ['abandoned_cart', 'old_shrine', 'hunter_cache', 'collapsed_mine', 'abandoned_shelter'].entries()) poiService.create(id, { runId: 'run', seed: 'seed', worldPosition: { row: 5 + index, column: 5 } }); const instance = (id) => repository.getAll().find((entry) => entry.poiDefinitionId === id); const context = { character, characterId: character.id, characterStats: calculateCharacterStats(character), proficiencyState: character.proficiencySkills, inventoryManager, wardwoodService, knownKnowledgeIds: character.discoveredKnowledge, worldPosition: { row: 5, column: 5 }, regionId: 'meadows', worldDay: 1, worldTime: 6, controlledRandomSource: random, advanceWorldTime: () => ({ ok: true }) }; return { character, inventoryManager, wardwoodService, repository, poiService, discovery: new PoiDiscoveryService({ poiService }), actions: new PoiActionService({ poiService }), instance, context } }

test('Visible, Proximity and Perception discovery use services and persist sources', () => { const s = setup(() => 0.9); const cart = s.instance('abandoned_cart'); assert.equal(s.discovery.evaluate(cart.instanceId, s.context).ok, true); assert.equal(cart.discoverySourceType, 'Visible'); const shrine = s.instance('old_shrine'); assert.equal(s.discovery.evaluate(shrine.instanceId, { ...s.context, worldPosition: { row: 100, column: 100 } }).code, 'POI_OUT_OF_RANGE'); assert.equal(s.discovery.evaluate(shrine.instanceId, s.context).ok, true); const cache = s.instance('hunter_cache'); assert.equal(s.discovery.evaluate(cache.instanceId, s.context).ok, true); assert.equal(cache.discoverySourceType, 'Perception') })
test('failed perception remains hidden and records the attempt', () => { const s = setup(() => 0); const cache = s.instance('hunter_cache'); s.context.characterStats.finalStats.perception = 0; assert.equal(s.discovery.evaluate(cache.instanceId, s.context).code, 'PERCEPTION_DISCOVERY_FAILED'); assert.equal(cache.isDiscovered, false); assert.equal(cache.discoveryAttempts, 1) })
test('Knowledge, Map and Other POI discovery are explicit and data-driven', () => { const s = setup(); const shrine = s.instance('old_shrine'); const knowledge = new PoiDiscoveryService({ poiService: s.poiService, discoveryDefinitions: { standard: definePoiDiscovery({ id: 'standard', discoveryMode: POI_DISCOVERY_MODE.KNOWLEDGE, discoveryRadius: 5, requiredKnowledgeIds: ['lore'] }) } }); assert.equal(knowledge.evaluate(shrine.instanceId, { ...s.context, knownKnowledgeIds: ['lore'] }).ok, true); const cache = s.instance('hunter_cache'); assert.equal(s.discovery.revealByMap({ poiInstanceId: cache.instanceId }, s.context).results[0].instance.discoverySourceType, 'MapScroll'); const mine = s.instance('collapsed_mine'); assert.equal(s.discovery.revealByOtherPoi({ poiInstanceId: mine.instanceId }, shrine.instanceId, s.context).results[0].instance.discoverySourceId, shrine.instanceId) })
test('map status hides undiscovered POI', () => { const s = setup(); assert.equal(s.poiService.getMapStatus(s.instance('old_shrine').instanceId), 'Undiscovered') })
test('action comes only from current state and preview never increments counters', () => { const s = setup(); const cart = s.instance('abandoned_cart'); s.poiService.discover(cart.instanceId); assert.equal(s.actions.preview(cart.instanceId, 'cart_search', s.context).ok, true); assert.equal(cart.interactionCounters.cart_search, undefined); assert.equal(s.actions.preview(cart.instanceId, 'shrine_pray', s.context).code, 'ACTION_NOT_IN_CURRENT_STATE') })
test('ShowLocked is visible, locked and hides internal requirement data', () => { const s = setup(); const shrine = s.instance('old_shrine'); const preview = s.actions.preview(shrine.instanceId, 'shrine_study', s.context); assert.equal(preview.visible, true); assert.equal(preview.available, false); assert.equal(preview.status, POI_ACTION_STATUS.VISIBLE_LOCKED); assert.equal(preview.hiddenRequirementCount, 1); assert.equal(JSON.stringify(preview.visibleRequirements).includes('old_kingdom'), false) })
test('HideWhenUnavailable action is hidden and usage limit becomes exhausted', () => { const s = setup(); const resolver = new PoiActionAvailabilityResolver(); const hidden = definePoiAction({ id: 'secret', visibilityMode: POI_ACTION_VISIBILITY.HIDE_WHEN_UNAVAILABLE, visibilityRequirements: [{ type: 'poi_flag', flag: 'secret' }] }); assert.equal(resolver.resolve(hidden, s.instance('old_shrine'), s.context).visible, false); const cache = s.instance('hunter_cache'); cache.interactionCounters.cache_open = 1; assert.equal(s.actions.preview(cache.instanceId, 'cache_open', s.context).status, POI_ACTION_STATUS.EXHAUSTED) })
test('cost preview is non-mutating and missing one cost blocks execution atomically', () => { const s = setup(); const cart = s.instance('abandoned_cart'); const before = JSON.stringify(s.character); const preview = s.actions.preview(cart.instanceId, 'cart_search', s.context); assert.equal(preview.costPreview.canPayAllCosts, true); assert.equal(JSON.stringify(s.character), before); const custom = definePoiAction({ id: 'mixed', costs: [{ type: 'Gold', quantity: 10 }, { type: 'Item', itemDefinitionId: 'torch', quantity: 1 }] }); const service = new PoiActionService({ poiService: s.poiService, actions: { mixed: custom } }); poiDatabase.get('abandoned_cart').stateDefinitions[0]?.availableActionIds; const cost = service.costs.pay(custom.costs, s.context); assert.equal(cost.ok, false); assert.equal(s.character.gold, 0) })
test('Item, Gold, Wardwood and World Time costs are detected and paid', () => { const s = setup(); s.character.gold = 20; s.inventoryManager.add(createItemInstance('torch')); s.wardwoodService.addBatch(2, 1); let minutes = 0; const costs = [{ type: 'Item', itemDefinitionId: 'torch', quantity: 1 }, { type: 'Gold', quantity: 10 }, { type: 'Wardwood', quantity: 1 }, { type: 'WorldTime', quantity: 30 }]; const context = { ...s.context, advanceWorldTime: (value) => { minutes += value; return { ok: true } } }; const preview = s.actions.costs.preview(costs, context); assert.equal(preview.canPayAllCosts, true); assert.equal(s.actions.costs.pay(costs, context).ok, true); assert.equal(s.character.gold, 10); assert.equal(s.character.wardwood, 1); assert.equal(minutes, 30) })
test('threshold, Base and Effective proficiency checks resolve central calculated values', () => { const s = setup(); const checks = new PoiCheckService(); const threshold = definePoiCheck({ id: 'strength', checkType: POI_CHECK_TYPE.STAT, statId: 'strength', difficulty: 3 }); assert.equal(checks.execute(threshold, s.context).success, true); const base = definePoiCheck({ id: 'base', checkType: POI_CHECK_TYPE.PROFICIENCY, proficiencyId: 'Scouting', valueSource: POI_VALUE_SOURCE.BASE, difficulty: 10 }); const effective = definePoiCheck({ id: 'effective', checkType: POI_CHECK_TYPE.PROFICIENCY, proficiencyId: 'Scouting', valueSource: POI_VALUE_SOURCE.EFFECTIVE, difficulty: 10 }); assert.equal(checks.execute(base, s.context).resolvedValue, 10); assert.equal(checks.execute(effective, s.context).resolvedValue, s.context.characterStats.proficiencyValues.Scouting.effectiveValue) })
test('controlled RNG selects success, failure and critical fallbacks', () => { const check = definePoiCheck({ id: 'random', checkType: POI_CHECK_TYPE.STAT, statId: 'perception', difficulty: 8, comparisonMode: POI_COMPARISON.VALUE_PLUS_ROLL, randomRange: { minimum: 1, maximum: 10 }, criticalSuccessThreshold: 13, criticalFailureThreshold: 4 }); const low = setup(() => 0); const high = setup(() => 0.999); assert.equal(new PoiCheckService().execute(check, low.context).resultType, 'CriticalFailure'); assert.equal(new PoiCheckService().execute(check, high.context).resultType, 'CriticalSuccess') })
test('execution increments counter, visits POI and stores pending outcome; combat blocks it', () => { const s = setup(() => 0.9); const cart = s.instance('abandoned_cart'); const result = s.actions.execute(cart.instanceId, 'cart_search', s.context); assert.equal(result.ok, true); assert.equal(result.outcomeId, 'abandoned_cart_search_success'); assert.equal(cart.interactionCounters.cart_search, 1); assert.equal(cart.pendingOutcomeId, result.outcomeId); assert.equal(cart.isVisited, true); assert.equal(s.actions.execute(cart.instanceId, 'cart_tracks', { ...s.context, isInCombat: true }).code, 'POI_INTERACTION_BLOCKED_DURING_COMBAT') })
test('AllMustPass and FirstResult strategies are supported', () => { const checks = new PoiCheckService(); const s = setup(); const pass = definePoiCheck({ id: 'pass', checkType: POI_CHECK_TYPE.STAT, statId: 'strength', difficulty: 1 }); const fail = definePoiCheck({ id: 'fail', checkType: POI_CHECK_TYPE.STAT, statId: 'strength', difficulty: 99 }); assert.equal(checks.executeMany([pass, fail], POI_CHECK_STRATEGY.ALL_MUST_PASS, s.context).success, false); assert.equal(checks.executeMany([pass, fail], POI_CHECK_STRATEGY.FIRST_RESULT, s.context).success, true) })
