import test from 'node:test'
import assert from 'node:assert/strict'
import { POI_DEFINITIONS } from '../src/poi/poiDefinitions.js'
import { PoiDatabase } from '../src/poi/poiDatabase.js'
import { createPoiInstance, definePoiAction, definePoiOutcome } from '../src/poi/poiModels.js'
import { createEmptyPoiState, isValidPoiState, PoiRepository } from '../src/poi/poiRepository.js'
import { PoiService } from '../src/poi/poiService.js'
import { POI_MAP_STATUS } from '../src/poi/poiConstants.js'
import { migrateSave } from '../src/game/saveService.js'

const setup = () => { const database = new PoiDatabase(); const repository = new PoiRepository(); const service = new PoiService({ database, repository }); const created = service.create('abandoned_cart', { runId: 'run-a', seed: 'seed-a', worldPosition: { row: 4, column: 7 } }); return { database, repository, service, instance: created.instance } }

test('PoiDefinition and placeholder models load immutable data', () => { const definition = POI_DEFINITIONS[0]; assert.equal(definition.id, 'abandoned_cart'); assert.equal(definition.stateDefinitions[0].id, definition.initialStateId); assert.equal(Object.isFrozen(definition), true); assert.equal(definePoiAction().id, null); assert.equal(definePoiOutcome().id, null) })
test('PoiInstance contains only run state and starts reset', () => { const definition = POI_DEFINITIONS[0]; const value = createPoiInstance(definition, { runId: 'r', seed: 's', worldPosition: { row: 2, column: 3 } }); assert.equal(value.poiDefinitionId, definition.id); assert.deepEqual(value.worldPosition, { row: 2, column: 3 }); assert.equal(value.isDiscovered, false); assert.deepEqual(value.localFlags, {}); assert.deepEqual(value.claimedRewardIds, []); assert.equal('stateDefinitions' in value, false) })
test('PoiDatabase queries and validates definitions and state IDs', () => { const database = new PoiDatabase(); assert.equal(database.get('old_shrine').displayName, 'Old Shrine'); assert.equal(database.getByRegion('meadows').length, 5); assert.equal(database.getByLocation('meadows-forest').length, 2); assert.equal(database.getByType('Shrine').length, 1); assert.equal(database.getByTag('hidden').length, 1); assert.equal(database.validate().valid, true) })
test('PoiRepository saves, queries and deletes instances', () => { const { repository, instance } = setup(); assert.equal(repository.get(instance.instanceId).seed, 'seed-a'); assert.equal(repository.getByRegion('meadows').length, 1); assert.equal(repository.getByLocation('meadows-wilds').length, 1); assert.equal(repository.delete(instance.instanceId), true); assert.equal(repository.getAll().length, 0) })
test('PoiService creates and changes valid states', () => { const { service, instance } = setup(); assert.equal(service.changeState(instance.instanceId, 'searched').ok, true); assert.equal(service.getInstance(instance.instanceId).currentStateId, 'searched'); assert.equal(service.changeState(instance.instanceId, 'missing').code, 'POI_STATE_NOT_FOUND') })
test('discovery, visit, completion, exhaustion and map status persist', () => { const { service, instance } = setup(); service.discover(instance.instanceId); assert.equal(service.getMapStatus(instance.instanceId), POI_MAP_STATUS.DISCOVERED); service.visit(instance.instanceId, { day: 2, hour: 9 }); assert.equal(service.getMapStatus(instance.instanceId), POI_MAP_STATUS.VISITED); service.complete(instance.instanceId); assert.equal(service.getMapStatus(instance.instanceId), POI_MAP_STATUS.COMPLETED); service.exhaust(instance.instanceId); assert.equal(service.getMapStatus(instance.instanceId), POI_MAP_STATUS.EXHAUSTED); assert.equal(service.getInstance(instance.instanceId).lastInteractionWorldDay, null) })
test('flags, counters and claimed rewards persist without hard-coded names', () => { const { service, instance } = setup(); service.setFlag(instance.instanceId, 'openedDoor'); service.incrementCounter(instance.instanceId, 'inspectAction', 3); service.claimReward(instance.instanceId, 'reward-a'); service.claimReward(instance.instanceId, 'reward-a'); const saved = service.repository.serialize(); assert.equal(saved.instances[0].localFlags.openedDoor, true); assert.equal(saved.instances[0].interactionCounters.inspectAction, 3); assert.deepEqual(saved.instances[0].claimedRewardIds, ['reward-a']); assert.equal(isValidPoiState(saved), true) })
test('reset restores the complete new-run state', () => { const { service, instance } = setup(); service.exhaust(instance.instanceId); service.setFlag(instance.instanceId, 'searched'); service.incrementCounter(instance.instanceId, 'searchAction'); service.claimReward(instance.instanceId, 'loot'); service.reset(instance.instanceId); const reset = service.getInstance(instance.instanceId); assert.equal(reset.currentStateId, 'untouched'); assert.equal(reset.isDiscovered, false); assert.deepEqual(reset.localFlags, {}); assert.deepEqual(reset.interactionCounters, {}); assert.deepEqual(reset.claimedRewardIds, []) })
test('serialized PoiState restores all fields without sharing mutable data', () => { const { repository, service, instance } = setup(); service.setFlag(instance.instanceId, 'prayed'); service.incrementCounter(instance.instanceId, 'inspectAction'); const restored = new PoiRepository(JSON.parse(JSON.stringify(repository.serialize()))); restored.get(instance.instanceId).localFlags.prayed = false; assert.equal(repository.get(instance.instanceId).localFlags.prayed, true); assert.equal(restored.get(instance.instanceId).interactionCounters.inspectAction, 1) })
test('legacy save migration receives an empty valid PoiState', () => { const migrated = migrateSave({ saveVersion: 7 }); assert.deepEqual(migrated.poiState, createEmptyPoiState()); assert.equal(isValidPoiState(migrated.poiState), true) })
