import test from 'node:test'
import assert from 'node:assert/strict'
import { createCharacterState } from '../src/game/characterState.js'
import { PROFICIENCY_NAMES } from '../src/data/characterCreation.js'
import { InventoryManager } from '../src/inventory/inventoryManager.js'
import { PoiRepository } from '../src/poi/poiRepository.js'
import { PoiService } from '../src/poi/poiService.js'
import { poiDatabase } from '../src/poi/poiDatabase.js'
import { PoiDiscoveryService } from '../src/poi/poiDiscoveryService.js'
import { PoiOutcomeService } from '../src/poi/poiOutcomeService.js'
import { definePoiOutcome } from '../src/poi/poiModels.js'
import { REWARD_TYPE } from '../src/rewards/rewardDefinitions.js'

const hero = () => createCharacterState({ id: 'outcome-hero', name: 'Explorer', proficiencies: Object.fromEntries(PROFICIENCY_NAMES.map((name) => [name, ['Camping', 'Scouting'].includes(name) ? 'Novice' : 'Untrained'])), startingWeapon: { id: 'test', combatSkills: [] } })
function setup(options = {}) { const character = hero(); const inventoryManager = new InventoryManager(character); const repository = new PoiRepository(); const poiService = new PoiService({ database: poiDatabase, repository }); for (const [index, id] of ['abandoned_cart', 'old_shrine', 'hunter_cache', 'collapsed_mine', 'abandoned_shelter'].entries()) poiService.create(id, { runId: 'run', seed: 'seed', worldPosition: { row: index, column: 0 } }); const instance = (id) => repository.getAll().find((entry) => entry.poiDefinitionId === id); const discoveryService = new PoiDiscoveryService({ poiService }); const worldFlags = {}; const regionFlags = {}; const context = { character, inventoryManager, worldFlags, regionFlags, worldDay: 2, worldTime: 9, controlledRandomSource: options.random ?? (() => 0), advanceWorldTime: () => ({ ok: true }) }; const outcomes = new PoiOutcomeService({ poiService, discoveryService, startCombat: options.startCombat }); return { character, inventoryManager, repository, poiService, discoveryService, outcomes, instance, context } }
const pending = (instance, outcomeId) => { instance.pendingOutcomeId = outcomeId; return instance }

test('pending outcome executes while a nonpending outcome is blocked', () => { const s = setup(); const cart = s.instance('abandoned_cart'); assert.equal(s.outcomes.execute(cart.instanceId, 'abandoned_cart_search_failure', s.context).code, 'OUTCOME_NOT_PENDING'); pending(cart, 'abandoned_cart_search_failure'); assert.equal(s.outcomes.execute(cart.instanceId, cart.pendingOutcomeId, s.context).code, 'OUTCOME_FINALIZED') })
test('finalized outcome is idempotent', () => { const s = setup(); const cart = pending(s.instance('abandoned_cart'), 'abandoned_cart_search_failure'); s.outcomes.execute(cart.instanceId, cart.pendingOutcomeId, s.context); cart.pendingOutcomeId = 'abandoned_cart_search_failure'; assert.equal(s.outcomes.execute(cart.instanceId, cart.pendingOutcomeId, s.context).code, 'OUTCOME_ALREADY_RESOLVED') })
test('damage, healing and statuses use effect executor adapters', () => { const s = setup(); const shrine = s.instance('old_shrine'); const custom = { damage: definePoiOutcome({ id: 'damage', effects: [{ type: 'DamageCharacter', damageAmount: 5 }] }), heal: definePoiOutcome({ id: 'heal', effects: [{ type: 'HealCharacter', healAmount: 3 }] }), status: definePoiOutcome({ id: 'status', effects: [{ type: 'ApplyStatusEffect', statusId: 'Blessed' }, { type: 'RemoveStatusEffect', statusId: 'Blessed' }] }) }; const service = new PoiOutcomeService({ poiService: s.poiService, discoveryService: s.discoveryService, outcomes: custom }); pending(shrine, 'damage'); service.execute(shrine.instanceId, 'damage', s.context); assert.equal(s.character.health.current, 13); pending(shrine, 'heal'); service.execute(shrine.instanceId, 'heal', s.context); assert.equal(s.character.health.current, 16); pending(shrine, 'status'); service.execute(shrine.instanceId, 'status', s.context); assert.deepEqual(s.character.statuses, []) })
test('local, world and region flags plus reveal effect are applied', () => { const s = setup(); const cart = s.instance('abandoned_cart'); const mine = s.instance('collapsed_mine'); pending(cart, 'abandoned_cart_tracks_success'); const result = s.outcomes.execute(cart.instanceId, cart.pendingOutcomeId, s.context); assert.equal(result.ok, true); assert.equal(cart.localFlags.tracksInspected, true); assert.equal(mine.isDiscovered, true); assert.equal(mine.discoverySourceType, 'OtherPoi'); assert.equal(s.character.discoveredKnowledge.includes('local_threat'), true) })
test('fixed item rewards create Loot Reward and ignore Smart Loot', () => { const s = setup(); const cache = pending(s.instance('hunter_cache'), 'hunter_cache_open'); const result = s.outcomes.execute(cache.instanceId, cache.pendingOutcomeId, s.context); assert.equal(result.code, 'LOOT_REWARD_PENDING'); assert.ok(result.lootReward.entries.some(({ payload }) => payload?.definitionId === 'advanced_archery_manual')); assert.equal(s.character.inventory.length, 0) })
test('Take All resolves loot, claims stable bundle and finalizes transition', () => { const s = setup(); const cache = pending(s.instance('hunter_cache'), 'hunter_cache_open'); s.outcomes.execute(cache.instanceId, cache.pendingOutcomeId, s.context); const result = s.outcomes.resolveLoot(cache.instanceId, 'all', [], s.context); assert.equal(result.code, 'OUTCOME_FINALIZED'); assert.ok(s.character.inventory.some(({ definitionId }) => definitionId === 'advanced_archery_manual')); assert.equal(cache.currentStateId, 'exhausted'); assert.equal(cache.isCompleted, true); assert.equal(cache.isExhausted, true); assert.equal(cache.claimedRewardIds.filter((id) => id.endsWith(':loot')).length, 1) })
test('Take Selected and Leave resolve a bundle once', () => { const selected = setup(); const first = pending(selected.instance('hunter_cache'), 'hunter_cache_open'); selected.outcomes.execute(first.instanceId, first.pendingOutcomeId, selected.context); assert.equal(selected.outcomes.resolveLoot(first.instanceId, 'selected', [0], selected.context).ok, true); assert.equal(selected.character.inventory.length, 1); const left = setup(); const second = pending(left.instance('hunter_cache'), 'hunter_cache_open'); left.outcomes.execute(second.instanceId, second.pendingOutcomeId, left.context); assert.equal(left.outcomes.resolveLoot(second.instanceId, 'leave', [], left.context).ok, true); assert.equal(left.character.inventory.length, 0); assert.equal(left.outcomes.resolveLoot(second.instanceId, 'all', [], left.context).code, 'OUTCOME_NOT_PENDING') })
test('direct Gold, Knowledge and Recipe rewards use RewardService', () => { const s = setup(); const shrine = s.instance('old_shrine'); const direct = definePoiOutcome({ id: 'direct', rewards: [{ rewardId: 'gold', type: REWARD_TYPE.GRANT_GOLD, amount: 10 }, { rewardId: 'knowledge', type: REWARD_TYPE.GRANT_KNOWLEDGE, knowledgeId: 'local_threat' }, { rewardId: 'recipe', type: REWARD_TYPE.GRANT_RECIPE, recipeId: 'simple_soup' }] }); const service = new PoiOutcomeService({ poiService: s.poiService, discoveryService: s.discoveryService, outcomes: { direct } }); pending(shrine, 'direct'); assert.equal(service.execute(shrine.instanceId, 'direct', s.context).ok, true); assert.equal(s.character.gold, 10); assert.equal(s.character.discoveredKnowledge.includes('local_threat'), true); assert.equal(s.character.recipeState.knownRecipeIds.includes('simple_soup'), true) })
test('random reward defaults to no Smart Loot and supports empty result', () => { const s = setup({ random: () => 0.999 }); const cart = pending(s.instance('abandoned_cart'), 'abandoned_cart_search_success'); const result = s.outcomes.execute(cart.instanceId, cart.pendingOutcomeId, s.context); assert.equal(result.ok, true); assert.equal(result.code, 'OUTCOME_FINALIZED') })
test('combat starts once, persists association and validates combat ID', () => { const combatOutcome = definePoiOutcome({ id: 'combat', startCombatEncounterId: 'grey_wolf', combatResolutionDefinition: { victory: { setLocalFlags: ['guardianDefeated'], nextStateId: 'searched' } } }); const s = setup({ startCombat: () => ({ ok: true, combatId: 'combat-1' }) }); const service = new PoiOutcomeService({ poiService: s.poiService, discoveryService: s.discoveryService, outcomes: { combat: combatOutcome }, startCombat: () => ({ ok: true, combatId: 'combat-1' }) }); const mine = pending(s.instance('collapsed_mine'), 'combat'); assert.equal(service.execute(mine.instanceId, 'combat', s.context).code, 'COMBAT_TRIGGERED'); assert.equal(mine.pendingCombatId, 'combat-1'); assert.equal(service.execute(mine.instanceId, 'combat', s.context).code, 'OUTCOME_EXECUTION_STARTED'); assert.equal(service.resolveCombat(mine.instanceId, 'wrong', 'Victory', s.context).code, 'COMBAT_ID_MISMATCH'); assert.equal(service.resolveCombat(mine.instanceId, 'combat-1', 'Victory', s.context).code, 'OUTCOME_FINALIZED'); assert.equal(mine.localFlags.guardianDefeated, true); assert.equal(mine.currentStateId, 'searched') })
test('defeat and escape do not grant victory changes', () => { for (const result of ['Defeat', 'Escaped']) { const s = setup(); const definition = definePoiOutcome({ id: 'combat', startCombatEncounterId: 'grey_wolf', combatResolutionDefinition: { victory: { setLocalFlags: ['victory'] } } }); const service = new PoiOutcomeService({ poiService: s.poiService, discoveryService: s.discoveryService, outcomes: { combat: definition }, startCombat: () => ({ ok: true, combatId: 'c' }) }); const mine = pending(s.instance('collapsed_mine'), 'combat'); service.execute(mine.instanceId, 'combat', s.context); service.resolveCombat(mine.instanceId, 'c', result, s.context); assert.equal(mine.localFlags.victory, undefined) } })
test('secured shelter becomes completed safe zone but not exhausted', () => { const s = setup(); const shelter = pending(s.instance('abandoned_shelter'), 'shelter_secure'); const result = s.outcomes.execute(shelter.instanceId, shelter.pendingOutcomeId, s.context); assert.equal(result.code, 'OUTCOME_FINALIZED'); assert.equal(shelter.localFlags.safeZoneEnabled, true); assert.equal(shelter.localFlags.allowWaitUntilMorning, true); assert.equal(shelter.localFlags.campfireCompatible, true); assert.equal(shelter.isCompleted, true); assert.equal(shelter.isExhausted, false) })
test('pending loot and combat process survives repository serialization', () => { const s = setup(); const cache = pending(s.instance('hunter_cache'), 'hunter_cache_open'); s.outcomes.execute(cache.instanceId, cache.pendingOutcomeId, s.context); const restored = new PoiRepository(JSON.parse(JSON.stringify(s.repository.serialize()))).get(cache.instanceId); assert.equal(restored.pendingResolution.phase, 'AwaitingLootResolution'); assert.equal(restored.pendingLootRewardId, cache.pendingLootRewardId); assert.equal(restored.pendingResolution.generatedRewardBundle.entries.length, 3) })
