import assert from 'node:assert/strict'
import test from 'node:test'
import { createCharacterState, cloneCharacterState, restoreCharacterState } from '../src/game/characterState.js'
import { PROFICIENCY_NAMES } from '../src/data/characterCreation.js'
import { getSkillProgressionDefinition, SKILL_PROGRESSION_DEFINITIONS } from '../src/skills/skillProgressionDefinitions.js'
import { attemptPracticeGain, calculateProficiency } from '../src/skills/proficiencySystem.js'
import { PracticeGainService } from '../src/skills/practiceGainService.js'
import { InventoryManager } from '../src/inventory/inventoryManager.js'
import { createItemInstance } from '../src/items/itemInstance.js'
import { createLootReward, takeLootReward } from '../src/inventory/lootReward.js'
import { BookService } from '../src/books/bookService.js'
import { getBookCollectionSummary } from '../src/books/bookCollectionService.js'
import { defineLootDefinition, LOOT_SOURCE_TYPE } from '../src/loot/lootDefinition.js'
import { generateLoot } from '../src/loot/lootGenerator.js'
import { getItemDefinition } from '../src/items/itemDatabase.js'
import { EquipmentManager } from '../src/equipment/equipmentManager.js'
import { CombatManager } from '../src/combat/combatManager.js'
import { DiceService } from '../src/combat/diceService.js'
import { COMBAT_INITIATOR } from '../src/combat/combatConstants.js'

const hero = () => createCharacterState({ id: 'practice-hero', name: 'Hero', proficiencies: Object.fromEntries(PROFICIENCY_NAMES.map((name) => [name, ['Archery', 'Camping'].includes(name) ? 'Novice' : 'Untrained'])), startingWeapon: { id: 'test', combatSkills: [] } })

test('SkillProgressionDefinition stores all data-driven chances and +0.01 gain', () => { assert.equal(SKILL_PROGRESSION_DEFINITIONS.length, 8); assert.equal(getSkillProgressionDefinition(5).chance, 0.20); assert.equal(getSkillProgressionDefinition(24.35).chance, 0.07); assert.equal(getSkillProgressionDefinition(115).chance, 0.002); assert.ok(SKILL_PROGRESSION_DEFINITIONS.every(({ skillGain }) => skillGain === 0.01)) })
test('Practice Gain adds only 0.01 Base Skill and ignores equipment Bonus', () => { const character = hero(); character.proficiencySkills.Archery.baseValue = 24.35; const before = calculateProficiency(character, 'Archery', { equipmentEffects: [{ type: 'modify_proficiency', proficiency: 'Archery', amount: 50 }] }); assert.equal(before.effectiveValue, 74.35); const gain = attemptPracticeGain(character, 'Archery', { successful: true, random: () => 0 }); assert.equal(gain.ok, true); assert.equal(character.proficiencySkills.Archery.baseValue, 24.36); assert.equal(gain.chance, 0.07) })
test('Practice Gain rejects failed actions and performs at most one roll per action id', () => { const character = hero(); const service = new PracticeGainService({ random: () => 0 }); assert.equal(service.processSuccessfulAction(character, 'Archery', { actionId: 'hit-1', successful: false }).code, 'ACTION_NOT_SUCCESSFUL'); assert.equal(service.processSuccessfulAction(character, 'Archery', { actionId: 'hit-1', successful: true }).code, 'PRACTICE_ALREADY_ROLLED_FOR_ACTION'); assert.equal(service.processSuccessfulAction(character, 'Archery', { actionId: 'hit-2', successful: true }).ok, true) })
test('a successful weapon hit invokes one Practice Gain action for its Proficiency', () => { const character = hero(); const equipment = new EquipmentManager(character); assert.equal(equipment.equip(createItemInstance('club'), 'mainHand').ok, true); const calls = []; const manager = new CombatManager({ diceService: new DiceService(() => 0.999999), practiceGainService: { processSuccessfulAction: (...args) => { calls.push(args); return { ok: true } } } }); manager.startCombat({ character, initiator: COMBAT_INITIATOR.PLAYER }); manager.selectInitiativeAttribute('strength'); manager.selectPlayerSkill('player_strike'); manager.resolveEnemySelection(); manager.resolveInitiative(); manager.resolveActions(); assert.equal(calls.length, 1); assert.equal(calls[0][1], 'Mace Fighting'); assert.equal(calls[0][2].successful, true) })
test('Practice Gain respects Current Rank Cap, Maximum Cap and anti-grind hook architecture', () => { const character = hero(); character.proficiencySkills.Archery.baseValue = 39; assert.equal(attemptPracticeGain(character, 'Archery', { successful: true, random: () => 0 }).code, 'CURRENT_RANK_CAP_REACHED'); character.proficiencySkills.Archery = { baseValue: 25, currentRank: 'Novice', currentRankCap: 39, maximumCap: 30 }; const blocked = attemptPracticeGain(character, 'Archery', { successful: true, random: () => 0, antiGrindHooks: { diminishingReturns: () => 0 } }); assert.equal(blocked.code, 'PRACTICE_GAIN_NOT_ROLLED'); assert.equal(blocked.chance, 0) })
test('Smart Loot removes unusable Manuals only from explicitly random loot', () => { const character = hero(); character.proficiencySkills.Archery.baseValue = 25; const definition = defineLootDefinition({ id: 'manual_random', sourceType: LOOT_SOURCE_TYPE.ENEMY, bundles: [{ id: 'written', chance: 100, choices: [{ type: 'item', itemId: 'basic_archery_manual', weight: 10 }, { type: 'item', itemId: 'raw_meat', weight: 1 }] }] }); const smart = generateLoot(definition, { random: () => 0, smartLootCharacter: character, isRandomLoot: true }); assert.equal(smart.entries[0].payload.definitionId, 'raw_meat'); const handPlaced = generateLoot(definition, { random: () => 0, smartLootCharacter: character, isRandomLoot: false }); assert.equal(handPlaced.entries[0].payload.definitionId, 'basic_archery_manual') })
test('Loot records unique Books Found and Knowledge Book journal metadata', () => { const character = hero(); const inventory = new InventoryManager(character); const book = createItemInstance('history_of_the_old_kingdom', { acquiredAt: '2026-07-17T10:00:00Z' }); const reward = createLootReward({ source: { type: 'enemy', id: 'wolf' }, itemInstances: [book] }); takeLootReward(reward, character, inventory); const summary = getBookCollectionSummary(character); assert.equal(summary.found, 1); assert.equal(summary.total, 180); assert.deepEqual(summary.journal[0], { bookId: 'history_of_the_old_kingdom', title: 'History of the Old Kingdom', foundDate: '2026-07-17T10:00:00Z', known: false, source: { type: 'enemy', id: 'wolf' } }); const service = new BookService({ character, inventoryManager: inventory }); service.useBook(character.inventory[0], getItemDefinition('history_of_the_old_kingdom'), { time: { day: 2 } }); assert.equal(character.bookJournal[0].known, true) })
test('Save restores Library, read/protected state, used books and exact fractional Practice values', () => { const character = hero(); character.proficiencySkills.Archery.baseValue = 24.36; character.foundBookIds = ['history_of_the_old_kingdom']; character.bookJournal = [{ bookId: 'history_of_the_old_kingdom', title: 'History of the Old Kingdom', foundDate: 'Day 2', known: true, source: 'ruins' }]; character.libraryRecords = [{ bookId: 'history_of_the_old_kingdom', title: 'History of the Old Kingdom', bookType: 'knowledge_book', category: 'History', status: 'Known', foundDate: 'Day 2', source: 'ruins', protected: true }]; character.usedManualIds = ['basic_archery_manual']; character.usedTreatiseIds = ['archery_master_treatise']; character.usedLegendaryTomeIds = ['legendary_archery_tome']; const restored = restoreCharacterState(JSON.parse(JSON.stringify(cloneCharacterState(character))), hero()); assert.equal(restored.proficiencySkills.Archery.baseValue, 24.36); assert.deepEqual(restored.foundBookIds, character.foundBookIds); assert.deepEqual(restored.bookJournal, character.bookJournal); assert.deepEqual(restored.libraryRecords, character.libraryRecords); assert.deepEqual(restored.usedManualIds, character.usedManualIds); assert.deepEqual(restored.usedTreatiseIds, character.usedTreatiseIds); assert.deepEqual(restored.usedLegendaryTomeIds, character.usedLegendaryTomeIds) })
