import assert from 'node:assert/strict'
import test from 'node:test'
import fs from 'node:fs'
import { createCharacterState, cloneCharacterState, restoreCharacterState } from '../src/game/characterState.js'
import { PROFICIENCY_NAMES } from '../src/data/characterCreation.js'
import { SKILL_RANK_DEFINITIONS, ABSOLUTE_SKILL_CAP } from '../src/skills/skillRankDefinitions.js'
import { attemptPracticeGain, calculateProficiency, canApplySkillBook, createProficiencyTooltipModel, gainBaseProficiency, increaseMaximumProficiencyCap, unlockNextProficiencyRank } from '../src/skills/proficiencySystem.js'
import { calculateCharacterStats } from '../src/character/characterStatCalculator.js'
import { createItemInstance } from '../src/items/itemInstance.js'
import { EquipmentManager } from '../src/equipment/equipmentManager.js'
import { evaluateTrainerLimit } from '../src/npc/trainerProgression.js'
import { TRAINERS } from '../src/data/trainers.js'

const hero = () => createCharacterState({ id: 'skill-hero', name: 'Hero', proficiencies: Object.fromEntries(PROFICIENCY_NAMES.map((name) => [name, ['Archery', 'Camping'].includes(name) ? 'Novice' : 'Untrained'])), startingWeapon: { id: 'test', combatSkills: [] } })

test('SkillRankDefinition provides all data-driven thresholds', () => { assert.deepEqual(SKILL_RANK_DEFINITIONS.map(({ name, minimumSkill, maximumSkill }) => [name, minimumSkill, maximumSkill]), [['Untrained', 0, 9], ['Novice', 10, 39], ['Apprentice', 40, 59], ['Adept', 60, 79], ['Expert', 80, 89], ['Master', 90, 99], ['Grandmaster', 100, 100]]) })
test('Character starts with Base, Rank Cap and default Maximum Cap', () => { const character = hero(); assert.deepEqual(character.proficiencySkills.Archery, { baseValue: 10, currentRank: 'Novice', currentRankCap: 39, maximumCap: 100 }); assert.equal(character.proficiencySkills.Alchemy.maximumCap, 100) })
test('Effective Value is Base plus calculated Bonus and Bonus is not persisted', () => { const character = hero(); character.proficiencySkills.Archery.baseValue = 38; const value = calculateProficiency(character, 'Archery', { temporaryEffects: [{ type: 'modify_proficiency', proficiency: 'Archery', amount: 7 }] }); assert.equal(value.baseValue, 38); assert.equal(value.bonusValue, 7); assert.equal(value.effectiveValue, 45); assert.equal('bonusValue' in character.proficiencySkills.Archery, false); assert.equal('effectiveValue' in cloneCharacterState(character).proficiencySkills.Archery, false) })
test('Equipment Bonus contributes to Effective Value', () => { const character = hero(); const equipment = new EquipmentManager(character); equipment.equip(createItemInstance('plain_ring'), 'ringLeft'); const calculated = calculateCharacterStats(character); assert.equal(calculated.proficiencyValues.Perception.baseValue, 0); assert.equal(calculated.proficiencyValues.Perception.bonusValue, 2); assert.equal(calculated.proficiencyValues.Perception.effectiveValue, 2) })
test('Trainer unlocks next Rank Cap without increasing Base and ignores Bonus', () => { const character = hero(); character.proficiencySkills.Archery.baseValue = 38; const before = calculateProficiency(character, 'Archery', { temporaryEffects: [{ type: 'modify_proficiency', proficiency: 'Archery', amount: 50 }] }); assert.equal(before.effectiveValue, 88); const limit = evaluateTrainerLimit(character, TRAINERS.village_hunter, { rewards: [{ type: 'upgrade_proficiency', proficiency: 'Archery' }] }); assert.equal(limit.baseValue, 38); const result = unlockNextProficiencyRank(character, 'Archery'); assert.equal(result.rank, 'Apprentice'); assert.equal(result.currentRankCap, 59); assert.equal(character.proficiencySkills.Archery.baseValue, 38) })
test('Base gains and Books respect Current Rank Cap without wasting content', () => { const character = hero(); character.proficiencySkills.Archery.baseValue = 38; assert.equal(gainBaseProficiency(character, 'Archery', 1).ok, true); assert.equal(gainBaseProficiency(character, 'Archery', 1).code, 'CURRENT_RANK_CAP_REACHED'); assert.equal(canApplySkillBook(character, 'Archery', 2).code, 'NEXT_RANK_REQUIRED'); assert.equal(character.proficiencySkills.Archery.baseValue, 39) })
test('Practice requires success, controlled RNG and respects Rank Cap', () => { const character = hero(); character.proficiencySkills.Archery.baseValue = 38; assert.equal(attemptPracticeGain(character, 'Archery', { successful: false, random: () => 0 }).code, 'ACTION_NOT_SUCCESSFUL'); assert.equal(attemptPracticeGain(character, 'Archery', { successful: true, random: () => 1 }).code, 'PRACTICE_GAIN_NOT_ROLLED'); assert.equal(attemptPracticeGain(character, 'Archery', { successful: true, random: () => 0 }).ok, true); assert.equal(character.proficiencySkills.Archery.baseValue, 38.01); character.proficiencySkills.Archery.baseValue = 39; assert.equal(attemptPracticeGain(character, 'Archery', { successful: true, random: () => 0 }).code, 'CURRENT_RANK_CAP_REACHED') })
test('Master Treatise architecture raises only Maximum Cap up to 120', () => { const character = hero(); character.proficiencies.Archery = 'Grandmaster'; character.proficiencySkills.Archery = { baseValue: 100, currentRank: 'Grandmaster', currentRankCap: 100, maximumCap: 100 }; assert.equal(increaseMaximumProficiencyCap(character, 'Archery', 5).maximumCap, 105); assert.equal(character.proficiencySkills.Archery.baseValue, 100); assert.equal(increaseMaximumProficiencyCap(character, 'Archery', 50).maximumCap, ABSOLUTE_SKILL_CAP) })
test('Save restores persistent proficiency data and migrates legacy ranks', () => { const character = hero(); character.proficiencySkills.Archery.baseValue = 32; const saved = JSON.parse(JSON.stringify(cloneCharacterState(character))); const restored = restoreCharacterState(saved, hero()); assert.equal(restored.proficiencySkills.Archery.baseValue, 32); assert.equal(restored.proficiencySkills.Archery.currentRankCap, 39); const legacy = cloneCharacterState(hero()); delete legacy.proficiencySkills; const migrated = restoreCharacterState(legacy, hero()); assert.equal(migrated.proficiencySkills.Archery.currentRank, 'Novice'); assert.equal(migrated.proficiencySkills.Archery.baseValue, 10) })
test('Tooltip and Character UI expose Rank, Base, Bonus, Effective and Caps', () => { const model = createProficiencyTooltipModel('Archery', { currentRank: 'Novice', baseValue: 38, bonusValue: 5, effectiveValue: 43, currentRankCap: 39, maximumCap: 100 }); assert.equal(model.effectiveValue, 43); const source = fs.readFileSync(new URL('../src/views/MenuThree.vue', import.meta.url), 'utf8'); for (const label of ['Base Value', 'Bonus Value', 'Effective Value', 'Current Rank Cap', 'Maximum Cap']) assert.match(source, new RegExp(label)) })
