import test from 'node:test'
import assert from 'node:assert/strict'
import { defineEncounter, defineEncounterTable, defineEncounterTableEntry } from '../src/encounters/encounterModels.js'
import { EncounterDatabase } from '../src/encounters/encounterDatabase.js'
import { createEmptyEncounterRunState, EncounterStateRepository, normalizeEncounterRunState } from '../src/encounters/encounterRepository.js'
import { EncounterSelectionService } from '../src/encounters/encounterSelectionService.js'
import { createEncounterTravelState } from '../src/encounters/encounterTravelModels.js'
import { EncounterFrequencyProfileResolver } from '../src/encounters/encounterFrequencyProfiles.js'
import { TravelEncounterService } from '../src/encounters/travelEncounterService.js'
import { MOVEMENT_SOURCE, TRAVEL_TRIGGER_RESULT } from '../src/encounters/encounterConstants.js'
import { migrateSave } from '../src/game/saveService.js'

const definition = defineEncounter({ id: 'wolf', displayName: 'Wolf', allowedLocationTags: ['Road', 'Wilderness'], weight: 1 })
const table = (noEncounterWeight = 0) => defineEncounterTable({ id: 'travel', locationTags: ['Road'], noEncounterWeight, encounterEntries: [defineEncounterTableEntry({ encounterDefinitionId: 'wolf', weight: 1 })] })
const profile = Object.freeze({ id: 'test', displayName: 'Test', baseMeterThresholdMinimum: 1, baseMeterThresholdMaximum: 3, roadMeterGainMultiplier: 1, wildernessMeterGainMultiplier: 2, nightMeterGainMultiplier: 2, dayMeterGainMultiplier: 1, safeZoneMeterGainMultiplier: 0, regionThreatMultiplierCurve: [{ value: 0, multiplier: 1 }, { value: 10, multiplier: 1 }], nightThreatMultiplierCurve: [{ value: 0, multiplier: 1 }, { value: 100, multiplier: 2 }], postEncounterGraceDistance: 2, postSafeZoneGraceDistance: 2, minimumDistanceBetweenChecks: 1, minimumDistanceBetweenTriggeredEncounters: 2, checkCooldownWorldMinutes: 30, encounterCooldownWorldMinutes: 60, allowChecksWhileStandingStill: false, allowedLocationTags: ['Road', 'Wilderness'], tags: [] })
const resolver = new EncounterFrequencyProfileResolver({ road_day: profile, road_night: profile, wilderness_day: profile, wilderness_night: profile, global_default: profile })
const create = ({ none = 0, state = createEmptyEncounterRunState() } = {}) => { const database = new EncounterDatabase({ encounters: [definition], tables: [table(none)] }); const stateRepository = new EncounterStateRepository(state); const selectionService = new EncounterSelectionService({ database, stateRepository, runSeed: 'travel-seed' }); const service = new TravelEncounterService({ selectionService, travelState: stateRepository.state.travelState, runSeed: 'travel-seed', profileResolver: resolver }); return { service, stateRepository, selectionService } }
const context = (changes = {}) => ({ characterId: 'hero', runId: 'run', movementSource: MOVEMENT_SOURCE.MANUAL, previousPosition: { row: 0, column: 0 }, currentPosition: { row: 0, column: 1 }, regionId: 'meadows', biomeTags: ['forest'], locationId: 'road', locationTags: ['Road'], previousWorldDay: 1, previousWorldTime: { hour: 8, minute: 0 }, worldDay: 1, worldTime: { hour: 8, minute: 10 }, isNight: false, nightThreatPercent: 0, regionThreatLevel: 1, randomSource: () => 0, stopMovement: () => true, ...changes })

test('valid travel updates distance while micro movement and standing still do not', () => { const { service, stateRepository } = create(); stateRepository.state.travelState.encounterMeterThreshold = 99; service.processTravelSegment(context()); assert.equal(stateRepository.state.travelState.accumulatedTravelDistance, 1); const result = service.processTravelSegment(context({ currentPosition: { row: 0, column: 0 } })); assert.equal(result.code, TRAVEL_TRIGGER_RESULT.INVALID); assert.equal(stateRepository.state.travelState.accumulatedTravelDistance, 1) })
test('teleport, fast travel, forced movement and combat do not increase distance or meter', () => { for (const movementSource of [MOVEMENT_SOURCE.TELEPORT, MOVEMENT_SOURCE.FAST_TRAVEL, MOVEMENT_SOURCE.FORCED]) { const { service, stateRepository } = create(); service.processTravelSegment(context({ movementSource })); assert.equal(stateRepository.state.travelState.accumulatedTravelDistance, 0); assert.equal(stateRepository.state.travelState.encounterMeterValue, 0) } const { service, stateRepository } = create(); service.processTravelSegment(context({ isInCombat: true })); assert.equal(stateRepository.state.travelState.encounterMeterValue, 0) })
test('pending encounter and blocking overlay stop all progress', () => { for (const changes of [{}, { hasBlockingOverlay: true }]) { const state = createEmptyEncounterRunState(); if (!changes.hasBlockingOverlay) state.travelState.pendingEncounterInstanceId = 'pending'; const { service, stateRepository } = create({ state }); service.processTravelSegment(context(changes)); assert.equal(stateRepository.state.travelState.accumulatedTravelDistance, 0) } })
test('Safe Zone freezes meter and starts grace after exit', () => { const { service, stateRepository } = create(); const state = stateRepository.state.travelState; state.encounterMeterThreshold = 99; service.processTravelSegment(context({ isInSafeZone: true, locationTags: ['SafeZone'] })); assert.equal(state.distanceSinceLeavingSafeZone, 0); assert.equal(state.encounterMeterValue, 0); assert.equal(service.processTravelSegment(context()).code, TRAVEL_TRIGGER_RESULT.SAFE_GRACE); assert.equal(state.encounterMeterValue, 0); service.processTravelSegment(context()); assert.ok(state.encounterMeterValue > 0) })
test('Road and Wilderness profiles and day/night threat change meter gain', () => { const { service } = create(); const road = service.previewTravelEncounterTrigger(context()); const wild = service.previewTravelEncounterTrigger(context({ locationTags: ['Wilderness'], locationId: 'wild' })); const night = service.previewTravelEncounterTrigger(context({ isNight: true, nightThreatPercent: 100, worldTime: { hour: 22 } })); assert.equal(road.profile.id, 'test'); assert.ok(wild.meterGain > road.meterGain); assert.ok(night.meterGain > road.meterGain) })
test('selection is not evaluated before threshold and preview is side-effect free', () => { const { service, stateRepository } = create(); stateRepository.state.travelState.encounterMeterThreshold = 50; let previews = 0; const original = service.selectionService.previewEncounterSelection.bind(service.selectionService); service.selectionService.previewEncounterSelection = (...args) => { previews += 1; return original(...args) }; const before = structuredClone(stateRepository.state); const preview = service.previewTravelEncounterTrigger(context()); assert.equal(preview.wouldPerformCheck, false); assert.equal(previews, 0); assert.deepEqual(stateRepository.state, before); service.processTravelSegment(context()); assert.equal(previews, 0) })
test('No Encounter resets meter, rolls threshold and sets only check cooldown', () => { const { service, stateRepository } = create({ none: 100 }); const state = stateRepository.state.travelState; state.encounterMeterThreshold = 1; const result = service.processTravelSegment(context({ randomSource: () => .99 })); assert.equal(result.code, 'NO_ENCOUNTER_SELECTED'); assert.equal(state.encounterMeterValue, 0); assert.ok(state.encounterMeterThreshold >= 1); assert.ok(state.encounterCheckCooldownUntil !== null); assert.equal(state.globalEncounterCooldownUntil, null); assert.equal(state.pendingEncounterInstanceId, null) })
test('selected encounter becomes PendingTrigger, locks movement and blocks duplicate trigger', () => { const { service, stateRepository } = create(); const state = stateRepository.state.travelState; state.encounterMeterThreshold = 1; let stopped = false; const result = service.processTravelSegment(context({ stopMovement: ({ reason }) => { stopped = reason === 'EncounterPending'; return true } })); assert.equal(result.code, TRAVEL_TRIGGER_RESULT.PENDING); assert.equal(result.encounterInstance.currentPhase, 'PendingTrigger'); assert.equal(stateRepository.instances.get(result.encounterInstance.instanceId).currentPhase, 'PendingTrigger'); assert.equal(state.pendingEncounterInstanceId, result.encounterInstance.instanceId); assert.equal(state.movementBlockedByEncounter, true); assert.equal(state.movementLockReason, 'EncounterPending'); assert.equal(stopped, true); const count = stateRepository.instances.getAll().length; assert.equal(service.processTravelSegment(context()).code, TRAVEL_TRIGGER_RESULT.ALREADY_PENDING); assert.equal(stateRepository.instances.getAll().length, count) })
test('check distance, check cooldown, global cooldown and post encounter grace are independent', () => { const { service, stateRepository } = create(); const state = stateRepository.state.travelState; state.encounterMeterThreshold = .1; state.distanceSinceLastEncounterCheck = 0; const distance = service.processTravelSegment(context({ travelDistance: .5 })); assert.equal(distance.code, TRAVEL_TRIGGER_RESULT.DISTANCE_BLOCKED); state.encounterCheckCooldownUntil = 9999; assert.equal(service.processTravelSegment(context()).code, TRAVEL_TRIGGER_RESULT.CHECK_COOLDOWN); state.encounterCheckCooldownUntil = null; state.globalEncounterCooldownUntil = 9999; assert.equal(service.processTravelSegment(context()).code, TRAVEL_TRIGGER_RESULT.GLOBAL_COOLDOWN); state.globalEncounterCooldownUntil = null; state.lastTriggeredEncounterInstanceId = 'old'; state.distanceSinceLastTriggeredEncounter = 0; assert.equal(service.processTravelSegment(context()).code, TRAVEL_TRIGGER_RESULT.ENCOUNTER_GRACE) })
test('threshold generation is deterministic for the same state and seed', () => { const first = create(); const second = create(); first.stateRepository.state.travelState.encounterMeterThreshold = 1; second.stateRepository.state.travelState.encounterMeterThreshold = 1; first.service.processTravelSegment(context({ randomSource: null })); second.service.processTravelSegment(context({ randomSource: null })); assert.equal(first.stateRepository.state.travelState.encounterMeterThreshold, second.stateRepository.state.travelState.encounterMeterThreshold) })
test('location transition preserves meter and zero-distance region transition cannot trigger', () => { const { service, stateRepository } = create(); const state = stateRepository.state.travelState; state.encounterMeterThreshold = 99; service.processTravelSegment(context()); const meter = state.encounterMeterValue; service.processTravelSegment(context({ locationTags: ['Wilderness'], locationId: 'wild' })); assert.ok(state.encounterMeterValue > meter); const instances = stateRepository.instances.getAll().length; service.processTravelSegment(context({ previousPosition: { row: 1, column: 1 }, currentPosition: { row: 1, column: 1 }, regionId: 'other' })); assert.equal(stateRepository.instances.getAll().length, instances) })
test('travel state persists meter, thresholds, cooldowns, distances and pending lock', () => { const state = createEmptyEncounterRunState(); Object.assign(state.travelState, { encounterMeterValue: 4, encounterMeterThreshold: 12, accumulatedTravelDistance: 7, globalEncounterCooldownUntil: 500, pendingEncounterInstanceId: 'enc-1', movementBlockedByEncounter: true }); const restored = normalizeEncounterRunState(JSON.parse(JSON.stringify(state))); assert.equal(restored.travelState.encounterMeterValue, 4); assert.equal(restored.travelState.encounterMeterThreshold, 12); assert.equal(restored.travelState.accumulatedTravelDistance, 7); assert.equal(restored.travelState.globalEncounterCooldownUntil, 500); assert.equal(restored.travelState.pendingEncounterInstanceId, 'enc-1'); assert.equal(restored.travelState.movementBlockedByEncounter, true) })
test('legacy migration creates a safe travel state and New Run defaults are reset', () => { const migrated = migrateSave({ saveVersion: 7, encounterState: { version: 1, encounterInstances: [], historyRecords: [], occurrenceCountersByEncounterId: {}, cooldowns: {}, encounterSequenceCounter: 0 } }); assert.equal(migrated.encounterState.travelState.encounterMeterValue, 0); assert.equal(migrated.encounterState.travelState.pendingEncounterInstanceId, null); assert.equal(migrated.encounterState.travelState.movementBlockedByEncounter, false); assert.deepEqual(createEncounterTravelState().recentTravelSegments, []) })
