import test from 'node:test'; import assert from 'node:assert/strict'
import { CONFLICT_POLICY,DURATION_TYPE,EFFECTS_STATUS,EVENT_SCOPE,EVENT_STATE,REPEAT_POLICY,TRIGGER_TYPE } from '../src/worldEvents/worldEventConstants.js'
import { createRegionState,createScheduledWorldEvent,createWorldEventInstance,createWorldState,defineWorldEvent } from '../src/worldEvents/worldEventModels.js'
import { WorldEventDatabase,worldEventDatabase } from '../src/worldEvents/worldEventDatabase.js'
import { createInitialWorldEventRuntime,normalizeWorldEventRuntime,WorldEventStateRepository } from '../src/worldEvents/worldEventRepository.js'
import { WorldEventProcessingService,WorldEventTriggerIndex } from '../src/worldEvents/worldEventServices.js'
import { createNewRun } from '../src/game/gameState.js'; import { migrateSave } from '../src/game/saveService.js'
const at=(day=1,hour=6)=>({worldDay:day,worldTime:{hour,minute:0},regionId:'meadows',locationId:'road'})
const signal=(type,id='s1',extra={})=>({signalId:id,triggerType:type,worldDay:1,worldTime:{hour:6,minute:0},regionId:'meadows',...extra})
const engine=(defs=worldEventDatabase.getAll())=>{const database=new WorldEventDatabase(defs);const repository=new WorldEventStateRepository(createInitialWorldEventRuntime('test-run'));const processing=new WorldEventProcessingService({database,repository});return{database,repository,processing}}
const manual=(d={})=>defineWorldEvent({id:d.id??'event',displayName:'Event',scope:EVENT_SCOPE.REGION,targetRegionIds:['meadows'],triggerDefinitions:[{id:'manual',triggerType:TRIGGER_TYPE.MANUAL,...(d.trigger??{})}],durationDefinition:{type:DURATION_TYPE.PERMANENT},repeatPolicy:REPEAT_POLICY.REPEATABLE,...d})

test('WorldState and RegionState initialize runtime data separately from Night Threat',()=>{const runtime=createInitialWorldEventRuntime('run');assert.equal(runtime.worldState.activeWorldEventIds.length,0);assert.equal(runtime.regionStates.meadows.threatLevel,1);assert.equal(runtime.regionStates.meadows.safetyLevel,3);assert.equal('nightThreat' in runtime.regionStates.meadows,false);assert.deepEqual(createWorldState().globalModifiers,{});assert.equal(createRegionState('x',{threatLevel:4}).threatLevel,4)})
test('definitions, instances and schedules have stable data-only models',()=>{const d=worldEventDatabase.get('merchant_delivery');assert.equal(d.eventType,'Delivery');assert.equal(Object.isFrozen(d),true);assert.equal(createWorldEventInstance({instanceId:'i',eventDefinitionId:d.id}).effectsStatus,EFFECTS_STATUS.NOT_REQUIRED);assert.equal(createScheduledWorldEvent({scheduleId:'s'}).processed,false);assert.equal(worldEventDatabase.validate().valid,true)})
test('definition validator detects missing regions, required IDs, follow-ups, duration and cooldown',()=>{const broken=defineWorldEvent({id:'broken',targetRegionIds:['missing'],requiredActiveEventIds:['absent'],followUpEventIds:['later'],durationDefinition:{type:'Wrong'},cooldownPolicy:{durationWorldMinutes:-1}});const v=new WorldEventDatabase([broken]).validate();for(const code of ['MISSING_REGION_ID','MISSING_REQUIRED_EVENT','MISSING_FOLLOW_UP_EVENT','INVALID_DURATION','NEGATIVE_COOLDOWN'])assert.ok(v.errors.some(x=>x.code===code))})
test('Trigger Index returns related definitions without scanning unrelated trigger types',()=>{const index=new WorldEventTriggerIndex(worldEventDatabase.getAll());assert.ok(index.get(signal(TRIGGER_TYPE.WORLD_DAY)).some(x=>x.definition.id==='merchant_delivery'));assert.ok(!index.get(signal(TRIGGER_TYPE.WORLD_DAY)).some(x=>x.definition.id==='shrine_desecrated'));assert.ok(index.get(signal(TRIGGER_TYPE.POI_COMPLETED,'x',{sourceId:'wolf_den'})).some(x=>x.definition.id==='northern_road_secured'))})
test('supported trigger types match source, value, day and manual target',()=>{const defs=[manual({id:'manual-a'}),manual({id:'manual-b'}),defineWorldEvent({id:'counter',targetRegionIds:['meadows'],triggerDefinitions:[{id:'c',triggerType:TRIGGER_TYPE.COUNTER_REACHED,sourceId:'danger',requiredValue:3,comparisonMode:'GreaterOrEqual'}]}),defineWorldEvent({id:'day',targetRegionIds:['meadows'],triggerDefinitions:[{id:'d',triggerType:TRIGGER_TYPE.WORLD_DAY,worldDay:2}]})];const e=engine(defs);assert.equal(e.processing.processSignal(signal(TRIGGER_TYPE.MANUAL,'m',{targetId:'manual-a'}),at()).results.length,1);assert.equal(e.processing.processSignal(signal(TRIGGER_TYPE.COUNTER_REACHED,'c',{sourceId:'danger',value:2}),at()).code,'WORLD_EVENT_NO_MATCHING_DEFINITIONS');assert.equal(e.processing.processSignal({...signal(TRIGGER_TYPE.WORLD_DAY,'d'),worldDay:1},at()).code,'WORLD_EVENT_NO_MATCHING_DEFINITIONS')})
test('conditions and preview are side-effect free',()=>{const d=manual({id:'conditional',conditions:[{type:'WorldCounter',counterId:'rescues',comparisonMode:'GreaterOrEqual',value:2}]});const e=engine([d]);const before=structuredClone(e.repository.worldState);assert.equal(e.processing.eligibility.previewWorldEventEligibility(d.id,at()).eligible,false);e.repository.worldState.worldCounters.rescues=2;assert.equal(e.processing.eligibility.previewWorldEventEligibility(d.id,at()).eligible,true);assert.equal(e.repository.worldState.eventInstances.length,0);assert.equal(before.eventSequenceCounter,e.repository.worldState.eventSequenceCounter)})
test('OncePerRun, OncePerRegion, OncePerLocation and Repeatable use scoped occurrence keys',()=>{for(const policy of [REPEAT_POLICY.ONCE_PER_RUN,REPEAT_POLICY.ONCE_PER_REGION,REPEAT_POLICY.ONCE_PER_LOCATION]){const e=engine([manual({id:`once-${policy}`,repeatPolicy:policy})]);const first=e.processing.processSignal(signal(TRIGGER_TYPE.MANUAL,'a',{targetId:`once-${policy}`}),at());assert.equal(first.results[0].ok,true);const second=e.processing.processSignal(signal(TRIGGER_TYPE.MANUAL,'b',{targetId:`once-${policy}`}),at());assert.equal(second.results[0].code,'WORLD_EVENT_NOT_ELIGIBLE')}const r=engine([manual({id:'repeat'})]);r.processing.processSignal(signal(TRIGGER_TYPE.MANUAL,'r1',{targetId:'repeat'}),at());r.processing.processSignal(signal(TRIGGER_TYPE.MANUAL,'r2',{targetId:'repeat'}),at());assert.equal(r.repository.worldState.eventOccurrenceCounters.repeat,2)})
test('cooldown blocks until world time reaches its deterministic end',()=>{const d=manual({id:'cool',repeatPolicy:REPEAT_POLICY.COOLDOWN,cooldownPolicy:{enabled:true,durationWorldMinutes:60,startsOn:'Activated',scope:'GlobalEventDefinition'}});const e=engine([d]);e.processing.processSignal(signal(TRIGGER_TYPE.MANUAL,'c1',{targetId:'cool'}),at());assert.equal(e.processing.eligibility.previewWorldEventEligibility('cool',at(1,6)).eligible,false);assert.equal(e.processing.eligibility.previewWorldEventEligibility('cool',at(1,7)).eligible,true)})
test('delayed trigger creates one schedule and activates only when due',()=>{const d=manual({id:'delayed',trigger:{delayWorldMinutes:120}});const e=engine([d]);const scheduled=e.processing.processSignal(signal(TRIGGER_TYPE.MANUAL,'delay',{targetId:'delayed'}),at());assert.equal(scheduled.results[0].code,'WORLD_EVENT_SCHEDULED');assert.equal(e.repository.worldState.eventOccurrenceCounters.delayed,undefined);assert.equal(e.processing.processTime(1,{hour:7,minute:59}).results.length,0);assert.equal(e.processing.processTime(1,{hour:8,minute:0}).results[0].code,'WORLD_EVENT_ACTIVATED_NO_EFFECTS');assert.equal(e.repository.worldState.eventOccurrenceCounters.delayed,1)})
test('batch scheduling processes equal due times deterministically',()=>{const defs=[manual({id:'a',trigger:{delayWorldMinutes:60}}),manual({id:'b',trigger:{delayWorldMinutes:60}})];const e=engine(defs);e.processing.processSignal(signal(TRIGGER_TYPE.MANUAL,'a1',{targetId:'a'}),at());e.processing.processSignal(signal(TRIGGER_TYPE.MANUAL,'b1',{targetId:'b'}),at());const r=e.processing.processTime(2,{hour:6,minute:0});assert.equal(r.results.length,2);assert.equal(e.repository.worldState.scheduledEvents.every(x=>x.processed),true)})
test('duration lifecycle handles permanent, timed and instant events with pending effects',()=>{const permanent=manual({id:'permanent'}),timed=manual({id:'timed',durationDefinition:{type:DURATION_TYPE.TIMED,durationWorldMinutes:60}}),instant=manual({id:'instant',durationDefinition:{type:DURATION_TYPE.INSTANT},effects:[]}),effects=manual({id:'effects',durationDefinition:{type:DURATION_TYPE.INSTANT},effects:[{id:'future'}]});const e=engine([permanent,timed,instant,effects]);for(const id of ['permanent','timed','instant','effects'])e.processing.processSignal(signal(TRIGGER_TYPE.MANUAL,id,{targetId:id}),at());assert.equal(e.repository.worldState.eventInstances.find(x=>x.eventDefinitionId==='permanent').currentState,EVENT_STATE.ACTIVE);assert.equal(e.repository.worldState.eventInstances.find(x=>x.eventDefinitionId==='instant').currentState,EVENT_STATE.COMPLETED);assert.equal(e.repository.worldState.eventInstances.find(x=>x.eventDefinitionId==='effects').effectsStatus,EFFECTS_STATUS.PENDING);e.processing.processTime(1,{hour:7,minute:0});assert.equal(e.repository.worldState.eventInstances.find(x=>x.eventDefinitionId==='timed').currentState,EVENT_STATE.EXPIRED)})
test('conflicts support BlockNew, ReplaceLowerPriority and AllowBoth',()=>{const low=manual({id:'low',priority:1,conflictTags:['road']}),blocked=manual({id:'blocked',priority:2,conflictTags:['road'],conflictPolicy:CONFLICT_POLICY.BLOCK_NEW}),high=manual({id:'high',priority:3,conflictTags:['road'],conflictPolicy:CONFLICT_POLICY.REPLACE_LOWER}),both=manual({id:'both',priority:1,conflictTags:['road'],conflictPolicy:CONFLICT_POLICY.ALLOW_BOTH});const e=engine([low,blocked,high,both]);e.processing.processSignal(signal(TRIGGER_TYPE.MANUAL,'l',{targetId:'low'}),at());assert.equal(e.processing.processSignal(signal(TRIGGER_TYPE.MANUAL,'b',{targetId:'blocked'}),at()).results[0].code,'WORLD_EVENT_NOT_ELIGIBLE');assert.equal(e.processing.processSignal(signal(TRIGGER_TYPE.MANUAL,'h',{targetId:'high'}),at()).results[0].ok,true);assert.equal(e.repository.worldState.eventInstances.find(x=>x.eventDefinitionId==='low').currentState,EVENT_STATE.CANCELLED);assert.equal(e.processing.processSignal(signal(TRIGGER_TYPE.MANUAL,'x',{targetId:'both'}),at()).results[0].ok,true)})
test('required active, completed and inactive events are resolved from runtime state',()=>{const base=manual({id:'base'}),active=manual({id:'needs-active',requiredActiveEventIds:['base']}),completed=manual({id:'needs-complete',requiredCompletedEventIds:['base']}),inactive=manual({id:'needs-inactive',requiredInactiveEventIds:['base']});const e=engine([base,active,completed,inactive]);assert.equal(e.processing.eligibility.previewWorldEventEligibility('needs-active',at()).eligible,false);e.processing.processSignal(signal(TRIGGER_TYPE.MANUAL,'base',{targetId:'base'}),at());assert.equal(e.processing.eligibility.previewWorldEventEligibility('needs-active',at()).eligible,true);assert.equal(e.processing.eligibility.previewWorldEventEligibility('needs-inactive',at()).eligible,false);const i=e.repository.worldState.eventInstances.find(x=>x.eventDefinitionId==='base');e.processing.lifecycle.complete(i.instanceId,at());assert.equal(e.processing.eligibility.previewWorldEventEligibility('needs-complete',at()).eligible,true)})
test('signals, activation and finalization are idempotent and history is structural',()=>{const e=engine([manual({id:'single',repeatPolicy:REPEAT_POLICY.ONCE_PER_RUN})]);e.processing.processSignal(signal(TRIGGER_TYPE.MANUAL,'same',{targetId:'single'}),at());assert.equal(e.processing.processSignal(signal(TRIGGER_TYPE.MANUAL,'same',{targetId:'single'}),at()).code,'WORLD_EVENT_TRIGGER_CONSUMED');assert.equal(e.repository.worldState.eventInstances.length,1);assert.equal(e.repository.worldState.eventHistory[0].type,'Started');const i=e.repository.worldState.eventInstances[0];e.processing.lifecycle.complete(i.instanceId,at());assert.equal(e.processing.lifecycle.complete(i.instanceId,at()).code,'WORLD_EVENT_ALREADY_FINALIZED');assert.equal(e.repository.worldState.eventHistory.at(-1).type,'Completed')})
test('save normalization preserves instances, schedules, cooldowns and effects state without reactivation',()=>{const e=engine([manual({id:'save',effects:[{id:'pending'}]})]);e.processing.processSignal(signal(TRIGGER_TYPE.MANUAL,'save-signal',{targetId:'save'}),at());e.repository.worldState.eventCooldowns.x={endsAt:99};const serialized=e.repository.serialize(),loaded=new WorldEventStateRepository(serialized);assert.equal(loaded.worldState.eventInstances.length,1);assert.equal(loaded.worldState.eventOccurrenceCounters.save,1);assert.equal(loaded.worldState.eventInstances[0].effectsStatus,EFFECTS_STATUS.PENDING);assert.deepEqual(loaded.worldState.eventCooldowns.x,{endsAt:99});assert.equal(loaded.reconcile(e.database).warnings.length,0)})
test('legacy migration and New Run create/reset safe event runtime',()=>{const migrated=migrateSave({saveVersion:7,runId:'old',seed:'s',encounterState:null});assert.ok(migrated.worldEventRuntime.worldState);const run=createNewRun(null,{seed:'world-event-new-run',runId:'new-run',now:()=> '2026-01-01'});assert.equal(run.worldEventRuntime.worldState.eventInstances.length,0);assert.equal(run.worldEventRuntime.regionStates.meadows.threatLevel,1);const repo=new WorldEventStateRepository(run.worldEventRuntime);repo.worldState.worldFlags.changed=true;repo.reset();assert.deepEqual(repo.worldState.worldFlags,{})})
