import { ARMOR_CATEGORY, DAMAGE_TYPE, ITEM_EFFECT_TYPE, ITEM_QUALITY, ITEM_TAG, ITEM_TYPE, WEAPON_CATEGORY } from './itemConstants.js'
import { BOOK_ITEM_DATA } from '../books/bookDefinitions.js'

const freezeList = (values = []) => Object.freeze(values.map((value) => Object.freeze({ ...value })))
export function defineItem(data) {
  if (!data?.id || !data.displayName || !Object.values(ITEM_TYPE).includes(data.itemType)) throw new Error('ItemDefinition requires a valid id, displayName and itemType.')
  if ([ITEM_TYPE.WEAPON, ITEM_TYPE.ARMOR].includes(data.itemType) && (data.requirements ?? []).some((requirement) => requirement.type !== 'attribute' || requirement.attribute !== 'strength')) throw new Error('Weapons and Armor may only define a Strength requirement.')
  const salvageableByDefault = Boolean(data.salvageDefinitionId && [ITEM_TYPE.WEAPON, ITEM_TYPE.ARMOR, ITEM_TYPE.SHIELD].includes(data.itemType))
  return Object.freeze({ description: '', value: 0, stackSize: 1, iconId: 'item-placeholder', icon: null, quality: ITEM_QUALITY.NORMAL, category: null, protected: false, unique: false, allowUniqueSalvage: false, salvageable: salvageableByDefault, salvageDefinitionId: null, equipSlots: Object.freeze([]), proficiency: null, tags: Object.freeze([]), requirements: Object.freeze([]), effects: Object.freeze([]), useContext: Object.freeze([]), useEffects: Object.freeze([]), consumeAmount: 1, durationMinutes: null, charges: null, fuelType: null, fuelCost: 0, resultingItemId: null, reusable: false, armorStats: null, weaponStats: null, bookData: null, ...data, salvageable: data.salvageable ?? salvageableByDefault, equipSlots: Object.freeze([...(data.equipSlots ?? [])]), tags: Object.freeze([...(data.tags ?? [])]), requirements: freezeList(data.requirements), effects: freezeList(data.effects), useContext: Object.freeze([...(data.useContext ?? [])]), useEffects: freezeList(data.useEffects), armorStats: data.armorStats ? Object.freeze({ ...data.armorStats, resistances: Object.freeze({ ...(data.armorStats.resistances ?? {}) }) }) : null, weaponStats: data.weaponStats ? Object.freeze({ ...data.weaponStats }) : null, bookData: data.bookData ? Object.freeze({ ...data.bookData, requirements: freezeList(data.bookData.requirements), effects: freezeList(data.bookData.effects) }) : null })
}
const weaponProficiency = Object.freeze({ [WEAPON_CATEGORY.MACE]: 'Mace Fighting', [WEAPON_CATEGORY.STAFF]: 'Mace Fighting', [WEAPON_CATEGORY.SWORD]: 'Swordsmanship', [WEAPON_CATEGORY.DAGGER]: 'Fencing', [WEAPON_CATEGORY.BOW]: 'Archery', [WEAPON_CATEGORY.CROSSBOW]: 'Archery' })
const weapon = (id, displayName, description, category, quality, stats, tags = [], requirements = [], salvageDefinitionId = null) => defineItem({ id, displayName, description, itemType: ITEM_TYPE.WEAPON, category, quality, value: quality === ITEM_QUALITY.BROKEN ? 2 : 8, stackSize: 1, iconId: `weapon-${category.toLowerCase().replaceAll(' ', '-')}`, equipSlots: ['mainHand'], proficiency: weaponProficiency[category] ?? null, tags, requirements, weaponStats: stats, salvageDefinitionId })
const strengthRequirement = (minimum) => Object.freeze([{ type: 'attribute', attribute: 'strength', minimum }])
const armorMaterials = Object.freeze({ [ARMOR_CATEGORY.CLOTH]: [ITEM_TAG.CLOTH, ITEM_TAG.LIGHT], [ARMOR_CATEGORY.LEATHER]: [ITEM_TAG.LEATHER, ITEM_TAG.LIGHT], [ARMOR_CATEGORY.STUDDED]: [ITEM_TAG.LEATHER, ITEM_TAG.METAL], [ARMOR_CATEGORY.BONE]: [ITEM_TAG.BONE], [ARMOR_CATEGORY.HIDE]: [ITEM_TAG.LEATHER], [ARMOR_CATEGORY.WOODLAND]: [ITEM_TAG.LEATHER] })
const armor = (id, displayName, description, category, armorRating, requiredStrength, resistances = {}, salvageDefinitionId = null) => defineItem({ id, displayName, description, itemType: ITEM_TYPE.ARMOR, category, quality: ITEM_QUALITY.NORMAL, value: armorRating * 12, stackSize: 1, iconId: `armor-${category.toLowerCase().replaceAll(' ', '-')}`, equipSlots: ['chest'], tags: armorMaterials[category] ?? (category.includes('mail') || category === ARMOR_CATEGORY.PLATEMAIL ? [ITEM_TAG.METAL, ITEM_TAG.HEAVY] : [ITEM_TAG.LIGHT]), requirements: strengthRequirement(requiredStrength), armorStats: { armorRating, maximumHpBonus: 0, resistances: { cold: 0, fire: 0, poison: 0, magic: 0, blunt: 0, piercing: 0, slashing: 0, ...resistances } }, salvageDefinitionId })

const items = [
  weapon('club', 'Club', 'A basic wooden bludgeon.', WEAPON_CATEGORY.MACE, ITEM_QUALITY.NORMAL, { baseDamage: 2, damageType: DAMAGE_TYPE.BLUNT, attackRange: 1, attackSpeed: 1, weaponCategory: WEAPON_CATEGORY.MACE, handsRequired: 1 }, [ITEM_TAG.WOOD, ITEM_TAG.ONE_HANDED, ITEM_TAG.STARTER], strengthRequirement(1)),
  weapon('wooden_staff', 'Wooden Staff', 'A long wooden fighting staff.', WEAPON_CATEGORY.STAFF, ITEM_QUALITY.NORMAL, { baseDamage: 2, damageType: DAMAGE_TYPE.BLUNT, attackRange: 2, attackSpeed: 0.8, weaponCategory: WEAPON_CATEGORY.STAFF, handsRequired: 2 }, [ITEM_TAG.WOOD, ITEM_TAG.TWO_HANDED, ITEM_TAG.STARTER], strengthRequirement(1), 'wood_weapon'),
  weapon('rusty_sword', 'Rusty Sword', 'A neglected sword with a damaged edge.', WEAPON_CATEGORY.SWORD, ITEM_QUALITY.POOR, { baseDamage: 3, damageType: DAMAGE_TYPE.SLASHING, attackRange: 1, attackSpeed: 1, weaponCategory: WEAPON_CATEGORY.SWORD, handsRequired: 1 }, [ITEM_TAG.METAL, ITEM_TAG.ONE_HANDED, ITEM_TAG.STARTER], strengthRequirement(2), 'metal_weapon'),
  weapon('item_rusty_dagger', 'Rusty Dagger', 'A fast but weathered dagger.', WEAPON_CATEGORY.DAGGER, ITEM_QUALITY.POOR, { baseDamage: 2, damageType: DAMAGE_TYPE.PIERCING, attackRange: 1, attackSpeed: 1.3, weaponCategory: WEAPON_CATEGORY.DAGGER, handsRequired: 1 }, [ITEM_TAG.METAL, ITEM_TAG.LIGHT, ITEM_TAG.ONE_HANDED], strengthRequirement(1)),
  weapon('short_bow', 'Short Bow', 'A compact hunting bow.', WEAPON_CATEGORY.BOW, ITEM_QUALITY.NORMAL, { baseDamage: 3, damageType: DAMAGE_TYPE.PIERCING, attackRange: 6, attackSpeed: 0.9, weaponCategory: WEAPON_CATEGORY.BOW, handsRequired: 2 }, [ITEM_TAG.WOOD, ITEM_TAG.TWO_HANDED], strengthRequirement(1)),
  armor('cloth_armor', 'Cloth Armor', 'Simple layered cloth protection.', ARMOR_CATEGORY.CLOTH, 1, 0, { cold: 1 }, 'cloth_armor'),
  armor('leather_armor', 'Leather Armor', 'Flexible protection made from treated leather.', ARMOR_CATEGORY.LEATHER, 2, 1, { cold: 1 }, 'leather_armor'),
  armor('studded_armor', 'Studded Armor', 'Leather reinforced with metal studs.', ARMOR_CATEGORY.STUDDED, 3, 2, { piercing: 1 }, 'studded_armor'),
  armor('hide_armor', 'Hide Armor', 'Thick untreated hide armor.', ARMOR_CATEGORY.HIDE, 4, 3, { cold: 2 }),
  armor('ringmail_armor', 'Ringmail Armor', 'Metal rings sewn over a sturdy backing.', ARMOR_CATEGORY.RINGMAIL, 4, 4, { slashing: 2 }),
  armor('chainmail_armor', 'Chainmail Armor', 'Interlocking metal rings offering reliable defense.', ARMOR_CATEGORY.CHAINMAIL, 5, 5, { slashing: 3, piercing: 1 }),
  armor('platemail_armor', 'Platemail Armor', 'Heavy articulated plates for exceptional protection.', ARMOR_CATEGORY.PLATEMAIL, 8, 8, { slashing: 5, piercing: 4, blunt: 2 }),
  armor('dragon_armor', 'Dragon Armor', 'Exceptional protection made from dragon material.', ARMOR_CATEGORY.DRAGON, 12, 12, { fire: 8, slashing: 6 }),
  armor('woodland_armor', 'Woodland Armor', 'Light armor adapted to forest travel.', ARMOR_CATEGORY.WOODLAND, 3, 3, { poison: 2, cold: 1 }),
  armor('bone_armor', 'Bone Armor', 'Interlocked plates carved from large bones.', ARMOR_CATEGORY.BONE, 4, 4, { magic: 1, piercing: 2 }, 'bone_armor'),
  defineItem({ id: 'plain_ring', displayName: 'Plain Ring', description: 'A simple ring that sharpens awareness.', itemType: ITEM_TYPE.ACCESSORY, value: 5, stackSize: 1, iconId: 'accessory-ring', equipSlots: ['ringLeft', 'ringRight'], quality: ITEM_QUALITY.NORMAL, tags: [ITEM_TAG.METAL], effects: [{ type: ITEM_EFFECT_TYPE.MODIFY_PROFICIENCY, proficiency: 'Perception', amount: 2 }] }),
  defineItem({ id: 'warded_ring', displayName: 'Warded Ring', description: 'A small ring carrying a minor protective pattern.', itemType: ITEM_TYPE.ACCESSORY, value: 15, stackSize: 1, iconId: 'accessory-warded-ring', equipSlots: ['ringLeft', 'ringRight'], quality: ITEM_QUALITY.FINE, tags: [ITEM_TAG.METAL, ITEM_TAG.MAGIC], effects: [{ type: ITEM_EFFECT_TYPE.MODIFY_RESISTANCE, resistance: 'magic', amount: 2 }] }),
  defineItem({ id: 'wardwood', displayName: 'Wardwood', description: 'Protective wood used as fuel against night threats.', itemType: ITEM_TYPE.MATERIAL, value: 3, stackSize: 100, iconId: 'material-wardwood', quality: ITEM_QUALITY.NORMAL, tags: [ITEM_TAG.WOOD, ITEM_TAG.CRAFTING], useContext: ['exploration', 'camp'], useEffects: [{ type: 'open_wardwood_actions' }], reusable: true }),
  defineItem({ id: 'torch', displayName: 'Torch', description: 'A portable Wardwood light source.', itemType: ITEM_TYPE.CONSUMABLE, value: 5, stackSize: 20, iconId: 'consumable-torch', quality: ITEM_QUALITY.NORMAL, tags: [ITEM_TAG.WOOD, ITEM_TAG.FIRE, ITEM_TAG.CONSUMABLE], effects: [{ type: ITEM_EFFECT_TYPE.GRANT_LIGHT_SOURCE, lightSourceId: 'Torch' }], useContext: ['exploration'], useEffects: [{ type: 'activate_light_source', lightSourceType: 'Torch' }], consumeAmount: 1, durationMinutes: 120 }),
  defineItem({ id: 'lantern', displayName: 'Lantern', description: 'A reusable lantern fueled with Wardwood.', itemType: ITEM_TYPE.CONSUMABLE, value: 20, stackSize: 1, iconId: 'utility-lantern', quality: ITEM_QUALITY.NORMAL, tags: [ITEM_TAG.METAL], useContext: ['exploration', 'camp'], useEffects: [{ type: 'manage_lantern' }], fuelType: 'wardwood', reusable: true }),
  defineItem({ id: 'holy_lantern', displayName: 'Holy Lantern', description: 'A developer placeholder for an enduring sacred light.', itemType: ITEM_TYPE.KEY_ITEM, value: 0, stackSize: 1, iconId: 'utility-holy-lantern', quality: ITEM_QUALITY.MASTERWORK, tags: [ITEM_TAG.HOLY, ITEM_TAG.MAGIC], useContext: ['exploration', 'camp'], useEffects: [{ type: 'toggle_holy_lantern' }], reusable: true }),
  defineItem({ id: 'wolf_hide', displayName: 'Wolf Hide', description: 'A rough hide taken from a defeated wolf.', itemType: ITEM_TYPE.MATERIAL, value: 6, stackSize: 20, iconId: 'material-wolf-hide', tags: [ITEM_TAG.CRAFTING] }),
  defineItem({ id: 'raw_meat', displayName: 'Raw Meat', description: 'Fresh meat that should be cooked before eating.', itemType: ITEM_TYPE.CONSUMABLE, value: 2, stackSize: 10, iconId: 'consumable-raw-meat', tags: [ITEM_TAG.CONSUMABLE] }),
  defineItem({ id: 'cooked_meat', displayName: 'Cooked Meat', description: 'A simple, nourishing meal cooked over a fire.', itemType: ITEM_TYPE.CONSUMABLE, category: 'Food', value: 5, stackSize: 20, iconId: 'consumable-cooked-meat', tags: [ITEM_TAG.CONSUMABLE] }),
  defineItem({ id: 'simple_soup', displayName: 'Simple Soup', description: 'A warm camp meal made from basic provisions.', itemType: ITEM_TYPE.CONSUMABLE, category: 'Food', value: 7, stackSize: 20, iconId: 'consumable-simple-soup', tags: [ITEM_TAG.CONSUMABLE] }),
  defineItem({ id: 'sealed_contract', displayName: 'Sealed Contract', description: 'A protected document tied to an unfinished task.', itemType: ITEM_TYPE.QUEST_ITEM, value: 0, stackSize: 1, iconId: 'quest-contract', tags: [ITEM_TAG.QUEST] }),
  defineItem({ id: 'silver_cup', displayName: 'Silver Cup', description: 'A decorative cup valued by collectors.', itemType: ITEM_TYPE.TREASURE, value: 25, stackSize: 1, iconId: 'treasure-silver-cup', tags: [ITEM_TAG.METAL] }),
  defineItem({ id: 'wolf_tooth', displayName: 'Wolf Tooth', description: 'A sharp tooth from a mature wolf.', itemType: ITEM_TYPE.MATERIAL, value: 9, stackSize: 10, iconId: 'material-wolf-tooth', tags: [ITEM_TAG.BONE, ITEM_TAG.CRAFTING] }),
  defineItem({ id: 'dead_wardwood', displayName: 'Dead Wardwood', description: 'Wardwood that has lost its protective properties.', itemType: ITEM_TYPE.MATERIAL, value: 1, stackSize: 100, iconId: 'material-dead-wardwood', tags: [ITEM_TAG.WOOD, ITEM_TAG.CRAFTING] }),
  weapon('simple_crossbow', 'Simple Crossbow', 'A basic crossbow that requires no tracked ammunition.', WEAPON_CATEGORY.CROSSBOW, ITEM_QUALITY.NORMAL, { baseDamage: 4, damageType: DAMAGE_TYPE.PIERCING, attackRange: 7, attackSpeed: 0.7, weaponCategory: WEAPON_CATEGORY.CROSSBOW, handsRequired: 2 }, [ITEM_TAG.WOOD, ITEM_TAG.METAL, ITEM_TAG.TWO_HANDED], strengthRequirement(2)),
  defineItem({ id: 'wooden_shield', displayName: 'Wooden Shield', description: 'A basic defensive shield.', itemType: ITEM_TYPE.SHIELD, category: 'Shield', value: 8, stackSize: 1, iconId: 'shield-wooden', equipSlots: ['offHand'], quality: ITEM_QUALITY.NORMAL, tags: [ITEM_TAG.WOOD], requirements: strengthRequirement(1), armorStats: { armorRating: 1, maximumHpBonus: 0, resistances: { blunt: 1 } }, salvageDefinitionId: 'wood_shield' }),
  defineItem({ id: 'bandage', displayName: 'Bandage', description: 'A simple medical dressing reserved for a future healing action.', itemType: ITEM_TYPE.CONSUMABLE, category: 'Medical', value: 4, stackSize: 20, iconId: 'consumable-bandage', quality: ITEM_QUALITY.NORMAL, tags: [ITEM_TAG.CONSUMABLE] }),
  defineItem({ id: 'travel_ration', displayName: 'Travel Ration', description: 'Preserved food for the road.', itemType: ITEM_TYPE.CONSUMABLE, category: 'Food', value: 3, stackSize: 20, iconId: 'consumable-ration', quality: ITEM_QUALITY.NORMAL, tags: [ITEM_TAG.CONSUMABLE] }),
  defineItem({ id: 'metal_scrap', displayName: 'Metal Scrap', description: 'Small reusable pieces of ordinary metal.', itemType: ITEM_TYPE.MATERIAL, value: 1, stackSize: 100, iconId: 'material-metal-scrap', tags: [ITEM_TAG.METAL, ITEM_TAG.CRAFTING] }),
  defineItem({ id: 'leather_scrap', displayName: 'Leather Scrap', description: 'A small piece of reusable leather.', itemType: ITEM_TYPE.MATERIAL, value: 1, stackSize: 100, iconId: 'material-leather-scrap', tags: [ITEM_TAG.LEATHER, ITEM_TAG.CRAFTING] }),
  defineItem({ id: 'cloth_scrap', displayName: 'Cloth Scrap', description: 'A usable remnant of ordinary cloth.', itemType: ITEM_TYPE.MATERIAL, value: 1, stackSize: 100, iconId: 'material-cloth-scrap', tags: [ITEM_TAG.CLOTH, ITEM_TAG.CRAFTING] }),
  defineItem({ id: 'bone_fragment', displayName: 'Bone Fragment', description: 'A sturdy fragment suitable for future crafting.', itemType: ITEM_TYPE.MATERIAL, value: 1, stackSize: 100, iconId: 'material-bone-fragment', tags: [ITEM_TAG.BONE, ITEM_TAG.CRAFTING] }),
  defineItem({ id: 'wood_scrap', displayName: 'Wood Scrap', description: 'A small reusable piece of common wood.', itemType: ITEM_TYPE.MATERIAL, value: 1, stackSize: 100, iconId: 'material-wood-scrap', tags: [ITEM_TAG.WOOD, ITEM_TAG.CRAFTING] }),
  ...BOOK_ITEM_DATA.map(defineItem),
]

export const ITEM_LIST = Object.freeze(items)
export const ITEM_DATABASE = Object.freeze(Object.fromEntries(items.map((item) => [item.id, item])))
export function getItemDefinition(itemId) { return ITEM_DATABASE[itemId] ?? null }
export function getItemsByType(itemType) { return ITEM_LIST.filter((item) => item.itemType === itemType) }
