import { DIALOGUE_EFFECT, DIALOGUE_REPEAT, EXTERNAL_ACTION } from './dialogueConstants.js'
import { defineDialogue } from './dialogueModels.js'
const leave={id:'leave',text:'Leave.',endsDialogue:true,sortOrder:99}
export const DIALOGUE_NPCS=Object.freeze({hunter:{id:'hunter',displayName:'Edrin the Hunter'},innkeeper:{id:'innkeeper',displayName:'Mara the Innkeeper'},scholar:{id:'scholar',displayName:'Scholar Alden'},blacksmith:{id:'blacksmith',displayName:'Borin the Blacksmith'},developer:{id:'developer',displayName:'Developer NPC'}})
const defaultDialogue=(id,npcId,text,choices=[])=>defineDialogue({id,npcId,displayName:DIALOGUE_NPCS[npcId].displayName,priority:10,startNodeId:'hub',nodeDefinitions:[{id:'hub',speaker:{speakerType:'Npc'},text,choices:[...choices,leave]}]})
export const dialogueDefinitions=Object.freeze([
 defineDialogue({id:'hunter_first_meeting',npcId:'hunter',displayName:'First Meeting',priority:80,startNodeId:'intro',maximumCompletions:1,nodeDefinitions:[{id:'intro',speaker:{speakerType:'Npc'},text:'I have not seen you before, {playerName}. Keep your eyes open beyond the road.',choices:[{id:'continue',text:'I will.',endsDialogue:true}]}]}),
 defineDialogue({id:'hunter_topics',npcId:'hunter',displayName:'Hunter',priority:10,startNodeId:'hub',nodeDefinitions:[{id:'hub',speaker:{speakerType:'Npc'},text:'What do you need?',choices:[{id:'wolves',text:'Tell me about the wolves.',nextNodeId:'wolves'},leave]},{id:'wolves',speaker:{speakerType:'Npc'},text:'They favor the northern road after dusk.',choices:[{id:'back',text:'Anything else?',nextNodeId:'hub'}]}]}),
 defaultDialogue('innkeeper_default','innkeeper','Welcome. A warm meal and local rumors are both available.',[{id:'trade',text:'Show me your goods.',opensExternalAction:{type:EXTERNAL_ACTION.MERCHANT,targetId:'general_merchant'}},{id:'rest',text:'I need a room.',opensExternalAction:{type:EXTERNAL_ACTION.REST,targetId:'inn'}}]),
 defaultDialogue('scholar_default','scholar','Knowledge rewards the patient reader.',[{id:'learn',text:'Let me study what I know.',opensExternalAction:{type:EXTERNAL_ACTION.KNOWLEDGE}}]),
 defaultDialogue('blacksmith_default','blacksmith','Steel needs a steady hand.',[{id:'trade',text:'Show me your equipment.',opensExternalAction:{type:EXTERNAL_ACTION.MERCHANT,targetId:'blacksmith'}},{id:'train',text:'Can you train me?',opensExternalAction:{type:EXTERNAL_ACTION.TRAINER,targetId:'blacksmith_trainer'}}]),
 defineDialogue({id:'developer_dialogue',npcId:'developer',displayName:'Dialogue Laboratory',priority:100,startNodeId:'hub',nodeDefinitions:[{id:'hub',speaker:{speakerType:'Npc'},text:'Dialogue test for {playerName}. You have {gold} Gold on day {worldDay}.',choices:[{id:'hidden',text:'Hidden option',visibilityRequirements:[{type:'dialogue_flag',flag:'show_hidden'}]},{id:'locked',text:'Expensive option',availabilityRequirements:[{type:'gold',minimum:999}],disabledReason:'Requires 999 Gold.'},{id:'paid',text:'Pay 5 Gold.',costs:[{type:'Gold',quantity:5}],effects:[{id:'paid-flag',effectType:DIALOGUE_EFFECT.SET_DIALOGUE_FLAG,flag:'paid'}],nextNodeId:'result',repeatPolicy:DIALOGUE_REPEAT.ONCE_PER_DAY},{id:'check',text:'Attempt a Perception check.',check:{stat:'perception',difficulty:8},nextNodeId:'success',failureNodeId:'failure'},leave]},{id:'result',speaker:{speakerType:'System'},text:'The atomic payment succeeded.',autoAdvance:true,defaultNextNodeId:'hub',choices:[{id:'return',text:'Return.',nextNodeId:'hub'}]},{id:'success',speaker:{speakerType:'Narrator'},text:'You notice the hidden detail.',choices:[{id:'back-success',text:'Continue.',nextNodeId:'hub'}]},{id:'failure',speaker:{speakerType:'Narrator'},text:'Nothing catches your eye.',choices:[{id:'back-failure',text:'Continue.',nextNodeId:'hub'}]}]})
].filter(Boolean))
