import{OBJECTIVE_STATUS,PROGRESS_TYPE,QUEST_REPEAT,QUEST_STATUS,STAGE_POLICY,STAGE_STATUS}from'./questConstants.js'
const clone=v=>structuredClone(v??{})
export const defineObjective=(d={})=>Object.freeze({id:d.id,displayName:d.displayName??d.id,description:d.description??'',objectiveType:d.objectiveType??'Custom',progressType:d.progressType??PROGRESS_TYPE.BOOLEAN,targetIds:[...(d.targetIds??[])],targetTags:[...(d.targetTags??[])],requiredCount:d.requiredCount??1,requiredValue:d.requiredValue??null,comparison:d.comparison??'GreaterOrEqual',optional:Boolean(d.optional),hidden:Boolean(d.hidden),retroactive:Boolean(d.retroactive),trackOnMap:Boolean(d.trackOnMap),signalTypes:[...(d.signalTypes??[])],filters:clone(d.filters),sequence:[...(d.sequence??[])],completionEffects:[...(d.completionEffects??[])],sortOrder:d.sortOrder??0,enabled:d.enabled!==false})
export const defineStage=(d={})=>Object.freeze({id:d.id,displayName:d.displayName??d.id,description:d.description??'',objectiveDefinitions:Object.freeze((d.objectiveDefinitions??[]).map(defineObjective)),entryRequirements:[...(d.entryRequirements??[])],activationEffects:[...(d.activationEffects??[])],completionPolicy:d.completionPolicy??STAGE_POLICY.ALL,requiredCount:d.requiredCount??null,completionEffects:[...(d.completionEffects??[])],failureEffects:[...(d.failureEffects??[])],transitions:[...(d.transitions??[])],defaultNextStageId:d.defaultNextStageId??null,allowManualAdvance:Boolean(d.allowManualAdvance)})
export const defineQuest=(d={})=>Object.freeze({id:d.id,displayName:d.displayName??d.id,shortDescription:d.shortDescription??'',longDescription:d.longDescription??'',category:d.category??'Side',priority:d.priority??0,startStageId:d.startStageId,stageDefinitions:Object.freeze((d.stageDefinitions??[]).map(defineStage)),entryRequirements:[...(d.entryRequirements??[])],visibilityRequirements:[...(d.visibilityRequirements??[])],availabilityRequirements:[...(d.availabilityRequirements??[])],startEffects:[...(d.startEffects??[])],completionEffects:[...(d.completionEffects??[])],failureEffects:[...(d.failureEffects??[])],cancelEffects:[...(d.cancelEffects??[])],rewards:[...(d.rewards??[])],repeatPolicy:d.repeatPolicy??QUEST_REPEAT.ONCE,maximumCompletions:d.maximumCompletions??null,relatedNpcIds:[...(d.relatedNpcIds??[])],relatedPoiIds:[...(d.relatedPoiIds??[])],relatedRegionIds:[...(d.relatedRegionIds??[])],relatedWorldEventIds:[...(d.relatedWorldEventIds??[])],tags:[...(d.tags??[])],enabled:d.enabled!==false,version:d.version??1})
export const createObjectiveState=(o,c={})=>({objectiveId:o.id,status:OBJECTIVE_STATUS.ACTIVE,currentCount:0,requiredCount:o.requiredCount,currentValue:null,requiredValue:o.requiredValue,collectedTargetIds:[],sequenceIndex:0,matchedState:null,activatedWorldDay:c.worldDay??1,activatedWorldTime:clone(c.worldTime??{hour:6,minute:0}),processedSignalIds:[],appliedCompletionEffectIds:[],storedValues:{},version:1})
export const createStageState=(stage,c={})=>({stageId:stage.id,status:STAGE_STATUS.ACTIVE,activatedWorldDay:c.worldDay??1,activatedWorldTime:clone(c.worldTime??{hour:6,minute:0}),objectiveStates:Object.fromEntries(stage.objectiveDefinitions.map(o=>[o.id,createObjectiveState(o,c)])),appliedActivationEffectIds:[],appliedCompletionEffectIds:[],appliedFailureEffectIds:[],storedValues:{},transitionResult:null,version:1})
export const createQuestInstance=(q,c={})=>({instanceId:c.instanceId,questId:q.id,status:QUEST_STATUS.ACTIVE,currentStageId:q.startStageId,previousStageId:null,stageStates:{},startedWorldDay:c.worldDay??1,startedWorldTime:clone(c.worldTime??{hour:6,minute:0}),startSource:c.startSource??'Developer',sourceId:c.sourceId??null,completionCountAtStart:c.completionCount??0,activeObjectiveIds:[],optionalObjectiveIds:[],completedObjectiveIds:[],failedObjectiveIds:[],skippedObjectiveIds:[],appliedEffectIds:[],rewardedRewardIds:[],storedValues:{},storedRolls:{},pendingTransition:null,pendingEffectTransactionId:null,tracked:true,version:1})
export const createQuestRuntime=(d={})=>({version:1,instances:clone(d.instances??[]),history:clone(d.history??[]),completionCounts:clone(d.completionCounts),instanceSequence:d.instanceSequence??0,primaryTrackedQuestId:d.primaryTrackedQuestId??null,processedSignalIds:[...(d.processedSignalIds??[])]})
