import{NPC_ACTIVITY as A,NPC_AVAILABILITY as V,NPC_PRESENCE as P,SCHEDULE_TYPE as T}from'./npcScheduleConstants.js';import{defineNpcSchedule}from'./npcScheduleModels.js'
const entry=(id,startTime,endTime,activity,target,availability=V.AVAILABLE,interactionOverrides={})=>({id,startTime,endTime,activity,target,presenceState:P.PRESENT,availabilityState:availability,interactionOverrides})
export const NPC_ASSIGNMENTS=Object.freeze({general_merchant:{homeLocationId:'merchant_home',workplaceLocationId:'general_store',preferredInnLocationId:'village_inn',fallbackLocationId:'merchant_home'},blacksmith:{homeLocationId:'blacksmith_home',workplaceLocationId:'forge',preferredInnLocationId:'village_inn',fallbackLocationId:'blacksmith_home'},hunter:{homeLocationId:'hunter_hut',workplaceLocationId:'hunting_grounds',preferredInnLocationId:'village_inn',fallbackLocationId:'hunter_hut'},innkeeper:{homeLocationId:'village_inn',workplaceLocationId:'village_inn',preferredInnLocationId:'village_inn',fallbackLocationId:'village_inn'},scholar:{homeLocationId:'scholar_quarters',workplaceLocationId:'library',preferredInnLocationId:'village_inn',fallbackLocationId:'scholar_quarters'},developer:{homeLocationId:'debug_home',workplaceLocationId:'debug_lab',preferredInnLocationId:'village_inn',fallbackLocationId:'debug_home'}})
export const SCHEDULE_LOCATIONS=Object.freeze([...new Set(Object.values(NPC_ASSIGNMENTS).flatMap(Object.values).filter(x=>typeof x==='string')),'temple_courtyard'])
export const npcScheduleDefinitions=Object.freeze([
defineNpcSchedule({id:'merchant_daily',npcId:'general_merchant',displayName:'Merchant Daily Routine',fallbackEntryId:'sleep',entries:[entry('sleep',{hour:21},{hour:7},A.SLEEPING,{type:'Home'},V.SLEEPING,{Talk:false,Trade:false}),entry('store',{hour:7},{hour:18},A.TRADING,{type:'Workplace'},V.AVAILABLE,{Talk:true,Trade:true}),entry('inn',{hour:18},{hour:21},A.SOCIALIZING,{type:'Inn'},V.LIMITED,{Talk:true,Trade:false})]}),
defineNpcSchedule({id:'blacksmith_daily',npcId:'blacksmith',displayName:'Blacksmith Daily Routine',fallbackEntryId:'sleep',entries:[entry('sleep',{hour:21},{hour:6},A.SLEEPING,{type:'Home'},V.SLEEPING,{Talk:false,Trade:false,Train:false}),entry('prepare',{hour:6},{hour:7},A.IDLE,{type:'Home'},V.BUSY,{Talk:true,Trade:false,Train:false}),entry('forge_morning',{hour:7},{hour:12},A.WORKING,{type:'Workplace'},V.AVAILABLE,{Talk:true,Trade:true,Train:true}),entry('meal',{hour:12},{hour:13},A.EATING,{type:'Inn'},V.LIMITED,{Talk:true,Trade:false,Train:false}),entry('forge_afternoon',{hour:13},{hour:18},A.WORKING,{type:'Workplace'},V.AVAILABLE,{Talk:true,Trade:true,Train:true}),entry('social',{hour:18},{hour:21},A.SOCIALIZING,{type:'Inn'},V.LIMITED,{Talk:true,Trade:false,Train:false})]}),
defineNpcSchedule({id:'hunter_daily',npcId:'hunter',displayName:'Hunter Daily Routine',fallbackEntryId:'sleep',entries:[entry('sleep',{hour:22},{hour:6},A.SLEEPING,{type:'Home'},V.SLEEPING,{Talk:false}),entry('hunt',{hour:6},{hour:17},A.HUNTING,{type:'Workplace',roadId:'northern_road'},V.BUSY,{Talk:false}),entry('inn',{hour:17},{hour:22},A.SOCIALIZING,{type:'Inn'},V.AVAILABLE,{Talk:true})]}),
defineNpcSchedule({id:'hunter_wolves_override',npcId:'hunter',displayName:'Hunting Wolves',priority:500,scheduleType:T.EVENT,entryRequirements:[{type:'world_flag',flag:'wolves_occupy_northern_road'}],fallbackEntryId:'hut',entries:[entry('guard',{hour:6},{hour:20},A.GUARDING,{type:'Workplace',roadId:'northern_road'},V.LIMITED,{Talk:true}),entry('hut',{hour:20},{hour:6},A.HIDING,{type:'Home'},V.BUSY,{Talk:true})]}),
defineNpcSchedule({id:'innkeeper_daily',npcId:'innkeeper',displayName:'Innkeeper Daily Routine',entries:[entry('work',{hour:5},{hour:1},A.WORKING,{type:'Workplace'},V.AVAILABLE,{Talk:true,Trade:true,Rest:true}),entry('sleep',{hour:1},{hour:5},A.SLEEPING,{type:'Home'},V.SLEEPING,{Talk:false})],fallbackEntryId:'work'}),
defineNpcSchedule({id:'scholar_daily',npcId:'scholar',displayName:'Scholar Daily Routine',entries:[entry('sleep',{hour:22},{hour:7},A.SLEEPING,{type:'Home'},V.SLEEPING,{Talk:false,Learn:false}),entry('study',{hour:7},{hour:15},A.STUDYING,{type:'Workplace'},V.AVAILABLE,{Talk:true,Learn:true}),entry('teach',{hour:15},{hour:18},A.TEACHING,{type:'Location',id:'temple_courtyard'},V.AVAILABLE,{Talk:true,Learn:true}),entry('rest',{hour:18},{hour:22},A.RESTING,{type:'Home'},V.LIMITED,{Talk:true,Learn:false})],fallbackEntryId:'sleep'}),
defineNpcSchedule({id:'developer_midnight',npcId:'developer',displayName:'Developer Midnight Test',scheduleType:T.DEVELOPER,entries:[entry('night',{hour:22},{hour:6},A.CUSTOM,{type:'Workplace'},V.AVAILABLE,{Talk:true}),entry('day',{hour:6},{hour:22},A.IDLE,{type:'Home'},V.AVAILABLE,{Talk:true})],fallbackEntryId:'day'})])
