import { createItemInstance } from '../items/itemInstance.js'

export const WARDWOOD_CONFIG = Object.freeze({ expirationDays: 7, campfireCost: 3, torchCost: 1, torchDurationMinutes: 120, lanternMaximumFuelMinutes: 480, lanternMinutesPerWardwood: 96, campfireRecoveryChance: 0.5, campfireRecoveryQuantity: 1 })
let batchSequence = 1

export class WardwoodService {
  constructor(character, inventoryManager) { this.character = character; this.inventory = inventoryManager }
  reconcile(day) { const inventoryQuantity = this.character.inventory.filter(({ definitionId }) => definitionId === 'wardwood').reduce((sum, item) => sum + item.quantity, 0); const batchQuantity = this.character.wardwoodBatches.reduce((sum, batch) => sum + batch.quantity, 0); if (inventoryQuantity > batchQuantity) this.character.wardwoodBatches.push({ id: `wardwood-batch-${batchSequence++}`, quantity: inventoryQuantity - batchQuantity, acquiredDay: day, expirationDay: day + WARDWOOD_CONFIG.expirationDays }); this.syncTotal(); return this.character.wardwoodBatches }
  syncTotal() { this.character.wardwood = this.character.wardwoodBatches.reduce((sum, batch) => sum + batch.quantity, 0); return this.character.wardwood }
  addBatch(quantity, acquiredDay, options = {}) { const amount = Math.max(0, Math.trunc(quantity)); if (!amount) return { ok: false, code: 'INVALID_QUANTITY' }; this.character.wardwoodBatches.push({ id: options.id ?? `wardwood-batch-${batchSequence++}`, quantity: amount, acquiredDay, expirationDay: options.expirationDay ?? acquiredDay + WARDWOOD_CONFIG.expirationDays }); this.inventory.add(createItemInstance('wardwood', { quantity: amount })); this.syncTotal(); return { ok: true, quantity: amount } }
  consume(quantity, day) { this.expire(day); this.reconcile(day); let remaining = Math.max(0, Math.trunc(quantity)); if (this.character.wardwood < remaining) return { ok: false, code: 'NO_WARDWOOD' }; this.character.wardwoodBatches.sort((a, b) => a.expirationDay - b.expirationDay || a.acquiredDay - b.acquiredDay); const consumedBatchIds = []; for (const batch of this.character.wardwoodBatches) { if (!remaining) break; const used = Math.min(batch.quantity, remaining); batch.quantity -= used; remaining -= used; consumedBatchIds.push(batch.id) } this.character.wardwoodBatches = this.character.wardwoodBatches.filter(({ quantity: amount }) => amount > 0); this.removeInventoryWardwood(quantity); this.syncTotal(); return { ok: true, quantity, consumedBatchIds } }
  removeInventoryWardwood(quantity) { let remaining = quantity; for (const item of [...this.character.inventory].filter(({ definitionId }) => definitionId === 'wardwood')) { if (!remaining) break; const used = Math.min(item.quantity, remaining); this.inventory.remove(item.instanceId, used); remaining -= used } }
  expire(day) { this.reconcile(day); const expired = this.character.wardwoodBatches.filter((batch) => batch.expirationDay <= day).reduce((sum, batch) => sum + batch.quantity, 0); if (!expired) return { ok: true, expired: 0 }; this.character.wardwoodBatches = this.character.wardwoodBatches.filter((batch) => batch.expirationDay > day); this.removeInventoryWardwood(expired); this.inventory.add(createItemInstance('dead_wardwood', { quantity: expired })); this.character.deadWardwood += expired; this.syncTotal(); return { ok: true, expired, message: `${expired} Wardwood have lost their protective power.` } }
  getSummary(day) { this.reconcile(day); const batches = [...this.character.wardwoodBatches].sort((a, b) => a.expirationDay - b.expirationDay); const first = batches[0]; return { quantity: this.character.wardwood, nextExpiringQuantity: first?.quantity ?? 0, daysUntilExpiration: first ? Math.max(0, first.expirationDay - day) : null, batches } }
  recoverCampfire(random) { if (random() >= WARDWOOD_CONFIG.campfireRecoveryChance) return { ok: true, recovered: 0 }; this.inventory.add(createItemInstance('dead_wardwood', { quantity: 1 })); this.character.deadWardwood += 1; return { ok: true, recovered: 1 } }
}
