import { CONFLICT_POLICY, DURATION_TYPE, EFFECTS_STATUS, EVENT_SCOPE, EVENT_STATE, EVENT_TYPE, EVENT_VISIBILITY, REPEAT_POLICY, SCHEDULE_STATUS, TRIGGER_TYPE, WORLD_EVENT_STATE_VERSION } from './worldEventConstants.js'
const clone = (v) => structuredClone(v ?? {})
export const defineWorldEventTrigger = (d={}) => Object.freeze({ id:d.id, triggerType:d.triggerType??TRIGGER_TYPE.MANUAL, sourceId:null,targetId:null,comparisonMode:'Equals',requiredValue:null,timeWindow:null,worldDay:null,worldTime:null,delayWorldMinutes:0,consumeTrigger:true,oncePerRun:false,enabled:true,tags:[],...d })
export const defineWorldEvent = (d={}) => Object.freeze({ id:d.id,displayName:d.id,description:'',eventType:EVENT_TYPE.SPECIAL,scope:EVENT_SCOPE.GLOBAL,targetRegionIds:[],targetLocationIds:[],targetMerchantIds:[],targetPoiIds:[],triggerDefinitions:[],conditions:[],durationDefinition:{type:DURATION_TYPE.INSTANT,durationWorldMinutes:0},repeatPolicy:REPEAT_POLICY.REPEATABLE,countFailedAsOccurrence:true,cooldownPolicy:null,priority:0,conflictTags:[],conflictPolicy:CONFLICT_POLICY.BLOCK_NEW,requiredInactiveEventIds:[],requiredActiveEventIds:[],requiredCompletedEventIds:[],followUpEventIds:[],failureEventIds:[],effects:[],visibility:EVENT_VISIBILITY.HIDDEN,enabled:true,tags:[],...d,triggerDefinitions:Object.freeze((d.triggerDefinitions??[]).map(defineWorldEventTrigger)) })
export const createWorldEventInstance = (d={}) => ({ instanceId:d.instanceId,eventDefinitionId:d.eventDefinitionId,generatedForRunId:d.generatedForRunId,scope:d.scope??EVENT_SCOPE.GLOBAL,targetRegionIds:[...(d.targetRegionIds??[])],targetLocationIds:[...(d.targetLocationIds??[])],targetEntityIds:[...(d.targetEntityIds??[])],currentState:d.currentState??EVENT_STATE.INACTIVE,triggerSourceType:d.triggerSourceType??null,triggerSourceId:d.triggerSourceId??null,triggerPayload:clone(d.triggerPayload),priority:d.priority??0,createdWorldDay:d.createdWorldDay??1,createdWorldTime:clone(d.createdWorldTime??{hour:6,minute:0}),scheduledWorldDay:d.scheduledWorldDay??null,scheduledWorldTime:d.scheduledWorldTime??null,startedWorldDay:d.startedWorldDay??null,startedWorldTime:d.startedWorldTime??null,expiresWorldDay:d.expiresWorldDay??null,expiresWorldTime:d.expiresWorldTime??null,completedWorldDay:d.completedWorldDay??null,completedWorldTime:d.completedWorldTime??null,failedWorldDay:d.failedWorldDay??null,failedWorldTime:d.failedWorldTime??null,cooldownEndsWorldDay:d.cooldownEndsWorldDay??null,cooldownEndsWorldTime:d.cooldownEndsWorldTime??null,appliedEffectIds:[...(d.appliedEffectIds??[])],effectsStatus:d.effectsStatus??EFFECTS_STATUS.NOT_REQUIRED,rolledValues:clone(d.rolledValues),localFlags:clone(d.localFlags),localCounters:clone(d.localCounters),failureReason:d.failureReason??null,cancellationReason:d.cancellationReason??null,followUpEventInstanceIds:[...(d.followUpEventInstanceIds??[])],lifecycleVersion:d.lifecycleVersion??1,finalized:Boolean(d.finalized)})
export const createScheduledWorldEvent = (d={}) => ({ scheduleId:d.scheduleId,eventDefinitionId:d.eventDefinitionId,targetRegionIds:[...(d.targetRegionIds??[])],targetLocationIds:[...(d.targetLocationIds??[])],targetEntityIds:[...(d.targetEntityIds??[])],sourceTriggerType:d.sourceTriggerType??null,sourceTriggerId:d.sourceTriggerId??null,sourceEventInstanceId:d.sourceEventInstanceId??null,scheduledForWorldDay:d.scheduledForWorldDay,scheduledForWorldTime:clone(d.scheduledForWorldTime),createdWorldDay:d.createdWorldDay,createdWorldTime:clone(d.createdWorldTime),seed:d.seed??null,status:d.status??SCHEDULE_STATUS.SCHEDULED,cancelledReason:null,processed:false,processingSequence:d.processingSequence??0})
export const createWorldEventTriggerSignal = (d={}) => ({ signalId:d.signalId,triggerType:d.triggerType,sourceId:d.sourceId??null,targetId:d.targetId??null,regionId:d.regionId??null,locationId:d.locationId??null,entityId:d.entityId??null,value:d.value??null,worldDay:d.worldDay??1,worldTime:clone(d.worldTime??{hour:6,minute:0}),payload:clone(d.payload),sequence:d.sequence??0,randomSource:d.randomSource })
export const createWorldState = (d={}) => ({ version:WORLD_EVENT_STATE_VERSION,activeWorldEventIds:[],scheduledWorldEventIds:[],pendingWorldEventIds:[],completedWorldEventIds:[],failedWorldEventIds:[],cancelledWorldEventIds:[],expiredWorldEventIds:[],worldFlags:{},worldCounters:{},eventCooldowns:{},eventOccurrenceCounters:{},eventHistory:[],globalModifiers:{},lastProcessedWorldDay:1,lastProcessedWorldTime:{hour:6,minute:0},processingSequenceCounter:0,eventSequenceCounter:0,consumedTriggerKeys:[],eventInstances:[],scheduledEvents:[],...clone(d) })
export const createRegionState = (id,base={},d={}) => ({ version:WORLD_EVENT_STATE_VERSION,regionId:id,threatLevel:base.threatLevel??0,safetyLevel:base.safetyLevel??0,activeFlags:[...(base.flags??[])],localCounters:{},activeEventIds:[],completedEventIds:[],failedEventIds:[],disabledEventIds:[],scheduledEventIds:[],activeEncounterTableModifiers:{},activePoiModifiers:{},merchantStateModifiers:{},roadStates:clone(base.roadStates),locationStates:{},temporaryModifiers:{},lastUpdatedWorldDay:1,lastUpdatedWorldTime:{hour:6,minute:0},...clone(d) })

