import { ABSOLUTE_SKILL_CAP, getNextSkillRank, getSkillRankDefinition, NORMAL_SKILL_CAP } from './skillRankDefinitions.js'
import { getSkillProgressionDefinition, PRACTICE_ANTI_GRIND_HOOKS } from './skillProgressionDefinitions.js'

export const PRACTICE_CONFIG = Object.freeze({ antiGrindHooks: PRACTICE_ANTI_GRIND_HOOKS })
export function createProficiencyProgress(rankName = 'Untrained') { const rank = getSkillRankDefinition(rankName); return { baseValue: rank.minimumSkill, currentRank: rank.name, currentRankCap: rank.maximumSkill, maximumCap: NORMAL_SKILL_CAP } }
export function synchronizeLegacyProficiency(character, proficiency) { const legacy = character.proficiencies?.[proficiency] ?? 'Untrained'; const progress = character.proficiencySkills?.[proficiency]; if (!progress || progress.currentRank !== legacy) character.proficiencySkills[proficiency] = createProficiencyProgress(legacy); return character.proficiencySkills[proficiency] }
export function normalizeProficiencyProgress(value, legacyRank = 'Untrained') { const fallback = createProficiencyProgress(legacyRank); if (!value || typeof value !== 'object') return fallback; const maximumCap = Math.min(ABSOLUTE_SKILL_CAP, Math.max(NORMAL_SKILL_CAP, Math.trunc(value.maximumCap ?? NORMAL_SKILL_CAP))); const currentRank = getSkillRankDefinition(value.currentRank).name; const rankCap = Math.min(maximumCap, Math.max(getSkillRankDefinition(currentRank).minimumSkill, Math.trunc(value.currentRankCap ?? getSkillRankDefinition(currentRank).maximumSkill))); const baseValue = Number(value.baseValue ?? fallback.baseValue); return { baseValue: Math.min(rankCap, Math.max(0, Number.isFinite(baseValue) ? baseValue : fallback.baseValue)), currentRank, currentRankCap: rankCap, maximumCap } }
export function calculateProficiency(character, proficiency, { equipmentEffects = [], temporaryEffects = [] } = {}) { const progress = normalizeProficiencyProgress(synchronizeLegacyProficiency(character, proficiency), character.proficiencies?.[proficiency]); const bonusValue = [...equipmentEffects, ...temporaryEffects].filter((effect) => effect.type === 'modify_proficiency' && effect.proficiency === proficiency).reduce((sum, effect) => sum + (effect.amount ?? 0), 0); return { ...progress, bonusValue, effectiveValue: Math.max(0, progress.baseValue + bonusValue) } }
export function gainBaseProficiency(character, proficiency, amount, source = 'unknown') { const progress = synchronizeLegacyProficiency(character, proficiency); if (!progress) return { ok: false, code: 'PROFICIENCY_NOT_FOUND' }; const numericAmount = Number(amount); const gain = Number.isFinite(numericAmount) ? Math.max(0, numericAmount) : 0; if (!gain) return { ok: false, code: 'INVALID_PROFICIENCY_GAIN' }; if (progress.baseValue + gain > Math.min(progress.currentRankCap, progress.maximumCap)) return { ok: false, code: 'CURRENT_RANK_CAP_REACHED', message: `You must learn the next ${proficiency} rank before progressing further.` }; progress.baseValue = Math.round((progress.baseValue + gain) * 100) / 100; return { ok: true, gained: gain, baseValue: progress.baseValue, source } }
export function attemptPracticeGain(character, proficiency, { successful, random, antiGrindContext = {}, antiGrindHooks = {} } = {}) { if (!successful) return { ok: false, code: 'ACTION_NOT_SUCCESSFUL' }; if (typeof random !== 'function') return { ok: false, code: 'RANDOM_SOURCE_REQUIRED' }; const progress = synchronizeLegacyProficiency(character, proficiency); const definition = getSkillProgressionDefinition(progress.baseValue); if (!definition) return { ok: false, code: 'MAXIMUM_SKILL_CAP_REACHED' }; if (progress.baseValue + definition.skillGain > Math.min(progress.currentRankCap, progress.maximumCap, ABSOLUTE_SKILL_CAP)) return { ok: false, code: 'CURRENT_RANK_CAP_REACHED' }; const modifiers = PRACTICE_ANTI_GRIND_HOOKS.map((hook) => typeof antiGrindHooks[hook] === 'function' ? antiGrindHooks[hook](antiGrindContext) : 1); const chance = Math.max(0, Math.min(1, definition.chance * modifiers.reduce((total, modifier) => total * Math.max(0, Number(modifier) || 0), 1))); if (random() >= chance) return { ok: false, code: 'PRACTICE_GAIN_NOT_ROLLED', chance, antiGrindContext }; return { ...gainBaseProficiency(character, proficiency, definition.skillGain, 'practice'), chance, progressionDefinition: definition } }
export function unlockNextProficiencyRank(character, proficiency) { const progress = synchronizeLegacyProficiency(character, proficiency); const next = getNextSkillRank(progress.currentRank); if (!next || progress.currentRankCap >= progress.maximumCap) return { ok: false, code: 'MAXIMUM_RANK_REACHED' }; progress.currentRank = next.name; progress.currentRankCap = Math.min(next.maximumSkill, progress.maximumCap); character.proficiencies[proficiency] = next.name; return { ok: true, rank: next.name, currentRankCap: progress.currentRankCap, baseValue: progress.baseValue } }
export function increaseMaximumProficiencyCap(character, proficiency, amount) { const progress = synchronizeLegacyProficiency(character, proficiency); const next = Math.min(ABSOLUTE_SKILL_CAP, progress.maximumCap + Math.max(0, Math.trunc(amount))); const increased = next - progress.maximumCap; progress.maximumCap = next; if (progress.currentRank === 'Grandmaster') progress.currentRankCap = next; return { ok: true, increased, maximumCap: next } }
export function canApplySkillBook(character, proficiency, amount) { const progress = synchronizeLegacyProficiency(character, proficiency); return progress.baseValue + amount <= progress.currentRankCap ? { ok: true } : { ok: false, code: 'NEXT_RANK_REQUIRED', message: `You must learn the next ${proficiency} rank before using this manual.` } }
export function createProficiencyTooltipModel(name, calculated) { return { name, currentRank: calculated.currentRank, baseValue: calculated.baseValue, bonusValue: calculated.bonusValue, effectiveValue: calculated.effectiveValue, currentRankCap: calculated.currentRankCap, maximumCap: calculated.maximumCap } }
