import { ENCOUNTER_PHASE, PREPARATION_STATE } from './encounterConstants.js'
import { transitionEncounterPhase } from './encounterPhaseService.js'
const modifiers = Object.freeze({ [PREPARATION_STATE.SURPRISED]: { playerInitiativeModifier: -2, enemyInitiativeModifier: 2, initiator: 'enemy' }, [PREPARATION_STATE.PREPARED]: { playerInitiativeModifier: 2, enemyInitiativeModifier: 0, initiator: 'player' }, [PREPARATION_STATE.ALERT]: { playerInitiativeModifier: 0, enemyInitiativeModifier: 0, initiator: 'player' }, [PREPARATION_STATE.NEUTRAL]: { playerInitiativeModifier: 0, enemyInitiativeModifier: 0, initiator: 'player' } })
export class EncounterCombatService {
  constructor({ database, stateRepository, startCombat, resolutionService }) { this.database = database; this.stateRepository = stateRepository; this.startCombat = startCombat; this.resolution = resolutionService }
  buildContext(instance, encounter) { const preparation = modifiers[instance.preparationState] ?? modifiers.Neutral; return { encounterInstanceId: instance.instanceId, encounterDefinitionId: encounter.id, combatDefinitionId: encounter.combatDefinitionId, preparationState: instance.preparationState, detected: instance.detectionResult?.detected ?? true, surpriseMode: preparation.initiator === 'enemy' ? 'EnemyAmbushes' : 'Normal', playerInitiativeModifier: preparation.playerInitiativeModifier, enemyInitiativeModifier: preparation.enemyInitiativeModifier, allowEscape: true, sourceRegionId: instance.regionId, sourceLocationId: instance.locationId, sourceWorldPosition: { ...instance.worldPosition }, encounterTags: [...encounter.tags], worldDay: instance.worldDay, worldTime: instance.worldTime, initiator: preparation.initiator } }
  start(instanceId) { const instance = this.stateRepository.instances.get(instanceId); const encounter = instance && this.database.getEncounter(instance.encounterDefinitionId); if (!instance || !encounter?.combatDefinitionId) return { ok: false, code: 'COMBAT_DEFINITION_NOT_FOUND' }; if (instance.pendingCombatId) return { ok: false, code: 'ENCOUNTER_COMBAT_ALREADY_PENDING' }; if (![ENCOUNTER_PHASE.CHOICE_PENDING, ENCOUNTER_PHASE.PRESENTATION].includes(instance.currentPhase)) return { ok: false, code: 'ENCOUNTER_INVALID_PHASE' }; const combatContext = this.buildContext(instance, encounter); const started = this.startCombat(combatContext); if (!started?.ok) return { ok: false, code: started?.code ?? started?.error ?? 'ENCOUNTER_COMBAT_START_FAILED' }; transitionEncounterPhase(instance, ENCOUNTER_PHASE.COMBAT_PENDING); instance.pendingCombatId = started.combatId ?? started.combat?.id; instance.pendingCombatContext = combatContext; instance.pendingResolution = { ...(instance.pendingResolution ?? {}), combatContext, combatResult: null }; this.stateRepository.instances.save(instance); return { ok: true, code: 'ENCOUNTER_COMBAT_STARTED', combatId: instance.pendingCombatId, combatContext, instance } }
  resolveEncounterCombat(instanceId, combatId, result, context = {}) { const instance = this.stateRepository.instances.get(instanceId); if (!instance || instance.pendingCombatId !== combatId) return { ok: false, code: 'ENCOUNTER_COMBAT_ID_MISMATCH' }; if (instance.currentPhase !== ENCOUNTER_PHASE.COMBAT_PENDING) return { ok: false, code: 'ENCOUNTER_INVALID_PHASE' }; instance.pendingCombatId = null; instance.pendingResolution.combatResult = result; this.stateRepository.instances.save(instance); const resolutionType = result === 'Victory' ? 'CombatVictory' : result === 'Defeat' ? 'CombatDefeat' : result === 'Escaped' ? 'CombatEscape' : 'Cancelled'; return this.resolution.begin(instanceId, resolutionType, result === 'Victory' ? { title: 'Victory', rewards: [] } : { title: result, rewards: [] }, context) }
}
