import { CHOICE_ACTION_TYPE, DETECTION_MODE, PREPARATION_STATE } from './encounterConstants.js'
const freezeList = (items = []) => Object.freeze(items.map((item) => Object.freeze({ ...item })))
export const defineDetection = (data) => Object.freeze({ detectionMode: DETECTION_MODE.NONE, perceptionDifficulty: 6, scoutingDifficulty: null, luckDifficulty: 6, valueSource: 'FinalStat', comparisonMode: 'ValuePlusRoll', randomRange: 10, allowEquipmentBonus: true, allowTemporaryBonus: true, allowRepeatedDetection: false, detectedPreparationState: PREPARATION_STATE.ALERT, undetectedPreparationState: PREPARATION_STATE.NEUTRAL, criticalSuccessPreparationState: PREPARATION_STATE.PREPARED, criticalFailurePreparationState: PREPARATION_STATE.SURPRISED, visibleOnFailure: true, revealEncounterIdentityOnDetection: true, revealEnemyCountOnDetection: false, revealEncounterTypeOnDetection: true, modifiers: freezeList(), tags: Object.freeze([]), ...data })
export const defineChoice = (data) => Object.freeze({ displayName: data.id, description: '', visibilityRequirements: freezeList(), availabilityRequirements: freezeList(), costs: freezeList(), checks: freezeList(), actionType: CHOICE_ACTION_TYPE.CUSTOM, successResolutionId: null, failureResolutionId: null, criticalSuccessResolutionId: null, criticalFailureResolutionId: null, nextPhase: null, startCombat: false, combatPreparationOverride: null, isRepeatable: false, maximumUses: 1, requiresConfirmation: false, tags: Object.freeze([]), sortOrder: 0, ...data, visibilityRequirements: freezeList(data.visibilityRequirements), availabilityRequirements: freezeList(data.availabilityRequirements), costs: freezeList(data.costs), checks: freezeList(data.checks), tags: Object.freeze([...(data.tags ?? [])]) })
export const defineChoiceSet = (data) => Object.freeze({ id: data.id, choiceIds: Object.freeze([...(data.choiceIds ?? [])]), defaultChoiceId: null, allowLeave: true, autoSelectWhenSingleChoice: false, tags: Object.freeze([...(data.tags ?? [])]), ...data })

export const ENCOUNTER_DETECTION_DEFINITIONS = Object.freeze({
  automatic: defineDetection({ id: 'automatic', detectionMode: DETECTION_MODE.AUTOMATIC, detectedPreparationState: PREPARATION_STATE.NEUTRAL }),
  road_perception: defineDetection({ id: 'road_perception', detectionMode: DETECTION_MODE.PERCEPTION, perceptionDifficulty: 7 }),
  wilderness_perception: defineDetection({ id: 'wilderness_perception', detectionMode: DETECTION_MODE.PERCEPTION, perceptionDifficulty: 8 }),
  bandit_ambush: defineDetection({ id: 'bandit_ambush', detectionMode: DETECTION_MODE.AMBUSH, perceptionDifficulty: 9, undetectedPreparationState: PREPARATION_STATE.SURPRISED, criticalFailurePreparationState: PREPARATION_STATE.SURPRISED, revealEnemyCountOnDetection: true }),
})

export const ENCOUNTER_AMBUSH_DEFINITIONS = Object.freeze({ bandit_ambush: Object.freeze({ id: 'bandit_ambush', isAmbush: true, detectionDefinitionId: 'bandit_ambush', detectedChoiceSetId: 'bandit_detected', undetectedChoiceSetId: 'combat_undetected', criticalDetectionChoiceSetId: 'bandit_detected', surpriseMode: 'EnemyAmbushes', enemyInitiativeModifier: 2, playerInitiativeModifier: -2, preventPreCombatEscapeWhenUndetected: false, allowCounterAmbush: true, concealEnemyIdentity: true, revealTextDetected: 'You notice movement among the trees before the road narrows.', revealTextUndetected: 'Bandits emerge from cover at close range.', tags: Object.freeze(['bandit']) }) })

export const ENCOUNTER_CHOICES = Object.freeze(Object.fromEntries([
  defineChoice({ id: 'fight', displayName: 'Fight', actionType: CHOICE_ACTION_TYPE.FIGHT, startCombat: true, isRepeatable: false }),
  defineChoice({ id: 'avoid', displayName: 'Avoid the encounter', actionType: CHOICE_ACTION_TYPE.AVOID, checks: [{ statId: 'perception', difficulty: 7, randomRange: 10 }], successResolutionId: 'avoided', failureResolutionId: 'fight_after_failure' }),
  defineChoice({ id: 'flee', displayName: 'Attempt to flee', actionType: CHOICE_ACTION_TYPE.FLEE, checks: [{ statId: 'agility', difficulty: 8, randomRange: 10 }], successResolutionId: 'escaped', failureResolutionId: 'fight_surprised' }),
  defineChoice({ id: 'prepare', displayName: 'Prepare an attack', actionType: CHOICE_ACTION_TYPE.PREPARE, costs: [{ type: 'WorldTime', quantity: 10 }], successResolutionId: 'prepared', maximumUses: 1 }),
  defineChoice({ id: 'approach', displayName: 'Approach openly', actionType: CHOICE_ACTION_TYPE.APPROACH, startCombat: true }),
  defineChoice({ id: 'help_traveler', displayName: 'Help', actionType: CHOICE_ACTION_TYPE.HELP, checks: [{ proficiencyId: 'Healing', difficulty: 6, randomRange: 10 }], successResolutionId: 'traveler_helped', failureResolutionId: 'traveler_help_failed' }),
  defineChoice({ id: 'give_bandage', displayName: 'Give Bandage', actionType: CHOICE_ACTION_TYPE.HELP, costs: [{ type: 'Item', itemDefinitionId: 'bandage', quantity: 1 }], successResolutionId: 'traveler_bandaged' }),
  defineChoice({ id: 'inspect_supplies', displayName: 'Inspect', actionType: CHOICE_ACTION_TYPE.INVESTIGATE, checks: [{ statId: 'perception', difficulty: 6, randomRange: 10 }], successResolutionId: 'supplies_found', failureResolutionId: 'supplies_empty' }),
  defineChoice({ id: 'take_supplies', displayName: 'Take', actionType: CHOICE_ACTION_TYPE.TAKE, successResolutionId: 'supplies_found' }),
  defineChoice({ id: 'investigate_lights', displayName: 'Investigate', actionType: CHOICE_ACTION_TYPE.INVESTIGATE, successResolutionId: 'lights_knowledge' }),
  defineChoice({ id: 'wait_lights', displayName: 'Wait', actionType: CHOICE_ACTION_TYPE.WAIT, costs: [{ type: 'WorldTime', quantity: 20 }], successResolutionId: 'lights_fade' }),
  defineChoice({ id: 'leave', displayName: 'Leave', actionType: CHOICE_ACTION_TYPE.LEAVE, successResolutionId: 'left' }),
].map((choice) => [choice.id, choice])))

export const ENCOUNTER_CHOICE_SETS = Object.freeze(Object.fromEntries([
  defineChoiceSet({ id: 'combat_detected', choiceIds: ['avoid', 'prepare', 'approach', 'fight'] }), defineChoiceSet({ id: 'combat_undetected', choiceIds: ['flee', 'fight'] }), defineChoiceSet({ id: 'bandit_detected', choiceIds: ['avoid', 'prepare', 'approach', 'fight'] }),
  defineChoiceSet({ id: 'traveler', choiceIds: ['help_traveler', 'give_bandage', 'leave'] }), defineChoiceSet({ id: 'supplies', choiceIds: ['inspect_supplies', 'take_supplies', 'leave'] }), defineChoiceSet({ id: 'lights', choiceIds: ['investigate_lights', 'avoid', 'wait_lights'] }),
].map((set) => [set.id, set])))

export const ENCOUNTER_NONCOMBAT_OUTCOMES = Object.freeze({
  traveler_helped: { id: 'traveler_helped', title: 'Traveler helped', rewards: [{ type: 'grant_gold', amount: 5 }], finalResolutionType: 'NonCombatSuccess', markResolved: true }, traveler_help_failed: { id: 'traveler_help_failed', title: 'You could not help', rewards: [], finalResolutionType: 'NonCombatFailure', markResolved: true }, traveler_bandaged: { id: 'traveler_bandaged', title: 'Bandage given', rewards: [{ type: 'grant_gold', amount: 3 }], finalResolutionType: 'NonCombatSuccess', markResolved: true }, supplies_found: { id: 'supplies_found', title: 'Useful supplies', rewards: [], randomRewardTableIds: [], finalResolutionType: 'NonCombatSuccess', markResolved: true }, supplies_empty: { id: 'supplies_empty', title: 'Nothing useful', rewards: [], finalResolutionType: 'NonCombatFailure', markResolved: true }, lights_knowledge: { id: 'lights_knowledge', title: 'Strange lights understood', rewards: [{ type: 'grant_knowledge', knowledgeId: 'local_threat' }], revealPoiTargets: [{ poiDefinitionId: 'old_shrine' }], finalResolutionType: 'NonCombatSuccess', markResolved: true }, lights_fade: { id: 'lights_fade', title: 'The lights fade', rewards: [], finalResolutionType: 'NonCombatSuccess', markResolved: true }, left: { id: 'left', title: 'You leave', rewards: [], finalResolutionType: 'Avoided', markResolved: true },
})

export const ENCOUNTER_INTERACTION_CONFIGS = Object.freeze({
  bandit_ambush: { detectionDefinitionId: 'bandit_ambush', ambushDefinitionId: 'bandit_ambush', detectedChoiceSetId: 'bandit_detected', undetectedChoiceSetId: 'combat_undetected' }, hungry_wolves: { detectionDefinitionId: 'road_perception', detectedChoiceSetId: 'combat_detected', undetectedChoiceSetId: 'combat_undetected' }, lone_wolf: { detectionDefinitionId: 'road_perception', detectedChoiceSetId: 'combat_detected', undetectedChoiceSetId: 'combat_undetected' }, boar: { detectionDefinitionId: 'wilderness_perception', detectedChoiceSetId: 'combat_detected', undetectedChoiceSetId: 'combat_undetected' }, wolf_pair: { detectionDefinitionId: 'wilderness_perception', detectedChoiceSetId: 'combat_detected', undetectedChoiceSetId: 'combat_undetected' }, predator_pack: { detectionDefinitionId: 'wilderness_perception', detectedChoiceSetId: 'combat_detected', undetectedChoiceSetId: 'combat_undetected' }, hidden_creature: { detectionDefinitionId: 'bandit_ambush', detectedChoiceSetId: 'combat_detected', undetectedChoiceSetId: 'combat_undetected' }, injured_traveler: { detectionDefinitionId: 'automatic', detectedChoiceSetId: 'traveler', undetectedChoiceSetId: 'traveler' }, abandoned_supplies: { detectionDefinitionId: 'automatic', detectedChoiceSetId: 'supplies', undetectedChoiceSetId: 'supplies' }, strange_lights: { detectionDefinitionId: 'automatic', detectedChoiceSetId: 'lights', undetectedChoiceSetId: 'lights' },
})
