import { ENCOUNTER_PHASE } from './encounterConstants.js'
import { createEncounterPresentationModel } from './encounterPresentationService.js'
import { getEncounterUiMessage } from './encounterUiResults.js'

export class EncounterPresentationCoordinator {
  constructor({ database, stateRepository, detectionService, choiceService, resolutionService, availabilityResolver, contextFactory, notificationService = null }) { Object.assign(this, { database, stateRepository, detectionService, choiceService, resolutionService, availabilityResolver, contextFactory, notificationService }); this.activeInstanceId = null; this.suspended = false; this.requestId = null; this.lastResult = null; this.lastRecoveryResult = null }
  get activeInstance() { return this.activeInstanceId ? this.stateRepository.instances.get(this.activeInstanceId) : null }
  notify(result) { this.lastResult = result; this.notificationService?.notify(getEncounterUiMessage(result), { code: result?.code, source: 'encounter' }); return result }
  openPending() { const id = this.stateRepository.state.travelState.pendingEncounterInstanceId; if (!id) return this.notify({ ok: false, code: 'ENCOUNTER_NOT_PENDING' }); if (this.activeInstanceId && this.activeInstanceId !== id) return this.notify({ ok: false, code: 'ENCOUNTER_OVERLAY_ALREADY_OPEN' }); this.activeInstanceId = id; const instance = this.activeInstance; if (instance.currentPhase === ENCOUNTER_PHASE.PENDING_TRIGGER) return this.notify(this.detectionService.activatePendingEncounter(id, this.contextFactory())); return this.notify({ ok: true, code: 'ENCOUNTER_RECOVERED', instance }) }
  recoverPendingEncounterState() { const id = this.stateRepository.state.travelState.pendingEncounterInstanceId; if (!id) { this.activeInstanceId = null; return this.lastRecoveryResult = { ok: true, code: 'NO_PENDING_ENCOUNTER', panel: null } } this.activeInstanceId = id; const instance = this.activeInstance; if (!instance) return this.lastRecoveryResult = { ok: false, code: 'ENCOUNTER_NOT_FOUND', panel: 'error' }; let result; if (instance.currentPhase === ENCOUNTER_PHASE.PENDING_TRIGGER && !instance.detectionResult) result = this.openPending(); else result = { ok: true, code: 'ENCOUNTER_RECOVERED', instance }; const panel = instance.pendingLootRewardId ? 'loot' : instance.pendingCombatId ? 'combat' : instance.resolved ? 'resolution' : instance.currentPhase === ENCOUNTER_PHASE.CHOICE_PENDING ? 'choices' : 'presentation'; this.suspended = panel === 'combat' || panel === 'loot'; return this.lastRecoveryResult = { ...result, panel, skippedDuplicateDetection: Boolean(instance.detectionResult), skippedDuplicateCombat: Boolean(instance.pendingCombatId), skippedDuplicateRewards: Boolean(instance.pendingResolution?.rewardsGenerated) } }
  presentation() { const instance = this.activeInstance; return instance ? createEncounterPresentationModel(instance, this.database.getEncounter(instance.encounterDefinitionId), this.availabilityResolver, this.contextFactory()) : null }
  previewChoice(id) { const instance = this.activeInstance; return instance ? this.choiceService.preview(instance.instanceId, id, this.contextFactory()) : { ok: false, code: 'ENCOUNTER_NOT_FOUND' } }
  executeChoice(id) { if (this.requestId) return this.notify({ ok: false, code: 'ENCOUNTER_COMMAND_PENDING' }); const instance = this.activeInstance; if (!instance) return this.notify({ ok: false, code: 'ENCOUNTER_NOT_FOUND' }); this.requestId = `${instance.instanceId}:${id}`; try { const result = this.choiceService.execute(instance.instanceId, id, this.contextFactory()); this.suspended = result?.code === 'ENCOUNTER_COMBAT_STARTED' || result?.code === 'ENCOUNTER_LOOT_PENDING'; return this.notify(result) } finally { this.requestId = null } }
  resume() { this.suspended = false; const instance = this.activeInstance; if (instance?.resolved) return this.lastRecoveryResult = { ok: true, code: 'ENCOUNTER_RESOLUTION_READY', panel: 'resolution', instance }; return this.recoverPendingEncounterState() }
  closeFinalized() { const instance = this.activeInstance; if (!instance?.resolved || this.stateRepository.state.travelState.movementBlockedByEncounter) return this.notify({ ok: false, code: 'ENCOUNTER_RESOLUTION_PENDING' }); this.activeInstanceId = null; this.suspended = false; return this.notify({ ok: true, code: 'ENCOUNTER_OVERLAY_CLOSED' }) }
  debugView() { const instance = this.activeInstance; if (!instance) return null; const definition = this.database.getEncounter(instance.encounterDefinitionId); const presentation = this.presentation(); return { definition, instance, detection: instance.detectionResult, choices: presentation?.choices, combat: instance.pendingCombatContext, loot: instance.pendingResolution?.generatedLootReward, resolution: instance.pendingResolution, recovery: this.lastRecoveryResult, lastResult: this.lastResult, movementLocked: this.stateRepository.state.travelState.movementBlockedByEncounter } }
}
