import { CHOICE_ACTION_TYPE, CHOICE_STATUS, ENCOUNTER_PHASE, PREPARATION_STATE } from './encounterConstants.js'
import { ENCOUNTER_CHOICES, ENCOUNTER_CHOICE_SETS } from './encounterInteractionDefinitions.js'
import { evaluateRequirement } from '../npc/trainingRequirementSystem.js'
import { PoiActionCostService } from '../poi/poiActionCostService.js'
import { createSeededRandom } from './encounterSelectionService.js'

const requirementMet = (requirement, context) => { if (requirement.type === 'world_flag') return context.worldFlags?.[requirement.flag] === (requirement.value ?? true); if (requirement.type === 'region_flag') return context.regionFlags?.[requirement.flag] === (requirement.value ?? true); return context.characterState ? evaluateRequirement(context.characterState, requirement).met : false }
export class EncounterChoiceAvailabilityResolver {
  constructor({ choices = ENCOUNTER_CHOICES, choiceSets = ENCOUNTER_CHOICE_SETS, costService = new PoiActionCostService() } = {}) { this.choices = choices; this.choiceSets = choiceSets; this.costs = costService }
  preview(instance, choiceId, context) { const set = this.choiceSets[instance.currentChoiceSetId]; const choice = this.choices[choiceId]; if (!set || !choice || !set.choiceIds.includes(choiceId)) return { ok: false, status: CHOICE_STATUS.INVALID, code: 'CHOICE_NOT_FOUND' }; if (!choice.visibilityRequirements.every((requirement) => requirementMet(requirement, context))) return { ok: true, visible: false, available: false, status: CHOICE_STATUS.HIDDEN, choice }; const uses = instance.choiceCounters[choice.id] ?? 0; if (choice.maximumUses !== null && uses >= choice.maximumUses) return { ok: true, visible: true, available: false, status: CHOICE_STATUS.EXHAUSTED, choice, uses }; const requirements = choice.availabilityRequirements.map((requirement) => ({ requirement, met: requirementMet(requirement, context) })); const costPreview = this.costs.preview(choice.costs, { ...context, character: context.characterState }); const available = requirements.every(({ met }) => met) && costPreview.canPayAllCosts; return { ok: true, visible: true, available, status: available ? CHOICE_STATUS.AVAILABLE : CHOICE_STATUS.LOCKED, choice, requirements, costPreview, uses } }
  list(instance, context) { const set = this.choiceSets[instance.currentChoiceSetId]; return (set?.choiceIds ?? []).map((id) => this.preview(instance, id, context)).filter(({ visible }) => visible) }
}

export class EncounterChoiceService {
  constructor({ stateRepository, availabilityResolver = new EncounterChoiceAvailabilityResolver(), combatService, nonCombatService, resolutionService, runSeed = '' }) { this.stateRepository = stateRepository; this.availability = availabilityResolver; this.combat = combatService; this.nonCombat = nonCombatService; this.resolution = resolutionService; this.runSeed = runSeed }
  preview(instanceId, choiceId, context = {}) { const instance = this.stateRepository.instances.get(instanceId); if (!instance) return { ok: false, code: 'ENCOUNTER_NOT_FOUND' }; if (instance.currentPhase !== ENCOUNTER_PHASE.CHOICE_PENDING) return { ok: false, code: 'ENCOUNTER_INVALID_PHASE' }; return this.availability.preview(instance, choiceId, context) }
  resolveChecks(choice, instance, context) { if (!choice.checks.length) return { success: true, critical: false, results: [] }; const random = context.randomSource ?? createSeededRandom(`${this.runSeed}:${instance.seed}:choice:${choice.id}:${instance.choiceCounters[choice.id] ?? 0}`); const results = choice.checks.map((check) => { const value = check.proficiencyId ? (context.characterStats?.proficiencyValues?.[check.proficiencyId]?.effectiveValue ?? context.characterState?.proficiencySkills?.[check.proficiencyId]?.effectiveValue ?? 0) : (context.characterStats?.finalStats?.[check.statId] ?? context.characterState?.stats?.[check.statId] ?? 0); const roll = Math.floor(random() * (check.randomRange ?? 10)) + 1; return { ...check, value, roll, total: value + roll, success: value + roll >= check.difficulty, critical: roll === (check.randomRange ?? 10) || roll === 1 } }); return { success: results.every(({ success }) => success), critical: results.some(({ critical }) => critical), results } }
  execute(instanceId, choiceId, context = {}) { const instance = this.stateRepository.instances.get(instanceId); if (!instance || instance.currentPhase !== ENCOUNTER_PHASE.CHOICE_PENDING) return { ok: false, code: 'ENCOUNTER_INVALID_PHASE' }; const preview = this.availability.preview(instance, choiceId, context); if (!preview.ok || !preview.visible) return { ok: false, code: 'CHOICE_HIDDEN', preview }; if (!preview.available) return { ok: false, code: preview.status === CHOICE_STATUS.EXHAUSTED ? 'CHOICE_EXHAUSTED' : 'CHOICE_LOCKED', preview }; const paid = preview.choice.costs.length ? this.availability.costs.pay(preview.choice.costs, { ...context, character: context.characterState }) : { ok: true, snapshot: null }; if (!paid.ok) return { ok: false, code: 'CHOICE_COST_PAYMENT_FAILED', preview }; const check = this.resolveChecks(preview.choice, instance, context); instance.choiceCounters[choiceId] = (instance.choiceCounters[choiceId] ?? 0) + 1; instance.selectedChoiceId = choiceId; instance.lastChoiceResult = { success: check.success, critical: check.critical, checks: check.results }; this.stateRepository.instances.save(instance); let result
    if (preview.choice.actionType === CHOICE_ACTION_TYPE.PREPARE && check.success) { instance.preparationState = PREPARATION_STATE.PREPARED; this.stateRepository.instances.save(instance); result = { ok: true, code: 'CHOICE_CHECK_SUCCESS', preparationState: instance.preparationState, instance } }
    else if (preview.choice.startCombat || (!check.success && ['fight_after_failure', 'fight_surprised'].includes(preview.choice.failureResolutionId))) { if (!check.success && preview.choice.failureResolutionId === 'fight_surprised') instance.preparationState = PREPARATION_STATE.SURPRISED; this.stateRepository.instances.save(instance); result = this.combat.start(instanceId) }
    else if (check.success && preview.choice.successResolutionId === 'avoided') result = this.resolution.begin(instanceId, 'Avoided', { title: 'Encounter avoided', rewards: [] }, context)
    else if (check.success && preview.choice.successResolutionId === 'escaped') result = this.resolution.begin(instanceId, 'PreCombatEscape', { title: 'You escaped', rewards: [] }, context)
    else { const outcomeId = check.success ? preview.choice.successResolutionId : preview.choice.failureResolutionId; result = outcomeId ? this.nonCombat.resolve(instanceId, outcomeId, context) : { ok: true, code: check.success ? 'CHOICE_CHECK_SUCCESS' : 'CHOICE_CHECK_FAILURE', instance } }
    if (!result?.ok) { if (paid.snapshot) this.availability.costs.rollback(paid.snapshot, { ...context, character: context.characterState }); instance.choiceCounters[choiceId] -= 1; instance.selectedChoiceId = null; instance.lastChoiceResult = null; this.stateRepository.instances.save(instance) } return { ...result, choice: preview.choice, checkResult: check }
  }
}
