import { ENCOUNTER_PHASE, ENCOUNTER_STATE_VERSION } from './encounterConstants.js'
import { createEncounterTravelState, isValidEncounterTravelState, normalizeEncounterTravelState } from './encounterTravelModels.js'
import { createEncounterInstance } from './encounterModels.js'

export const createEmptyEncounterRunState = () => ({ version: ENCOUNTER_STATE_VERSION, encounterInstances: [], historyRecords: [], occurrenceCountersByEncounterId: {}, occurrenceCountersByTag: {}, lastEncounterId: null, lastEncounterWorldDay: null, lastEncounterWorldTime: null, recentEncounterIds: [], recentEncounterTags: [], cooldowns: {}, uniqueEncounterIdsUsed: [], disabledEncounterIds: [], forcedNextEncounterId: null, forcedNextEncounterTableId: null, encounterSequenceCounter: 0, triggeredEncounterCount: 0, travelState: createEncounterTravelState() })
export function createInitialEncounterRunState(seed = '', runId = '') { const state = createEmptyEncounterRunState(); const hash = [...`${seed}:${runId}:travel-threshold`].reduce((value, character) => Math.imul(value ^ character.charCodeAt(0), 16777619) >>> 0, 2166136261); state.travelState.encounterMeterThreshold = 11 + hash % 5; return state }
export function normalizeEncounterRunState(state) { const base = createEmptyEncounterRunState(); return { ...base, ...(state ?? {}), encounterInstances: (Array.isArray(state?.encounterInstances) ? state.encounterInstances : []).map((instance) => createEncounterInstance(structuredClone(instance))), historyRecords: structuredClone(Array.isArray(state?.historyRecords) ? state.historyRecords : []), occurrenceCountersByEncounterId: { ...(state?.occurrenceCountersByEncounterId ?? {}) }, occurrenceCountersByTag: { ...(state?.occurrenceCountersByTag ?? {}) }, recentEncounterIds: [...(state?.recentEncounterIds ?? [])].slice(-20), recentEncounterTags: [...(state?.recentEncounterTags ?? [])].slice(-40), cooldowns: structuredClone(state?.cooldowns ?? {}), uniqueEncounterIdsUsed: [...new Set(state?.uniqueEncounterIdsUsed ?? [])], disabledEncounterIds: [...new Set(state?.disabledEncounterIds ?? [])], travelState: normalizeEncounterTravelState(state?.travelState) } }
export const isValidEncounterRunState = (state) => Boolean(state && state.version === ENCOUNTER_STATE_VERSION && Array.isArray(state.encounterInstances) && Array.isArray(state.historyRecords) && typeof state.occurrenceCountersByEncounterId === 'object' && typeof state.cooldowns === 'object' && Number.isInteger(state.encounterSequenceCounter) && isValidEncounterTravelState(state.travelState))

export class EncounterRepository {
  constructor(state = createEmptyEncounterRunState()) { this.state = state }
  get(id) { return this.state.encounterInstances.find(({ instanceId }) => instanceId === id) ?? null }
  getAll() { return this.state.encounterInstances }
  save(instance) { const index = this.state.encounterInstances.findIndex(({ instanceId }) => instanceId === instance.instanceId); const copy = structuredClone(instance); if (index < 0) this.state.encounterInstances.push(copy); else this.state.encounterInstances[index] = copy; return copy }
  delete(id) { const index = this.state.encounterInstances.findIndex(({ instanceId }) => instanceId === id); if (index < 0) return false; this.state.encounterInstances.splice(index, 1); return true }
}

export class EncounterStateRepository {
  constructor(state = createEmptyEncounterRunState(), { recentHistoryWindow = 10 } = {}) { this.state = normalizeEncounterRunState(state); this.instances = new EncounterRepository(this.state); this.recentHistoryWindow = recentHistoryWindow }
  serialize() { return normalizeEncounterRunState(this.state) }
  reset() { const travelState = this.state.travelState; const fresh = createEmptyEncounterRunState(); Object.assign(this.state, fresh); Object.assign(travelState, fresh.travelState); this.state.travelState = travelState; return this.state }
  nextSequence() { this.state.encounterSequenceCounter += 1; return this.state.encounterSequenceCounter }
  setOccurrence(id, value) { this.state.occurrenceCountersByEncounterId[id] = Math.max(0, Math.trunc(value)); return this.state.occurrenceCountersByEncounterId[id] }
  setCooldown(id, cooldown) { this.state.cooldowns[id] = structuredClone(cooldown); return this.state.cooldowns[id] }
  clearCooldown(id) { delete this.state.cooldowns[id] }
  markTriggered(instance, definition) { this.instances.save(instance); const count = (this.state.occurrenceCountersByEncounterId[definition.id] ?? 0) + 1; this.state.occurrenceCountersByEncounterId[definition.id] = count; for (const tag of definition.tags) this.state.occurrenceCountersByTag[tag] = (this.state.occurrenceCountersByTag[tag] ?? 0) + 1; this.state.lastEncounterId = definition.id; this.state.lastEncounterWorldDay = instance.worldDay; this.state.lastEncounterWorldTime = instance.worldTime; this.state.recentEncounterIds.push(definition.id); this.state.recentEncounterIds = this.state.recentEncounterIds.slice(-this.recentHistoryWindow); this.state.recentEncounterTags.push(...definition.tags); this.state.recentEncounterTags = this.state.recentEncounterTags.slice(-this.recentHistoryWindow * 3); this.state.triggeredEncounterCount += 1; if (definition.uniquePerRun || definition.repeatPolicy === 'UniquePerRun') this.state.uniqueEncounterIdsUsed = [...new Set([...this.state.uniqueEncounterIdsUsed, definition.id])]; if (definition.cooldownPolicy) this.state.cooldowns[definition.id] = { ...definition.cooldownPolicy, startedWorldMinutes: instance.worldDay * 1440 + instance.worldTime * 60, startedEncounterCount: this.state.triggeredEncounterCount }; return instance }
  markResolved(instanceId, definition, result = 'Completed', phase = null) { const instance = this.instances.get(instanceId); if (!instance) return null; instance.resolved = true; instance.resolutionType = result; instance.currentPhase = phase ?? (result === 'Completed' ? ENCOUNTER_PHASE.COMPLETED : result); this.instances.save(instance); this.state.historyRecords.push({ encounterInstanceId: instance.instanceId, encounterDefinitionId: definition.id, sourceTableId: instance.sourceTableId, encounterType: definition.encounterType, regionId: instance.regionId, locationId: instance.locationId, worldDay: instance.worldDay, worldTime: instance.worldTime, triggerSource: instance.triggerSource, result, detectedBeforeTrigger: instance.detectionResult?.detected ?? null, combatResult: instance.pendingResolution?.combatResult ?? null, rewardsResolved: [...(instance.pendingResolution?.resolvedRewardIds ?? [])] }); return instance }
}
