import { ENCOUNTER_PHASE } from './encounterConstants.js'
import { createItemInstance } from '../items/itemInstance.js'
import { createLootReward } from '../inventory/lootReward.js'
import { REWARD_TYPE } from '../rewards/rewardDefinitions.js'
import { RewardService } from '../rewards/rewardService.js'
import { transitionEncounterPhase } from './encounterPhaseService.js'

const finalPhase = (type) => type === 'Avoided' ? ENCOUNTER_PHASE.AVOIDED : ['Escaped', 'PreCombatEscape', 'CombatEscape'].includes(type) ? ENCOUNTER_PHASE.ESCAPED : type === 'Cancelled' ? ENCOUNTER_PHASE.CANCELLED : type === 'CombatDefeat' ? ENCOUNTER_PHASE.FAILED : ENCOUNTER_PHASE.COMPLETED
export class EncounterResolutionService {
  constructor({ database, stateRepository, travelService = null, rewardServiceFactory = (context) => new RewardService({ character: context.characterState, inventoryManager: context.inventoryManager }), revealPoi = null }) { this.database = database; this.stateRepository = stateRepository; this.travelService = travelService; this.rewardServiceFactory = rewardServiceFactory; this.revealPoi = revealPoi }
  begin(instanceId, resolutionType, definition = {}, context = {}) { const instance = this.stateRepository.instances.get(instanceId); const encounter = instance && this.database.getEncounter(instance.encounterDefinitionId); if (!instance || !encounter) return { ok: false, code: 'ENCOUNTER_DEFINITION_NOT_FOUND' }; if (instance.resolved || instance.pendingResolution?.finalized) return { ok: false, code: 'ENCOUNTER_ALREADY_FINALIZED' }; if (![ENCOUNTER_PHASE.CHOICE_PENDING, ENCOUNTER_PHASE.COMBAT_PENDING, ENCOUNTER_PHASE.NON_COMBAT_PENDING, ENCOUNTER_PHASE.PRESENTATION].includes(instance.currentPhase)) return { ok: false, code: 'ENCOUNTER_INVALID_PHASE' }; if (instance.currentPhase !== ENCOUNTER_PHASE.RESOLVING) transitionEncounterPhase(instance, ENCOUNTER_PHASE.RESOLVING); const stableId = `${instanceId}:${resolutionType}`; if (!instance.pendingResolution) instance.pendingResolution = {}; const pending = instance.pendingResolution; pending.resolutionId = stableId; pending.resolutionType = resolutionType; pending.rewardsGenerated = pending.rewardsGenerated ?? false; pending.resolvedRewardIds = pending.resolvedRewardIds ?? []; pending.finalized = false
    if (!pending.rewardsGenerated) { const rewards = definition.rewards ?? []; const direct = rewards.filter(({ type }) => type !== REWARD_TYPE.GRANT_ITEM); const items = rewards.filter(({ type }) => type === REWARD_TYPE.GRANT_ITEM); const rewardService = this.rewardServiceFactory(context); const directResults = []; for (const reward of direct) { const rewardId = reward.rewardId ?? `${stableId}:${reward.type}:${reward.itemId ?? reward.knowledgeId ?? reward.flag ?? reward.amount ?? directResults.length}`; if (pending.resolvedRewardIds.includes(rewardId)) continue; const applied = rewardService.apply(reward, { sourceType: 'encounter', sourceId: instanceId, day: context.worldDay, time: context.worldTime }); if (applied.ok || ['KNOWLEDGE_ALREADY_DISCOVERED', 'RECIPE_ALREADY_KNOWN'].includes(applied.code)) pending.resolvedRewardIds.push(rewardId); directResults.push(applied) } if (items.length) { pending.generatedLootReward = createLootReward({ sourceName: definition.title ?? encounter.displayName, source: { type: 'encounter', id: instanceId, resolutionType }, itemInstances: items.map((reward) => reward.itemInstance ?? createItemInstance(reward.itemId, { quantity: reward.quantity ?? 1 })) }); instance.pendingLootRewardId = `${stableId}:loot`; pending.pendingLootRewardId = instance.pendingLootRewardId } pending.rewardsGenerated = true; instance.generatedRewards = structuredClone(rewards); for (const target of definition.revealPoiTargets ?? []) this.revealPoi?.(target, instance, context); pending.directRewardResults = directResults }
    this.stateRepository.instances.save(instance); if (instance.pendingLootRewardId) return { ok: true, code: 'ENCOUNTER_LOOT_PENDING', instance, lootReward: pending.generatedLootReward, pendingResolution: pending }; return this.finalizeEncounterResolution(instanceId, context) }
  resolveLoot(instanceId, resolution = 'leave', context = {}) { const instance = this.stateRepository.instances.get(instanceId); if (!instance?.pendingLootRewardId || !instance.pendingResolution?.generatedLootReward) return { ok: false, code: 'ENCOUNTER_LOOT_NOT_PENDING' }; instance.pendingResolution.lootResolution = resolution; instance.pendingResolution.resolvedRewardIds.push(instance.pendingLootRewardId); instance.pendingLootRewardId = null; instance.pendingResolution.pendingLootRewardId = null; this.stateRepository.instances.save(instance); return this.finalizeEncounterResolution(instanceId, context) }
  finalizeEncounterResolution(instanceId, context = {}) { const instance = this.stateRepository.instances.get(instanceId); const encounter = instance && this.database.getEncounter(instance.encounterDefinitionId); if (!instance || !encounter) return { ok: false, code: 'ENCOUNTER_DEFINITION_NOT_FOUND' }; if (instance.resolved) return { ok: false, code: 'ENCOUNTER_ALREADY_FINALIZED' }; if (instance.pendingCombatId || instance.pendingLootRewardId) return { ok: false, code: 'ENCOUNTER_RESOLUTION_PENDING' }; const type = instance.pendingResolution?.resolutionType ?? 'Completed'; const phase = finalPhase(type); instance.pendingResolution.finalized = true; instance.resolutionType = type; instance.resolved = true; instance.currentPhase = phase; this.stateRepository.instances.save(instance); this.stateRepository.markResolved(instanceId, encounter, type, phase); const travel = this.stateRepository.state.travelState; travel.distanceSinceLastTriggeredEncounter = 0; travel.lastTriggeredEncounterInstanceId = instanceId; if (this.travelService) this.travelService.clearPending(); else { travel.pendingEncounterInstanceId = null; travel.movementBlockedByEncounter = false; travel.movementLockReason = null; travel.pendingTriggerState = null } return { ok: true, code: 'ENCOUNTER_FINALIZED', instance: this.stateRepository.instances.get(instanceId), historyRecord: this.stateRepository.state.historyRecords.at(-1), movementUnlocked: !travel.movementBlockedByEncounter } }
  cancelPendingEncounter(instanceId, reason = 'Cancelled') { const instance = this.stateRepository.instances.get(instanceId); if (!instance) return { ok: false, code: 'ENCOUNTER_NOT_FOUND' }; const encounter = this.database.getEncounter(instance.encounterDefinitionId); if (instance.presented) { instance.pendingResolution = { ...(instance.pendingResolution ?? {}), resolutionType: 'Cancelled', cancellationReason: reason, finalized: true }; instance.currentPhase = ENCOUNTER_PHASE.CANCELLED; instance.resolved = true; this.stateRepository.instances.save(instance); this.stateRepository.markResolved(instanceId, encounter, 'Cancelled') } else { instance.currentPhase = ENCOUNTER_PHASE.CANCELLED; instance.resolved = true; instance.resolutionType = 'Cancelled'; instance.localFlags.cancellationReason = reason; this.stateRepository.instances.save(instance) } const travel = this.stateRepository.state.travelState; if (this.travelService) this.travelService.clearPending(reason); else { travel.pendingEncounterInstanceId = null; travel.movementBlockedByEncounter = false; travel.movementLockReason = null; travel.pendingTriggerState = null } return { ok: true, code: 'ENCOUNTER_CANCELLED', historyRecorded: instance.presented } }
}
