import { DETECTION_MODE, ENCOUNTER_PHASE, PREPARATION_STATE } from './encounterConstants.js'
import { ENCOUNTER_AMBUSH_DEFINITIONS, ENCOUNTER_CHOICE_SETS, ENCOUNTER_DETECTION_DEFINITIONS, ENCOUNTER_INTERACTION_CONFIGS } from './encounterInteractionDefinitions.js'
import { createSeededRandom } from './encounterSelectionService.js'
import { transitionEncounterPhase } from './encounterPhaseService.js'

const readStat = (context, id, source) => source === 'Base' ? (context.characterStats?.baseStats?.[id] ?? context.characterState?.stats?.[id] ?? 0) : source === 'Bonus' ? (context.characterStats?.finalStats?.[id] ?? 0) - (context.characterStats?.baseStats?.[id] ?? 0) : (context.characterStats?.finalStats?.[id] ?? context.characterState?.stats?.[id] ?? 0)
const makeResultType = (detected, critical) => critical ? (detected ? 'DETECTION_CRITICAL_SUCCESS' : 'DETECTION_CRITICAL_FAILURE') : detected ? 'DETECTION_SUCCESS' : 'DETECTION_FAILURE'
export class EncounterDetectionService {
  constructor({ database, stateRepository, detectionDefinitions = ENCOUNTER_DETECTION_DEFINITIONS, interactionConfigs = ENCOUNTER_INTERACTION_CONFIGS, ambushDefinitions = ENCOUNTER_AMBUSH_DEFINITIONS, choiceSets = ENCOUNTER_CHOICE_SETS, runSeed = '' }) { this.database = database; this.stateRepository = stateRepository; this.definitions = detectionDefinitions; this.configs = interactionConfigs; this.ambushes = ambushDefinitions; this.choiceSets = choiceSets; this.runSeed = runSeed }
  activatePendingEncounter(instanceId, context = {}) { const travel = this.stateRepository.state.travelState; if (travel.pendingEncounterInstanceId !== instanceId) return { ok: false, code: 'ENCOUNTER_NOT_PENDING' }; const instance = this.stateRepository.instances.get(instanceId); const encounter = instance && this.database.getEncounter(instance.encounterDefinitionId); if (!instance || !encounter) return { ok: false, code: 'ENCOUNTER_DEFINITION_NOT_FOUND' }; if (instance.currentPhase !== ENCOUNTER_PHASE.PENDING_TRIGGER) return { ok: false, code: 'ENCOUNTER_INVALID_PHASE' }; const config = this.configs[encounter.id] ?? {}; const detection = this.definitions[config.detectionDefinitionId] ?? this.definitions.automatic; instance.pendingResolution = { activated: true, detectionDefinitionId: detection.id, detectionResult: null, currentChoiceSetId: null, presentationReady: false, combatResult: null, rewardsGenerated: false, finalized: false }; transitionEncounterPhase(instance, detection.detectionMode === DETECTION_MODE.NONE ? ENCOUNTER_PHASE.PRESENTATION : ENCOUNTER_PHASE.DETECTION); this.stateRepository.instances.save(instance); if (detection.detectionMode === DETECTION_MODE.NONE) return this.present(instance, encounter, { detected: true, preparationState: PREPARATION_STATE.NEUTRAL, resultType: 'DETECTION_NOT_REQUIRED' }); return this.runDetection(instanceId, context) }
  runDetection(instanceId, context = {}) { const instance = this.stateRepository.instances.get(instanceId); const encounter = instance && this.database.getEncounter(instance.encounterDefinitionId); if (!instance || !encounter) return { ok: false, code: 'ENCOUNTER_DEFINITION_NOT_FOUND' }; if (instance.detectionResult) return { ok: true, code: 'DETECTION_ALREADY_RESOLVED', detectionResult: instance.detectionResult, instance }; if (instance.currentPhase !== ENCOUNTER_PHASE.DETECTION) return { ok: false, code: 'ENCOUNTER_INVALID_PHASE' }; const config = this.configs[encounter.id] ?? {}; const definition = this.definitions[config.detectionDefinitionId] ?? this.definitions.automatic; instance.detectionSequenceCounter += 1; const random = context.randomSource ?? createSeededRandom(`${this.runSeed}:${instance.seed}:${instance.detectionSequenceCounter}`); let roll = null; let resolvedValue = 0; let total = Infinity; let detected = true; let usedStat = null
    if (![DETECTION_MODE.NONE, DETECTION_MODE.AUTOMATIC].includes(definition.detectionMode)) { const perception = readStat(context, 'perception', definition.valueSource); const luck = readStat(context, 'luck', definition.valueSource); usedStat = definition.detectionMode === DETECTION_MODE.LUCK ? 'luck' : 'perception'; resolvedValue = usedStat === 'luck' ? luck : perception; roll = Math.floor(random() * definition.randomRange) + 1; total = resolvedValue + roll; detected = total >= (usedStat === 'luck' ? definition.luckDifficulty : definition.perceptionDifficulty); if (!detected && definition.detectionMode === DETECTION_MODE.PERCEPTION_OR_LUCK) { const luckRoll = Math.floor(random() * definition.randomRange) + 1; detected = luck + luckRoll >= definition.luckDifficulty; total = luck + luckRoll; usedStat = 'luck'; roll = luckRoll; resolvedValue = luck } }
    const critical = roll === definition.randomRange || roll === 1; const resultType = makeResultType(detected, critical); const preparationState = critical ? (detected ? definition.criticalSuccessPreparationState : definition.criticalFailurePreparationState) : detected ? definition.detectedPreparationState : definition.undetectedPreparationState; const revealedInformation = detected ? ['PresenceOnly', ...(definition.revealEncounterTypeOnDetection ? ['EncounterType'] : []), ...(definition.revealEncounterIdentityOnDetection ? ['EncounterIdentity'] : []), ...(definition.revealEnemyCountOnDetection ? ['EstimatedEnemyCount'] : [])] : definition.visibleOnFailure ? ['PresenceOnly'] : []
    const detectionResult = { encounterInstanceId: instanceId, detectionMode: definition.detectionMode, detected, critical, resolvedValue, usedStat, valueSource: definition.valueSource, difficulty: usedStat === 'luck' ? definition.luckDifficulty : definition.perceptionDifficulty, roll, total, resultType, revealedInformation, preparationState, selectedPresentationVariantId: detected ? 'detected' : 'undetected', debugDetails: { definitionId: definition.id, lightSourceType: context.activeLightSourceType ?? null } }; instance.detectionResult = detectionResult; instance.preparationState = preparationState; instance.revealedInformation = [...revealedInformation]; instance.pendingResolution.detectionResult = detectionResult; this.stateRepository.instances.save(instance); return this.present(instance, encounter, detectionResult) }
  present(instance, encounter, detectionResult) { if (instance.currentPhase === ENCOUNTER_PHASE.DETECTION) transitionEncounterPhase(instance, ENCOUNTER_PHASE.PRESENTATION); const config = this.configs[encounter.id] ?? {}; const ambush = this.ambushes[config.ambushDefinitionId]; const choiceSetId = detectionResult.detected ? (detectionResult.critical && ambush?.criticalDetectionChoiceSetId ? ambush.criticalDetectionChoiceSetId : ambush?.detectedChoiceSetId ?? config.detectedChoiceSetId) : ambush?.undetectedChoiceSetId ?? config.undetectedChoiceSetId; instance.currentChoiceSetId = choiceSetId ?? (encounter.combatDefinitionId ? 'combat_detected' : null); instance.presented = true; instance.pendingResolution.currentChoiceSetId = instance.currentChoiceSetId; instance.pendingResolution.presentationReady = true; transitionEncounterPhase(instance, ENCOUNTER_PHASE.CHOICE_PENDING); if (!instance.occurrenceRecorded) { this.stateRepository.markTriggered(instance, encounter); instance.occurrenceRecorded = true } this.stateRepository.instances.save(instance); return { ok: true, code: 'ENCOUNTER_PRESENTATION_READY', detectionResult, preparationState: instance.preparationState, choiceSet: this.choiceSets[instance.currentChoiceSetId] ?? null, instance } }
}
