const profile = (data) => Object.freeze({ baseMeterThresholdMinimum: 8, baseMeterThresholdMaximum: 12, roadMeterGainMultiplier: 1, wildernessMeterGainMultiplier: 1, nightMeterGainMultiplier: 1, dayMeterGainMultiplier: 1, safeZoneMeterGainMultiplier: 0, regionThreatMultiplierCurve: Object.freeze([{ value: 0, multiplier: 1 }, { value: 10, multiplier: 1.5 }]), nightThreatMultiplierCurve: Object.freeze([{ value: 0, multiplier: 1 }, { value: 50, multiplier: 1.25 }, { value: 100, multiplier: 1.75 }]), postEncounterGraceDistance: 4, postSafeZoneGraceDistance: 3, minimumDistanceBetweenChecks: 4, minimumDistanceBetweenTriggeredEncounters: 8, checkCooldownWorldMinutes: 30, encounterCooldownWorldMinutes: 120, allowChecksWhileStandingStill: false, allowedLocationTags: Object.freeze(['Road', 'Wilderness']), tags: Object.freeze([]), ...data })
export const ENCOUNTER_FREQUENCY_PROFILES = Object.freeze({
  road_day: profile({ id: 'road_day', displayName: 'Road — Day', baseMeterThresholdMinimum: 11, baseMeterThresholdMaximum: 15, roadMeterGainMultiplier: .7, dayMeterGainMultiplier: .9, minimumDistanceBetweenTriggeredEncounters: 10, tags: ['Road', 'Day'] }),
  road_night: profile({ id: 'road_night', displayName: 'Road — Night', baseMeterThresholdMinimum: 9, baseMeterThresholdMaximum: 13, roadMeterGainMultiplier: .9, nightMeterGainMultiplier: 1.2, tags: ['Road', 'Night'] }),
  wilderness_day: profile({ id: 'wilderness_day', displayName: 'Wilderness — Day', baseMeterThresholdMinimum: 8, baseMeterThresholdMaximum: 11, wildernessMeterGainMultiplier: 1.1, tags: ['Wilderness', 'Day'] }),
  wilderness_night: profile({ id: 'wilderness_night', displayName: 'Wilderness — Night', baseMeterThresholdMinimum: 7, baseMeterThresholdMaximum: 10, wildernessMeterGainMultiplier: 1.25, nightMeterGainMultiplier: 1.35, tags: ['Wilderness', 'Night'] }),
  global_default: profile({ id: 'global_default', displayName: 'Global Travel', tags: ['Global'] }),
})
export class EncounterFrequencyProfileResolver {
  constructor(profiles = ENCOUNTER_FREQUENCY_PROFILES) { this.profiles = profiles }
  get(id) { return this.profiles[id] ?? null }
  resolve(context, state = {}) { if (state.forcedFrequencyProfileId && this.get(state.forcedFrequencyProfileId)) return this.get(state.forcedFrequencyProfileId); const road = context.locationTags.includes('Road'); const wilderness = context.locationTags.includes('Wilderness'); if (road) return this.get(context.isNight ? 'road_night' : 'road_day'); if (wilderness) return this.get(context.isNight ? 'wilderness_night' : 'wilderness_day'); return this.get('global_default') }
}
export const interpolateMultiplier = (curve, value) => { const points = [...curve].sort((a, b) => a.value - b.value); if (value <= points[0].value) return points[0].multiplier; if (value >= points.at(-1).value) return points.at(-1).multiplier; const upperIndex = points.findIndex((point) => point.value >= value); const lower = points[upperIndex - 1]; const upper = points[upperIndex]; const ratio = (value - lower.value) / (upper.value - lower.value); return lower.multiplier + (upper.multiplier - lower.multiplier) * ratio }
