import { ENCOUNTER_AMBUSH_DEFINITIONS, ENCOUNTER_CHOICE_SETS, ENCOUNTER_CHOICES, ENCOUNTER_INTERACTION_CONFIGS } from './encounterInteractionDefinitions.js'

const phaseLabels = { PendingTrigger: 'Encounter approaching', Detection: 'Detection', Presentation: 'Encounter', ChoicePending: 'Choose an action', CombatPending: 'Combat', NonCombatPending: 'Outcome', Resolving: 'Resolving', Completed: 'Completed', Failed: 'Defeat', Avoided: 'Avoided', Escaped: 'Escaped', Cancelled: 'Cancelled' }
const revealedLabels = { PresenceOnly: 'A threat is nearby.', EncounterType: 'The nature of the encounter is known.', EncounterIdentity: 'The threat has been identified.', EstimatedEnemyCount: 'You can estimate the enemy numbers.', ExactEnemyCount: 'The exact enemy count is known.', DangerHint: 'You recognize the danger.', RouteInformation: 'You notice a possible route.' }
const formatCost = (entry) => { const cost = entry.required ?? entry.quantity ?? 1; if (entry.type === 'WorldTime') return `Time: ${cost} minutes.`; if (entry.type === 'Item') return `${entry.itemDefinitionId} ×${cost} (you have ${entry.owned ?? 0}).`; if (entry.type === 'Gold') return `Gold: ${cost} (you have ${entry.owned ?? 0}).`; if (entry.type === 'Wardwood') return `Wardwood: ${cost} (you have ${entry.owned ?? 0}).`; return `${entry.type}: ${cost}.` }
const formatCheck = (check) => `${check.proficiencyId ?? check.statId ?? 'Check'}${check.showDifficulty === false ? '' : ` — difficulty ${check.difficulty}`}`
const formatRequirement = ({ requirement, met }) => `${met ? 'Met' : 'Requires'}: ${requirement.displayText ?? requirement.statId ?? requirement.proficiencyId ?? requirement.itemDefinitionId ?? requirement.type}`
const decorateChoice = (entry) => ({ ...entry, lockReason: entry.status === 'Exhausted' ? 'Already attempted.' : entry.costPreview?.costs?.find(({ missing }) => missing)?.type ? `Missing ${entry.costPreview.costs.find(({ missing }) => missing).type}.` : entry.requirements?.find(({ met }) => !met) ? 'Requirements not met.' : 'Unavailable.', costDisplay: (entry.costPreview?.costs ?? entry.choice.costs).map(formatCost), checkDisplay: entry.choice.checks.map(formatCheck), requirementDisplay: (entry.requirements ?? []).map(formatRequirement) })

export function createEncounterPresentationModel(instance, definition, availabilityResolver, context = {}) {
  if (!instance || !definition) return null
  const config = ENCOUNTER_INTERACTION_CONFIGS[definition.id] ?? {}; const ambush = ENCOUNTER_AMBUSH_DEFINITIONS[config.ambushDefinitionId]
  const rawChoices = availabilityResolver?.list(instance, context) ?? (ENCOUNTER_CHOICE_SETS[instance.currentChoiceSetId]?.choiceIds ?? []).map((id) => ({ choice: ENCOUNTER_CHOICES[id], status: 'Available', available: true, visible: true }))
  const choices = rawChoices.map(decorateChoice).sort((a, b) => (a.choice.sortOrder - b.choice.sortOrder) || a.choice.displayName.localeCompare(b.choice.displayName))
  const identityVisible = instance.revealedInformation.includes('EncounterIdentity'); const typeVisible = instance.revealedInformation.includes('EncounterType')
  const detection = instance.detectionResult; const detected = detection?.detected ?? true
  return { instanceId: instance.instanceId, displayName: identityVisible ? definition.displayName : 'Unknown threat', description: definition.description || (detected ? 'You notice something ahead.' : 'A threat appears without warning.'), encounterType: typeVisible ? definition.encounterType : null, phaseLabel: phaseLabels[instance.currentPhase] ?? 'Encounter', locationLabel: instance.locationId ? `Location: ${instance.locationId}` : instance.regionId ? `Region: ${instance.regionId}` : 'Unknown location', preparationState: instance.preparationState, detectionResult: detection, detectionNarrative: ambush ? (detected ? ambush.revealTextDetected : ambush.revealTextUndetected) : detected ? 'You notice the encounter before it reaches you.' : 'The encounter catches you unaware.', detectionPublicStat: detection?.usedStat ? `${detection.usedStat[0].toUpperCase()}${detection.usedStat.slice(1)} check` : null, revealedInformationLabels: instance.revealedInformation.map((id) => revealedLabels[id]).filter(Boolean), currentChoiceSetId: instance.currentChoiceSetId, choices, pendingCombatId: instance.pendingCombatId, pendingLootRewardId: instance.pendingLootRewardId, pendingResolution: instance.pendingResolution, outcome: instance.pendingResolution?.outcome ?? null, isAmbush: Boolean(ambush), ambushText: ambush ? (detected ? ambush.revealTextDetected : ambush.revealTextUndetected) : '', movementLocked: true, showChoices: instance.currentPhase === 'ChoicePending' && !instance.pendingCombatId && !instance.pendingLootRewardId, canContinue: instance.resolved }
}
