import { createSeededRandom } from './encounterSelectionService.js'
import { EncounterFrequencyProfileResolver } from './encounterFrequencyProfiles.js'
import { EncounterMeterService } from './encounterMeterService.js'
import { EncounterMovementGate } from './encounterMovementGate.js'
import { EncounterTriggerService } from './encounterTriggerService.js'
import { calculateGridTravelDistance, createTravelEncounterContext, createTravelSegment } from './encounterTravelModels.js'
import { TRAVEL_TRIGGER_RESULT } from './encounterConstants.js'
const absoluteMinutes = (context) => (context.worldDay - 1) * 1440 + (typeof context.worldTime === 'object' ? (context.worldTime.hour ?? 0) * 60 + (context.worldTime.minute ?? 0) : context.worldTime * 60)
export class TravelEncounterService {
  constructor({ selectionService, travelState, runSeed = '', profileResolver = new EncounterFrequencyProfileResolver(), meterService = new EncounterMeterService(), movementGate = new EncounterMovementGate(), triggerService = null, minimumSegmentDistance = .01, recentSegmentLimit = 30 }) { this.selectionService = selectionService; this.state = travelState; this.runSeed = runSeed; this.profileResolver = profileResolver; this.meter = meterService; this.gate = movementGate; this.trigger = triggerService ?? new EncounterTriggerService({ selectionService, meterService }); this.minimumSegmentDistance = minimumSegmentDistance; this.recentSegmentLimit = recentSegmentLimit }
  randomFor(context, suffix = 'threshold') { return context.randomSource ?? createSeededRandom(`${this.runSeed}:${this.state.travelSequenceCounter}:${context.regionId}:${context.worldDay}:${suffix}`) }
  buildSegment(context) { const distance = context.travelDistance ?? calculateGridTravelDistance(context.previousPosition, context.currentPosition); const valid = Number.isFinite(distance) && distance >= this.minimumSegmentDistance; return createTravelSegment({ segmentId: `travel-${context.runId}-${this.state.travelSequenceCounter + 1}`, startPosition: context.previousPosition, endPosition: context.currentPosition, distance, regionId: context.regionId, biomeTags: context.biomeTags, locationId: context.locationId, locationTags: context.locationTags, startedWorldDay: context.previousWorldDay, startedWorldTime: context.previousWorldTime, endedWorldDay: context.worldDay, endedWorldTime: context.worldTime, isRoad: context.locationTags.includes('Road'), isWilderness: context.locationTags.includes('Wilderness'), isSafeZone: context.isInSafeZone, nightThreatPercent: context.nightThreatPercent, regionThreatLevel: context.regionThreatLevel, movementSource: context.movementSource, validForEncounterProgress: valid }) }
  previewTravelEncounterTrigger(rawContext = {}) { const context = createTravelEncounterContext(rawContext); const segment = this.buildSegment(context); const profile = this.profileResolver.resolve(context, this.state); const gate = this.gate.evaluate(context, this.state); const meter = gate.canAccumulate && segment.validForEncounterProgress ? this.meter.calculateGain({ ...context, travelDistance: segment.distance }, profile) : { gain: 0, terrainMultiplier: 0, timeMultiplier: 1, nightThreatMultiplier: 1, regionThreatMultiplier: 1 }; const meterAfter = this.state.encounterMeterValue + meter.gain; const now = absoluteMinutes(context); const safeGraceRemaining = this.state.safeZoneGraceActive ? Math.max(0, profile.postSafeZoneGraceDistance - this.state.distanceSinceLeavingSafeZone) : 0; const postEncounterGraceRemaining = this.state.lastTriggeredEncounterInstanceId ? Math.max(0, profile.postEncounterGraceDistance - this.state.distanceSinceLastTriggeredEncounter) : 0; const reasons = [...gate.reasons]; if (!segment.validForEncounterProgress) reasons.push('INVALID_TRAVEL_SEGMENT'); if (safeGraceRemaining > 0) reasons.push('POST_SAFE_ZONE_GRACE_ACTIVE'); if (postEncounterGraceRemaining > 0) reasons.push('POST_ENCOUNTER_GRACE_ACTIVE'); if (this.state.encounterCheckCooldownUntil !== null && now < this.state.encounterCheckCooldownUntil) reasons.push('ENCOUNTER_CHECK_COOLDOWN_ACTIVE'); if (this.state.globalEncounterCooldownUntil !== null && now < this.state.globalEncounterCooldownUntil) reasons.push('GLOBAL_ENCOUNTER_COOLDOWN_ACTIVE'); if (this.state.distanceSinceLastEncounterCheck + segment.distance < profile.minimumDistanceBetweenChecks) reasons.push('MINIMUM_CHECK_DISTANCE'); if (this.state.lastTriggeredEncounterInstanceId && this.state.distanceSinceLastTriggeredEncounter + segment.distance < profile.minimumDistanceBetweenTriggeredEncounters) reasons.push('MINIMUM_ENCOUNTER_DISTANCE'); const wouldPerformCheck = meterAfter >= this.state.encounterMeterThreshold && reasons.length === 0; return { segment, segmentValid: segment.validForEncounterProgress, movementGate: gate, profile, currentMeter: this.state.encounterMeterValue, meterGain: meter.gain, meterAfterSegment: meterAfter, meterDetails: meter, threshold: this.state.encounterMeterThreshold, meterPercentage: this.state.encounterMeterThreshold ? meterAfter / this.state.encounterMeterThreshold : 0, safeZoneGraceRemaining: safeGraceRemaining, postEncounterGraceRemaining, checkCooldownActive: reasons.includes('ENCOUNTER_CHECK_COOLDOWN_ACTIVE'), globalCooldownActive: reasons.includes('GLOBAL_ENCOUNTER_COOLDOWN_ACTIVE'), wouldPerformCheck, blockReasons: reasons, selectionContextPreview: wouldPerformCheck ? this.selectionService.previewEncounterSelection({ ...context, currentSafeZoneStatus: context.isInSafeZone }) : null } }
  processTravelSegment(rawContext = {}) {
    const context = createTravelEncounterContext(rawContext); const segment = this.buildSegment(context); const profile = this.profileResolver.resolve(context, this.state)
    if (!segment.validForEncounterProgress) return { ok: false, code: TRAVEL_TRIGGER_RESULT.INVALID, segment }
    if (context.isInSafeZone) { this.state.wasInSafeZone = true; this.state.safeZoneGraceActive = false; this.state.distanceSinceLeavingSafeZone = 0; this.state.lastRegionId = context.regionId; this.state.lastLocationId = context.locationId; this.state.lastLocationTags = [...context.locationTags]; return { ok: true, code: TRAVEL_TRIGGER_RESULT.SAFE_ZONE, segment, meterGain: 0 } }
    if (this.state.wasInSafeZone) { this.state.wasInSafeZone = false; this.state.safeZoneGraceActive = true; this.state.distanceSinceLeavingSafeZone = 0 }
    const gate = this.gate.evaluate(context, this.state); if (!gate.canAccumulate) return { ok: true, code: this.state.pendingEncounterInstanceId ? TRAVEL_TRIGGER_RESULT.ALREADY_PENDING : TRAVEL_TRIGGER_RESULT.BLOCKED, segment, gate, meterGain: 0 }
    this.state.travelSequenceCounter += 1; segment.segmentId = `travel-${context.runId}-${this.state.travelSequenceCounter}`; segment.validForEncounterProgress = true; this.state.recentTravelSegments.push(segment); this.state.recentTravelSegments = this.state.recentTravelSegments.slice(-this.recentSegmentLimit); this.state.accumulatedTravelDistance += segment.distance; if (segment.isRoad) this.state.accumulatedRoadDistance += segment.distance; if (segment.isWilderness) this.state.accumulatedWildernessDistance += segment.distance; this.state.distanceSinceLastEncounterCheck += segment.distance; this.state.distanceSinceLastTriggeredEncounter += segment.distance; this.state.distanceSinceLeavingSafeZone += segment.distance; this.state.lastMovementWorldDay = context.worldDay; this.state.lastMovementWorldTime = structuredClone(context.worldTime); this.state.lastRegionId = context.regionId; this.state.lastLocationId = context.locationId; this.state.lastLocationTags = [...context.locationTags]
    if (this.state.safeZoneGraceActive && this.state.distanceSinceLeavingSafeZone < profile.postSafeZoneGraceDistance) return { ok: true, code: TRAVEL_TRIGGER_RESULT.SAFE_GRACE, segment, profile, meterGain: 0 }
    this.state.safeZoneGraceActive = false
    if (this.state.lastTriggeredEncounterInstanceId && this.state.distanceSinceLastTriggeredEncounter < profile.postEncounterGraceDistance) return { ok: true, code: TRAVEL_TRIGGER_RESULT.ENCOUNTER_GRACE, segment, profile, meterGain: 0 }
    const now = absoluteMinutes(context); if (this.state.globalEncounterCooldownUntil !== null && now < this.state.globalEncounterCooldownUntil) return { ok: true, code: TRAVEL_TRIGGER_RESULT.GLOBAL_COOLDOWN, segment, profile, meterGain: 0 }
    const meter = this.meter.calculateGain({ ...context, travelDistance: segment.distance }, profile); this.meter.add(this.state, meter.gain)
    if (this.state.encounterMeterValue < this.state.encounterMeterThreshold) return { ok: true, code: TRAVEL_TRIGGER_RESULT.THRESHOLD_NOT_REACHED, segment, profile, meterGain: meter.gain, meterValue: this.state.encounterMeterValue }
    if (this.state.distanceSinceLastEncounterCheck < profile.minimumDistanceBetweenChecks || (this.state.lastTriggeredEncounterInstanceId && this.state.distanceSinceLastTriggeredEncounter < profile.minimumDistanceBetweenTriggeredEncounters)) return { ok: true, code: TRAVEL_TRIGGER_RESULT.DISTANCE_BLOCKED, segment, profile, meterGain: meter.gain }
    if (this.state.encounterCheckCooldownUntil !== null && now < this.state.encounterCheckCooldownUntil) return { ok: true, code: TRAVEL_TRIGGER_RESULT.CHECK_COOLDOWN, segment, profile, meterGain: meter.gain }
    return { ...this.trigger.execute(context, this.state, profile, this.randomFor(context, 'check')), segment, profile, meterGain: meter.gain }
  }
  clearPending(reason) { this.trigger.clearPending(this.state, reason) }
}
