<script setup>
import { computed, ref, watch } from 'vue'
const props = defineProps({ model: { type: Object, required: true }, busy: Boolean, message: { type: String, default: '' } })
const emit = defineEmits(['close', 'execute', 'resume-loot'])
const selectedId = ref(null); const confirming = ref(false)
const selected = computed(() => props.model.actions.find(({ actionId }) => actionId === selectedId.value) ?? null)
watch(() => props.model.instanceId, () => { selectedId.value = null; confirming.value = false })
function requestExecution() { if (!selected.value?.available || props.busy) return; if (selected.value.requiresConfirmation) confirming.value = true; else emit('execute', selected.value.actionId) }
function confirm() { confirming.value = false; emit('execute', selected.value.actionId) }
</script>
<template>
  <div class="poi-overlay" role="dialog" aria-modal="true" aria-labelledby="poi-title" @keydown.esc="!model.pendingLoot && !model.pendingCombat && $emit('close')">
    <section class="poi-window">
      <header><div><small>{{ model.poiType }} · {{ model.region }}</small><h2 id="poi-title">{{ model.displayName }}</h2><div class="poi-badges"><strong>{{ model.status }}</strong><span v-if="model.currentStateName">{{ model.currentStateName }}</span></div></div><button type="button" :disabled="model.pendingCombat" aria-label="Close location" @click="$emit('close')">×</button></header>
      <div class="poi-layout"><section><h3>Location</h3><p>{{ model.description }}</p><article v-if="model.outcome" class="poi-outcome"><h3>{{ model.outcome.title }}</h3><p>{{ model.outcome.description }}</p></article><article v-if="model.pendingCombat"><h3>Combat Pending</h3><p>The danger here has not been resolved.</p></article><article v-if="model.pendingLoot"><h3>Loot Pending</h3><p>Found items are waiting for your decision.</p><button type="button" @click="$emit('resume-loot')">Open Loot Rewards</button></article><p v-if="message" role="status">{{ message }}</p></section>
        <section><h3>Actions</h3><p v-if="model.pendingLoot || model.pendingCombat">Resolve the pending process before taking another action.</p><p v-else-if="!model.actions.length">There is nothing more to do here.</p><div v-else class="poi-actions"><button v-for="entry in model.actions" :key="entry.actionId" type="button" :disabled="!entry.available || busy" :class="{ selected: selectedId === entry.actionId }" @click="selectedId = entry.actionId"><strong>{{ entry.displayName }}</strong><small>{{ entry.status === 'Exhausted' ? 'Already used' : entry.blockReasons[0] ?? entry.status }}</small></button></div>
          <article v-if="selected" class="poi-action-details"><h3>{{ selected.displayName }}</h3><p>{{ selected.description || 'No additional description.' }}</p><h4 v-if="selected.visibleRequirements.length">Requirements</h4><p v-for="hint in selected.visibleRequirements" :key="hint">{{ hint }}</p><h4 v-if="selected.costPreview.costs.length">Costs</h4><p v-for="(cost, index) in selected.costPreview.costs" :key="index">{{ cost.type === 'WorldTime' ? `Time: ${cost.required} minutes` : `${cost.itemDefinitionId ?? cost.tag ?? cost.type}: ${cost.required} required · You have ${cost.owned === Infinity ? 'enough' : cost.owned}` }} · {{ cost.willConsume ? 'Consumed' : 'Not consumed' }}</p><h4 v-if="selected.checkPreview.length">Checks</h4><p v-for="check in selected.checkPreview" :key="check.checkId">{{ check.checkType }}{{ check.difficulty !== null ? ` · Difficulty ${check.difficulty}` : '' }}{{ check.estimatedSuccessChance !== null ? ` · Estimated chance ${Math.round(check.estimatedSuccessChance * 100)}%` : '' }}</p><p v-if="selected.potentialRiskText">{{ selected.potentialRiskText }}</p><p v-if="selected.maximumUses !== null">Uses: {{ selected.currentUses }} / {{ selected.maximumUses }}</p><button type="button" :disabled="!selected.available || busy" @click="requestExecution">{{ busy ? 'Working…' : 'Perform Action' }}</button></article>
        </section></div>
    </section>
    <div v-if="confirming" class="poi-confirm" role="alertdialog" aria-modal="true"><section><h3>Confirm {{ selected.displayName }}</h3><p>{{ selected.potentialRiskText || 'This action may be irreversible.' }}</p><button type="button" @click="confirming = false">Cancel</button><button type="button" @click="confirm">Confirm</button></section></div>
  </div>
</template>
<style scoped>
.poi-overlay{position:fixed;inset:0;z-index:75;display:grid;place-items:center;padding:1rem;background:#020617cc}.poi-window{width:min(72rem,96vw);max-height:92vh;overflow:auto;border:1px solid #64748b;border-radius:1rem;background:#0f172a;color:#e2e8f0;box-shadow:0 2rem 5rem #000}.poi-window>header{display:flex;justify-content:space-between;gap:1rem;padding:1.25rem;border-bottom:1px solid #334155}.poi-window h2{font-size:1.7rem}.poi-layout{display:grid;grid-template-columns:1fr 1fr;gap:1rem;padding:1.25rem}.poi-layout>section,.poi-action-details,.poi-outcome{padding:1rem;border:1px solid #334155;border-radius:.75rem;background:#111c31}.poi-actions{display:grid;gap:.5rem}.poi-actions button{display:flex;justify-content:space-between;text-align:left}.poi-actions button.selected{outline:2px solid #f59e0b}.poi-badges{display:flex;gap:.5rem}.poi-badges>*{padding:.2rem .55rem;border:1px solid #64748b;border-radius:999px}.poi-confirm{position:fixed;inset:0;display:grid;place-items:center;background:#000b}.poi-confirm section{padding:1.5rem;border:1px solid #f59e0b;border-radius:.75rem;background:#172033}@media(max-width:760px){.poi-layout{grid-template-columns:1fr}}
</style>
