import { ITEM_TAG, ITEM_TYPE, WEAPON_CATEGORY, ARMOR_CATEGORY } from '../items/itemConstants.js'
import { MERCHANT_TYPE, STOCK_MODE } from './merchantConstants.js'

const entry = (itemDefinitionId, data = {}) => Object.freeze({ itemDefinitionId, minimum: 1, maximum: 1, purchaseLimit: null, isUniqueStock: false, isProtectedStock: false, priceOverride: null, source: 'merchant_definition', weight: 1, ...data })
export function defineMerchant(data) {
  if (!data.id || !Object.values(MERCHANT_TYPE).includes(data.merchantType)) throw new Error('MerchantDefinition requires id and valid merchantType.')
  return Object.freeze({ portrait: 'merchant-placeholder', acceptedItemTypes: Object.freeze([]), acceptedCategories: Object.freeze([]), acceptedTags: Object.freeze([]), acceptedItemIds: Object.freeze([]), rejectedItemTypes: Object.freeze([]), rejectedItemIds: Object.freeze([]), rejectedTags: Object.freeze([]), tags: Object.freeze([]), optionalStockHints: Object.freeze([]), buyPriceMultiplier: 1, sellPriceMultiplier: 0.4, goldReserve: 500, acceptSoldItemsToStock: true, ...data, acceptedItemTypes: Object.freeze([...(data.acceptedItemTypes ?? [])]), acceptedCategories: Object.freeze([...(data.acceptedCategories ?? [])]), acceptedTags: Object.freeze([...(data.acceptedTags ?? [])]), acceptedItemIds: Object.freeze([...(data.acceptedItemIds ?? [])]), rejectedItemTypes: Object.freeze([...(data.rejectedItemTypes ?? [])]), rejectedItemIds: Object.freeze([...(data.rejectedItemIds ?? [])]), rejectedTags: Object.freeze([...(data.rejectedTags ?? [])]), tags: Object.freeze([...(data.tags ?? [])]), optionalStockHints: Object.freeze([...(data.optionalStockHints ?? [])]), stockDefinition: Object.freeze({ mode: data.stockDefinition.mode, fixed: Object.freeze([...(data.stockDefinition.fixed ?? [])]), random: Object.freeze([...(data.stockDefinition.random ?? [])]), randomPicks: data.stockDefinition.randomPicks ?? 0 }) })
}

const merchants = [
  defineMerchant({ id: 'general_merchant', displayName: 'Mara the Provisioner', description: 'A village trader carrying everyday expedition supplies.', merchantType: MERCHANT_TYPE.GENERAL, locationId: 'main_village', acceptedItemTypes: [ITEM_TYPE.CONSUMABLE, ITEM_TYPE.MATERIAL, ITEM_TYPE.TREASURE, ITEM_TYPE.ACCESSORY], rejectedTags: [ITEM_TAG.QUEST], stockDefinition: { mode: STOCK_MODE.MIXED, fixed: [entry('torch', { minimum: 1, maximum: 3 }), entry('bandage', { minimum: 1, maximum: 4 }), entry('travel_ration', { minimum: 1, maximum: 5 })], random: [entry('wardwood', { minimum: 0, maximum: 3, weight: 3 }), entry('plain_ring'), entry('raw_meat', { minimum: 1, maximum: 3 })], randomPicks: 2 }, goldReserve: 450, optionalStockHints: ['Limited Wardwood supply.', 'Stock does not refresh automatically.'] }),
  defineMerchant({ id: 'blacksmith', displayName: 'Orin the Blacksmith', description: 'A smith dealing in practical arms and armor.', merchantType: MERCHANT_TYPE.BLACKSMITH, locationId: 'main_village', acceptedItemTypes: [ITEM_TYPE.WEAPON, ITEM_TYPE.ARMOR, ITEM_TYPE.SHIELD, ITEM_TYPE.MATERIAL], acceptedTags: [ITEM_TAG.METAL], rejectedTags: [ITEM_TAG.MAGIC], stockDefinition: { mode: STOCK_MODE.MIXED, fixed: [entry('club'), entry('rusty_sword'), entry('item_rusty_dagger'), entry('wooden_staff'), entry('wooden_shield'), entry('leather_armor'), entry('studded_armor'), entry('hide_armor'), entry('ringmail_armor')], random: [entry('chainmail_armor')], randomPicks: 1 }, buyPriceMultiplier: 1.05, sellPriceMultiplier: 0.45, goldReserve: 900, tags: ['weapons', 'armor'] }),
  defineMerchant({ id: 'book_merchant', displayName: 'Selene the Bookseller', description: 'A collector of practical manuals and common historical works.', merchantType: MERCHANT_TYPE.BOOK, locationId: 'main_city', acceptedItemTypes: [ITEM_TYPE.BOOK, ITEM_TYPE.SCROLL], rejectedItemIds: ['legendary_archery_tome'], stockDefinition: { mode: STOCK_MODE.MIXED, fixed: [entry('basic_archery_manual'), entry('history_of_the_old_kingdom'), entry('archery_skill_scroll'), entry('old_kingdom_knowledge_scroll')], random: [entry('journeyman_archery_manual', { weight: 1 }), entry('poor_basic_archery_manual', { weight: 3 })], randomPicks: 1 }, buyPriceMultiplier: 1.15, sellPriceMultiplier: 0.35, goldReserve: 700, optionalStockHints: ['Rare works are assigned manually.'] }),
  defineMerchant({ id: 'hunter_merchant', displayName: 'Tarin the Hunter', description: 'A hunter selling lightweight expedition equipment.', merchantType: MERCHANT_TYPE.HUNTER, locationId: 'hunter_camp', acceptedItemTypes: [ITEM_TYPE.WEAPON, ITEM_TYPE.ARMOR, ITEM_TYPE.MATERIAL, ITEM_TYPE.CONSUMABLE, ITEM_TYPE.BOOK], acceptedCategories: [WEAPON_CATEGORY.BOW, WEAPON_CATEGORY.CROSSBOW, WEAPON_CATEGORY.DAGGER, ARMOR_CATEGORY.HIDE, ARMOR_CATEGORY.WOODLAND], acceptedItemIds: ['wolf_hide', 'wolf_tooth', 'raw_meat'], rejectedTags: [ITEM_TAG.HEAVY], stockDefinition: { mode: STOCK_MODE.MIXED, fixed: [entry('short_bow'), entry('simple_crossbow'), entry('item_rusty_dagger'), entry('hide_armor'), entry('woodland_armor'), entry('basic_archery_manual')], random: [entry('wardwood', { minimum: 0, maximum: 2 }), entry('bandage', { minimum: 1, maximum: 2 })], randomPicks: 2 }, goldReserve: 550, optionalStockHints: ['No ammunition required.', 'Limited Wardwood supply.'] }),
  defineMerchant({ id: 'innkeeper', displayName: 'Elara the Innkeeper', description: 'An innkeeper carrying food and basic travel supplies.', merchantType: MERCHANT_TYPE.INNKEEPER, locationId: 'main_village', acceptedItemTypes: [ITEM_TYPE.CONSUMABLE, ITEM_TYPE.MATERIAL], acceptedItemIds: ['raw_meat'], rejectedItemTypes: [ITEM_TYPE.WEAPON, ITEM_TYPE.ARMOR, ITEM_TYPE.BOOK, ITEM_TYPE.SCROLL], stockDefinition: { mode: STOCK_MODE.MIXED, fixed: [entry('travel_ration', { minimum: 2, maximum: 5 }), entry('bandage', { minimum: 1, maximum: 3 }), entry('torch', { minimum: 1, maximum: 2 })], random: [entry('wardwood', { minimum: 0, maximum: 2 })], randomPicks: 1 }, goldReserve: 350, optionalStockHints: ['Stock does not refresh automatically.'] }),
]

export const MERCHANT_LIST = Object.freeze(merchants)
export const MERCHANT_DEFINITIONS = Object.freeze(Object.fromEntries(merchants.map((merchant) => [merchant.id, merchant])))
