import { POI_ACTIONS } from './poiDefinitions.js'
import { PoiActionAvailabilityResolver } from './poiActionAvailabilityResolver.js'
import { PoiActionCostService } from './poiActionCostService.js'
import { PoiCheckService } from './poiCheckService.js'

export class PoiActionService {
  constructor({ poiService, actions = POI_ACTIONS, availabilityResolver = new PoiActionAvailabilityResolver(), costService = new PoiActionCostService(), checkService = new PoiCheckService() } = {}) { this.poiService = poiService; this.actions = actions; this.availability = availabilityResolver; this.costs = costService; this.checks = checkService }
  locate(instanceId, actionId) { const instance = this.poiService.getInstance(instanceId); if (!instance) return { ok: false, code: 'POI_NOT_FOUND' }; const definition = this.poiService.getDefinition(instance.poiDefinitionId); if (!definition) return { ok: false, code: 'POI_DEFINITION_NOT_FOUND' }; const state = definition.stateDefinitions.find(({ id }) => id === instance.currentStateId); if (!state) return { ok: false, code: 'POI_STATE_NOT_FOUND' }; const action = this.actions[actionId]; if (!action) return { ok: false, code: 'ACTION_NOT_FOUND' }; if (!state.availableActionIds.includes(actionId)) return { ok: false, code: 'ACTION_NOT_IN_CURRENT_STATE' }; return { ok: true, instance, definition, state, action } }
  preview(instanceId, actionId, context) { const located = this.locate(instanceId, actionId); if (!located.ok) return located; const availability = this.availability.resolve(located.action, located.instance, context); const costPreview = this.costs.preview(located.action.costs, context); const checkPreview = located.action.checks.map((check) => this.checks.preview(check, context)); const available = availability.available && costPreview.canPayAllCosts; return { ok: true, actionId, displayName: located.action.displayName, description: located.action.description, status: availability.status, available, exhausted: availability.exhausted, visible: availability.visible, blockReasons: [...availability.blockReasons, ...(!costPreview.canPayAllCosts ? ['Action costs cannot be paid.'] : [])], visibleRequirements: availability.visibleRequirementHints, hiddenRequirementCount: availability.hiddenRequirementCount, costPreview, checkPreview, currentUses: availability.currentUses, maximumUses: availability.maximumUses, requiresConfirmation: located.action.confirmationType !== 'None', potentialRiskText: checkPreview.some(({ risk }) => risk) ? 'This action can fail.' : null, definition: located.definition, state: located.state, action: located.action, availability }
  }
  execute(instanceId, actionId, context) { if (context.isInCombat) return { ok: false, code: 'POI_INTERACTION_BLOCKED_DURING_COMBAT' }; const preview = this.preview(instanceId, actionId, context); if (!preview.ok) return preview; if (!preview.visible) return { ok: false, code: 'ACTION_HIDDEN' }; if (preview.exhausted) return { ok: false, code: 'ACTION_EXHAUSTED' }; if (!preview.available) return { ok: false, code: preview.costPreview.canPayAllCosts ? 'ACTION_LOCKED' : 'REQUIREMENTS_NOT_MET', preview }; const payment = this.costs.pay(preview.action.costs, context); if (!payment.ok) return payment; const checks = this.checks.executeMany(preview.action.checks, preview.action.checkStrategy, context); if (!checks.success && !preview.action.consumesCostsOnFailure) this.costs.rollback(payment.snapshot, context); const outcomeId = checks.criticalSuccess ? (preview.action.criticalSuccessOutcomeId ?? preview.action.successOutcomeId) : checks.criticalFailure ? (preview.action.criticalFailureOutcomeId ?? preview.action.failureOutcomeId) : checks.success ? (preview.action.successOutcomeId ?? preview.action.defaultOutcomeId) : (preview.action.failureOutcomeId ?? preview.action.defaultOutcomeId); this.poiService.mutate(instanceId, (instance) => { instance.isDiscovered = true; instance.isVisited = true; instance.interactionCounters[actionId] = (instance.interactionCounters[actionId] ?? 0) + 1; instance.lastCheckResults = checks.results; instance.pendingOutcomeId = outcomeId; instance.lastInteractionWorldDay = context.worldDay; instance.lastInteractionWorldTime = context.worldTime }, 'PENDING_OUTCOME_CREATED'); return { ok: true, code: 'PENDING_OUTCOME_CREATED', actionId, outcomeId, success: checks.success, checkResults: checks.results, paidCosts: payment.preview.costs, pendingOutcomeId: outcomeId } }
  open(instanceId, context) { return context.isInCombat ? { ok: false, code: 'POI_INTERACTION_BLOCKED_DURING_COMBAT' } : this.poiService.visit(instanceId, { day: context.worldDay, time: context.worldTime }) }
  clearPendingOutcome(instanceId) { return this.poiService.mutate(instanceId, (instance) => { instance.pendingOutcomeId = null }, 'PENDING_OUTCOME_CLEARED') }
}
