import { resolveItemInstance } from '../items/itemInstance.js'
import { POI_COST_TYPE } from './poiConstants.js'

export class PoiActionCostService {
  preview(costs, context) { const entries = costs.map((cost) => { let owned = 0; if (cost.type === POI_COST_TYPE.ITEM) owned = context.character.inventory.filter((item) => item.definitionId === cost.itemDefinitionId).reduce((n, item) => n + item.quantity, 0); else if (cost.type === POI_COST_TYPE.ITEM_TAG) owned = context.character.inventory.filter((item) => resolveItemInstance(item)?.tags.includes(cost.tag)).reduce((n, item) => n + item.quantity, 0); else if (cost.type === POI_COST_TYPE.GOLD) owned = context.character.gold; else if (cost.type === POI_COST_TYPE.WARDWOOD) owned = context.character.wardwood; else if (cost.type === POI_COST_TYPE.WORLD_TIME) owned = Infinity; const required = cost.quantity ?? 1; return { ...cost, owned, required, missing: Math.max(0, required - owned), willConsume: cost.consume !== false } }); return { costs: entries, canPayAllCosts: entries.every(({ missing, type }) => missing === 0 && ![POI_COST_TYPE.HEALTH, POI_COST_TYPE.CUSTOM].includes(type)) } }
  removeItems(cost, context) { let remaining = cost.quantity ?? 1; for (const item of [...context.character.inventory]) { const matches = cost.type === POI_COST_TYPE.ITEM ? item.definitionId === cost.itemDefinitionId : resolveItemInstance(item)?.tags.includes(cost.tag); if (!matches || !remaining) continue; const amount = Math.min(item.quantity, remaining); const removed = context.inventoryManager.remove(item.instanceId, amount); if (!removed.ok) return false; remaining -= amount } return remaining === 0 }
  pay(costs, context) { const preview = this.preview(costs, context); if (!preview.canPayAllCosts) return { ok: false, code: preview.costs.find(({ missing }) => missing)?.type === POI_COST_TYPE.GOLD ? 'MISSING_GOLD_COST' : preview.costs.find(({ missing }) => missing)?.type === POI_COST_TYPE.WARDWOOD ? 'MISSING_WARDWOOD_COST' : 'MISSING_ITEM_COST', preview }; const snapshot = { inventory: [...context.character.inventory], gold: context.character.gold, wardwood: context.character.wardwood, batches: structuredClone(context.character.wardwoodBatches) }; try { for (const cost of costs) { if (cost.consume === false) continue; if ([POI_COST_TYPE.ITEM, POI_COST_TYPE.ITEM_TAG].includes(cost.type) && !this.removeItems(cost, context)) throw new Error('ITEM_PAYMENT_FAILED'); if (cost.type === POI_COST_TYPE.GOLD) context.character.gold -= cost.quantity; if (cost.type === POI_COST_TYPE.WARDWOOD && !context.wardwoodService.consume(cost.quantity, context.worldDay).ok) throw new Error('WARDWOOD_PAYMENT_FAILED'); if (cost.type === POI_COST_TYPE.WORLD_TIME) { const moved = context.advanceWorldTime(cost.quantity); if (moved?.ok === false) throw new Error('TIME_PAYMENT_FAILED') } } return { ok: true, code: 'COSTS_PAID', preview, snapshot } } catch (error) { context.character.inventory.splice(0, context.character.inventory.length, ...snapshot.inventory); context.character.gold = snapshot.gold; context.character.wardwood = snapshot.wardwood; context.character.wardwoodBatches = snapshot.batches; return { ok: false, code: 'COST_PAYMENT_FAILED', reason: String(error) } } }
  rollback(snapshot, context) { if (!snapshot) return; context.character.inventory.splice(0, context.character.inventory.length, ...snapshot.inventory); context.character.gold = snapshot.gold; context.character.wardwood = snapshot.wardwood; context.character.wardwoodBatches = snapshot.batches }
}
