import { POI_ACTION_VISIBILITY, POI_CHECK_TYPE, POI_COMPARISON, POI_COMPLETION_POLICY, POI_COST_TYPE, POI_DISCOVERY_MODE, POI_RESET_POLICY, POI_TYPE, POI_VALUE_SOURCE } from './poiConstants.js'
import { definePoi, definePoiAction, definePoiDiscovery } from './poiModels.js'

export const POI_DISCOVERY_DEFINITIONS = Object.freeze({ visible: definePoiDiscovery({ id: 'visible', discoveryMode: POI_DISCOVERY_MODE.VISIBLE }), standard: definePoiDiscovery({ id: 'standard', discoveryMode: POI_DISCOVERY_MODE.PROXIMITY, discoveryRadius: 2 }), hidden: definePoiDiscovery({ id: 'hidden', discoveryMode: POI_DISCOVERY_MODE.PERCEPTION, discoveryRadius: 2, perceptionDifficulty: 7 }) })
export const POI_ACTIONS = Object.freeze(Object.fromEntries([
  definePoiAction({ id: 'cart_search', displayName: 'Search the cart', costs: [{ type: POI_COST_TYPE.WORLD_TIME, quantity: 30 }], checks: [{ id: 'cart-perception', checkType: POI_CHECK_TYPE.STAT, statId: 'perception', valueSource: POI_VALUE_SOURCE.FINAL_STAT, difficulty: 7, comparisonMode: POI_COMPARISON.VALUE_PLUS_ROLL }], successOutcomeId: 'abandoned_cart_search_success', failureOutcomeId: 'abandoned_cart_search_failure', maximumUses: 2 }),
  definePoiAction({ id: 'cart_tracks', displayName: 'Inspect the tracks', costs: [{ type: POI_COST_TYPE.WORLD_TIME, quantity: 10 }], checks: [{ id: 'tracks', checkType: POI_CHECK_TYPE.STAT, statId: 'perception', difficulty: 6, comparisonMode: POI_COMPARISON.VALUE_PLUS_ROLL }], successOutcomeId: 'abandoned_cart_tracks_success', failureOutcomeId: 'abandoned_cart_tracks_failure' }),
  definePoiAction({ id: 'shrine_pray', displayName: 'Pray', costs: [{ type: POI_COST_TYPE.WORLD_TIME, quantity: 10 }], checks: [{ id: 'pray', checkType: POI_CHECK_TYPE.STAT, statId: 'wisdom', difficulty: 3 }], successOutcomeId: 'shrine_pray_success', failureOutcomeId: 'shrine_pray_failure' }),
  definePoiAction({ id: 'shrine_study', displayName: 'Study the inscription', visibilityMode: POI_ACTION_VISIBILITY.SHOW_LOCKED, availabilityRequirements: [{ type: 'knowledge', knowledgeId: 'old_kingdom_history', displayText: 'You do not understand the inscription.', hideRequirementType: true }], defaultOutcomeId: 'shrine_study' }),
  definePoiAction({ id: 'shrine_desecrate', displayName: 'Desecrate', confirmationType: 'Dangerous', defaultOutcomeId: 'shrine_desecrate' }),
  definePoiAction({ id: 'cache_open', displayName: 'Open the cache', costs: [{ type: POI_COST_TYPE.WORLD_TIME, quantity: 5 }], defaultOutcomeId: 'hunter_cache_open', maximumUses: 1 }),
  definePoiAction({ id: 'mine_inspect', displayName: 'Inspect the supports', checks: [{ id: 'mine-inspect', checkType: POI_CHECK_TYPE.STAT, statId: 'perception', difficulty: 7, comparisonMode: POI_COMPARISON.VALUE_PLUS_ROLL }], successOutcomeId: 'mine_inspect_success', failureOutcomeId: 'mine_inspect_failure' }),
  definePoiAction({ id: 'mine_clear', displayName: 'Clear debris', availabilityRequirements: [{ type: 'attribute', attribute: 'strength', minimum: 3, displayText: 'Requires sufficient Strength.' }], costs: [{ type: POI_COST_TYPE.WORLD_TIME, quantity: 60 }], defaultOutcomeId: 'mine_clear' }),
  definePoiAction({ id: 'mine_tool', displayName: 'Use a tool', availabilityRequirements: [{ type: 'item_tag', tag: 'Tool', displayText: 'Requires a suitable tool.' }], costs: [{ type: POI_COST_TYPE.ITEM_TAG, tag: 'Tool', consume: false }], defaultOutcomeId: 'mine_tool' }),
  definePoiAction({ id: 'shelter_inspect', displayName: 'Inspect the shelter', checks: [{ id: 'shelter', checkType: POI_CHECK_TYPE.STAT, statId: 'perception', difficulty: 6, comparisonMode: POI_COMPARISON.VALUE_PLUS_ROLL }], successOutcomeId: 'shelter_inspect_success', failureOutcomeId: 'shelter_inspect_failure' }),
  definePoiAction({ id: 'shelter_secure', displayName: 'Secure the entrance', costs: [{ type: POI_COST_TYPE.WARDWOOD, quantity: 1 }], defaultOutcomeId: 'shelter_secure' }),
].map((action) => [action.id, action])))
const states = (availableActionIds) => [{ id: 'untouched', availableActionIds }, { id: 'searched', availableActionIds }, { id: 'completed', availableActionIds: [], isCompletedState: true }, { id: 'exhausted', availableActionIds: [], isCompletedState: true, isExhaustedState: true, isTerminalState: true }]
export const POI_DEFINITIONS = Object.freeze([
  definePoi({ id: 'abandoned_cart', displayName: 'Abandoned Cart', description: 'A broken cart left beside an old trail.', poiType: POI_TYPE.WRECK, locationId: 'meadows-wilds', regionId: 'meadows', biomeTags: ['grassland'], mapIconId: 'poi-cart', visualId: 'abandoned-cart', discoveryDefinitionId: 'visible', initialStateId: 'untouched', stateDefinitions: states(['cart_search', 'cart_tracks']), tags: ['roadside'], resetPolicy: POI_RESET_POLICY.NEW_RUN, completionPolicy: POI_COMPLETION_POLICY.BECOME_EXHAUSTED }),
  definePoi({ id: 'old_shrine', displayName: 'Old Shrine', description: 'A weathered shrine from an earlier age.', poiType: POI_TYPE.SHRINE, locationId: 'meadows-wilds', regionId: 'meadows', biomeTags: ['grassland'], mapIconId: 'poi-shrine', visualId: 'old-shrine', discoveryDefinitionId: 'standard', initialStateId: 'untouched', stateDefinitions: states(['shrine_pray', 'shrine_study', 'shrine_desecrate']), tags: ['sacred'], resetPolicy: POI_RESET_POLICY.NEVER, completionPolicy: POI_COMPLETION_POLICY.CHANGE_STATE }),
  definePoi({ id: 'hunter_cache', displayName: 'Hunter Cache', description: 'A concealed supply cache.', poiType: POI_TYPE.SECRET, locationId: 'meadows-forest', regionId: 'meadows', biomeTags: ['forest'], mapIconId: 'poi-cache', visualId: 'hunter-cache', discoveryDefinitionId: 'hidden', initialStateId: 'untouched', stateDefinitions: states(['cache_open']), tags: ['hidden', 'hunter'], resetPolicy: POI_RESET_POLICY.NEW_RUN, completionPolicy: POI_COMPLETION_POLICY.BECOME_EXHAUSTED }),
  definePoi({ id: 'collapsed_mine', displayName: 'Collapsed Mine', description: 'A mine entrance buried under fallen stone.', poiType: POI_TYPE.HAZARD, locationId: 'meadows-hills', regionId: 'meadows', biomeTags: ['hills'], mapIconId: 'poi-mine', visualId: 'collapsed-mine', discoveryDefinitionId: 'standard', initialStateId: 'untouched', stateDefinitions: states(['mine_inspect', 'mine_clear', 'mine_tool']), tags: ['mine'], resetPolicy: POI_RESET_POLICY.NEVER, completionPolicy: POI_COMPLETION_POLICY.REMAIN }),
  definePoi({ id: 'abandoned_shelter', displayName: 'Abandoned Shelter', description: 'A crude shelter with no recent occupants.', poiType: POI_TYPE.SHELTER, locationId: 'meadows-forest', regionId: 'meadows', biomeTags: ['forest'], mapIconId: 'poi-shelter', visualId: 'abandoned-shelter', discoveryDefinitionId: 'standard', initialStateId: 'untouched', stateDefinitions: states(['shelter_inspect', 'shelter_secure']), tags: ['shelter'], resetPolicy: POI_RESET_POLICY.NEW_RUN, completionPolicy: POI_COMPLETION_POLICY.REMAIN }),
])
