import { POI_DISCOVERY_MODE } from './poiConstants.js'
import { POI_DISCOVERY_DEFINITIONS } from './poiDefinitions.js'

const distance = (a, b) => Math.max(Math.abs(a.row - b.row), Math.abs(a.column - b.column))
export class PoiDiscoveryService {
  constructor({ poiService, discoveryDefinitions = POI_DISCOVERY_DEFINITIONS } = {}) { this.poiService = poiService; this.definitions = discoveryDefinitions }
  reveal(instanceId, sourceType, context = {}, sourceId = null) { return this.poiService.mutate(instanceId, (instance) => { instance.isDiscovered = true; instance.discoverySourceType = sourceType; instance.discoverySourceId = sourceId; instance.discoveredWorldDay = context.worldDay ?? null; instance.discoveredWorldTime = context.worldTime ?? null }, 'POI_DISCOVERED') }
  evaluate(instanceId, context = {}, options = {}) { const instance = this.poiService.getInstance(instanceId); const definition = instance && this.poiService.getDefinition(instance.poiDefinitionId); const discovery = definition && this.definitions[definition.discoveryDefinitionId]; if (!instance || !definition || !discovery) return { ok: false, code: 'POI_NOT_FOUND' }; if (instance.isDiscovered) return { ok: true, code: 'POI_ALREADY_DISCOVERED', instance }; const inRange = context.worldPosition && distance(context.worldPosition, instance.worldPosition) <= discovery.discoveryRadius; const mode = discovery.discoveryMode; if (mode === POI_DISCOVERY_MODE.VISIBLE || (mode === POI_DISCOVERY_MODE.REGION_ENTRY && context.regionId === instance.regionId)) return this.reveal(instanceId, mode, context); if (mode === POI_DISCOVERY_MODE.PROXIMITY) return inRange ? this.reveal(instanceId, 'Proximity', context) : { ok: false, code: 'POI_OUT_OF_RANGE' }; if (mode === POI_DISCOVERY_MODE.KNOWLEDGE) return inRange && discovery.requiredKnowledgeIds.every((id) => context.knownKnowledgeIds?.includes(id)) ? this.reveal(instanceId, 'Knowledge', context) : { ok: false, code: 'KNOWLEDGE_REQUIRED' }; if (mode === POI_DISCOVERY_MODE.PERCEPTION && inRange) { instance.discoveryAttempts += 1; const roll = options.roll ?? Math.floor((context.controlledRandomSource?.() ?? 0) * 10) + 1; const value = context.characterStats?.finalStats?.perception ?? context.character?.stats?.perception ?? 0; if (value + roll >= discovery.perceptionDifficulty) return this.reveal(instanceId, 'Perception', context); return discovery.revealOnFailedAttempt ? this.reveal(instanceId, 'PerceptionFailure', context) : { ok: false, code: 'PERCEPTION_DISCOVERY_FAILED', roll, resolvedValue: value } } return { ok: false, code: 'DISCOVERY_MODE_REQUIRES_EXPLICIT_REVEAL' } }
  revealByMap(criteria, context = {}) { return this.revealMatching(criteria, 'MapScroll', context) }
  revealByOtherPoi(criteria, sourcePoiId, context = {}) { return this.revealMatching(criteria, 'OtherPoi', context, sourcePoiId) }
  revealMatching(criteria, source, context, sourceId = null) { const matches = this.poiService.repository.getAll().filter((instance) => (!criteria.poiInstanceId || instance.instanceId === criteria.poiInstanceId) && (!criteria.poiDefinitionId || instance.poiDefinitionId === criteria.poiDefinitionId) && (!criteria.regionId || instance.regionId === criteria.regionId) && (!criteria.tag || this.poiService.getDefinition(instance.poiDefinitionId)?.tags.includes(criteria.tag))); return { ok: true, results: matches.map((instance) => this.reveal(instance.instanceId, source, context, sourceId)) } }
}
