import { POI_ACTION_VISIBILITY, POI_CHECK_STRATEGY, POI_COMPARISON, POI_COMPLETION_POLICY, POI_DISCOVERY_MODE, POI_RESET_POLICY, POI_TYPE, POI_VALUE_SOURCE } from './poiConstants.js'

const frozenArray = (value = []) => Object.freeze([...value])
export const definePoiCost = (data = {}) => Object.freeze({ quantity: 1, consume: true, allowStack: true, optionalAcceptedTags: frozenArray(), ...data, optionalAcceptedTags: frozenArray(data.optionalAcceptedTags) })
export const definePoiCheck = (data = {}) => Object.freeze({ id: data.id, valueSource: POI_VALUE_SOURCE.FINAL_STAT, difficulty: 0, comparisonMode: POI_COMPARISON.GREATER_OR_EQUAL, allowEquipmentBonus: true, allowTemporaryBonus: true, criticalSuccessThreshold: null, criticalFailureThreshold: null, showDifficulty: true, showChance: true, ...data, randomRange: Object.freeze({ minimum: 1, maximum: 10, ...(data.randomRange ?? {}) }), tags: frozenArray(data.tags) })
export const definePoiAction = (data = {}) => Object.freeze({ id: data.id ?? null, displayName: data.id ?? '', description: '', visibilityMode: POI_ACTION_VISIBILITY.ALWAYS_VISIBLE, visibilityRequirements: frozenArray(), availabilityRequirements: frozenArray(), costs: frozenArray(), checks: frozenArray(), checkStrategy: POI_CHECK_STRATEGY.ALL_MUST_PASS, successOutcomeId: null, failureOutcomeId: null, criticalSuccessOutcomeId: null, criticalFailureOutcomeId: null, defaultOutcomeId: null, nextStateId: null, isRepeatable: true, maximumUses: null, confirmationType: 'None', consumesCostsOnFailure: true, tags: frozenArray(), sortOrder: 0, ...data, visibilityRequirements: frozenArray(data.visibilityRequirements), availabilityRequirements: frozenArray(data.availabilityRequirements), costs: Object.freeze((data.costs ?? []).map(definePoiCost)), checks: Object.freeze((data.checks ?? []).map(definePoiCheck)), tags: frozenArray(data.tags) })
export const definePoiEffect = (data = {}) => Object.freeze({ type: data.type ?? 'Custom', ...data })
export const definePoiStateTransition = (data = {}) => Object.freeze({ fromStateId: null, toStateId: null, transitionTiming: 'AfterAllPendingResolved', requiredResolutionState: null, applyOnCombatVictory: false, applyOnCombatDefeat: false, applyOnCombatEscape: false, applyOnLootResolved: false, applyImmediately: false, markCompleted: false, markExhausted: false, ...data })
export const definePoiCombatTrigger = (data = {}) => Object.freeze({ encounterDefinitionId: data.encounterDefinitionId, combatStartMode: 'Immediate', surpriseMode: 'NoSurprise', playerInitiativeModifier: 0, enemyInitiativeModifier: 0, allowEscape: true, combatContextTags: frozenArray(data.combatContextTags), pendingResolutionId: null, ...data })
export const definePoiOutcome = (data = {}) => Object.freeze({ id: data.id ?? null, title: data.id ?? '', description: '', effects: Object.freeze((data.effects ?? []).map(definePoiEffect)), rewards: frozenArray(data.rewards), randomRewardTableIds: frozenArray(data.randomRewardTableIds), nextStateId: null, stateTransition: null, stateTransitionMode: 'AfterAllPendingResolved', setLocalFlags: frozenArray(data.setLocalFlags), clearLocalFlags: frozenArray(data.clearLocalFlags), setWorldFlags: frozenArray(data.setWorldFlags), clearWorldFlags: frozenArray(data.clearWorldFlags), setRegionFlags: frozenArray(data.setRegionFlags), clearRegionFlags: frozenArray(data.clearRegionFlags), revealPoiTargets: frozenArray(data.revealPoiTargets), startCombatEncounterId: null, combatTriggerDefinition: null, combatResolutionDefinition: null, markVisited: true, markCompleted: false, markExhausted: false, consumePoi: false, closePoiAfterExecution: true, allowRepeatExecution: false, executionOrder: 'Standard', tags: frozenArray(data.tags), ...data })
export const definePoiDiscovery = (data = {}) => Object.freeze({ id: data.id, discoveryMode: POI_DISCOVERY_MODE.PROXIMITY, discoveryRadius: 1, requiredKnowledgeIds: frozenArray(), perceptionDifficulty: 0, allowRepeatedAttempts: true, attemptCooldown: null, revealOnFailedAttempt: false, showDiscoveryFeedback: true, revealOnRegionEnter: false, revealOnQuest: false, revealOnMap: false, revealOnOtherPoi: false, ...data, requiredKnowledgeIds: frozenArray(data.requiredKnowledgeIds) })
export const definePoiState = (data) => Object.freeze({ id: data.id, displayNameOverride: null, descriptionOverride: null, visualOverride: null, availableActionIds: frozenArray(), enterEffects: frozenArray(), exitEffects: frozenArray(), isCompletedState: false, isExhaustedState: false, isTerminalState: false, ...data, availableActionIds: frozenArray(data.availableActionIds), enterEffects: frozenArray(data.enterEffects), exitEffects: frozenArray(data.exitEffects) })
export function definePoi(data) {
  if (!data?.id || !data.displayName || !Object.values(POI_TYPE).includes(data.poiType)) throw new Error('PoiDefinition requires id, displayName and a valid poiType.')
  const states = Object.freeze((data.stateDefinitions ?? []).map(definePoiState))
  if (!states.some(({ id }) => id === data.initialStateId)) throw new Error(`PoiDefinition ${data.id} has an invalid initialStateId.`)
  return Object.freeze({ description: '', locationId: null, regionId: null, biomeTags: frozenArray(), mapIconId: null, visualId: null, discoveryDefinitionId: null, tags: frozenArray(), isUnique: true, isRepeatable: false, resetPolicy: POI_RESET_POLICY.NEVER, completionPolicy: POI_COMPLETION_POLICY.REMAIN, ...data, biomeTags: frozenArray(data.biomeTags), tags: frozenArray(data.tags), stateDefinitions: states })
}
export function createPoiInstance(definition, { instanceId, runId, seed, worldPosition, locationId, regionId } = {}) {
  if (!definition) throw new Error('PoiDefinition is required.')
  return { instanceId: instanceId ?? `${definition.id}-${runId}`, poiDefinitionId: definition.id, generatedForRunId: runId, seed: seed ?? null, worldPosition: { row: worldPosition?.row ?? 0, column: worldPosition?.column ?? 0 }, locationId: locationId ?? definition.locationId, regionId: regionId ?? definition.regionId, currentStateId: definition.initialStateId, isDiscovered: false, isVisited: false, isCompleted: false, isExhausted: false, isActive: true, discoverySourceType: null, discoverySourceId: null, discoveredWorldDay: null, discoveredWorldTime: null, discoveryAttempts: 0, localFlags: {}, interactionCounters: {}, claimedRewardIds: [], finalizedOutcomeIds: [], pendingOutcomeId: null, pendingCombatId: null, pendingLootRewardId: null, pendingResolution: null, lastCheckResults: [], lastOutcomeResult: null, lastInteractionWorldDay: null, lastInteractionWorldTime: null }
}
